### PR TITLE
VirtualBox: use dns proxy mode

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
I'm not sure it's a good idea. I know that having to `restart` to fix DNS is annoying, but IIRC the alternative (we originally introduced this settings in https://github.com/docker/machine/pull/1069) is worse (unfixable).

**Comment by dgageot** [comment]
We've never tried this settings. We used dnsresolver, not dnsproxy. Dnsresolver is known to have bugs. It seems that dnsproxy has no such problem

**Comment by nathanleclaire** [comment]
Maybe it's fixed in VirtualBox > 5, but https://www.virtualbox.org/ticket/13002 (linked to from the PR mentioned above) suggests that setting `--natdnsproxy on` causes DNS lookups to take a very long time (~5 seconds).  I'm going to fiddle a bit and see if the issue still exists.

**Comment by nathanleclaire** [comment]
I'm not seeing any issues after some testing so I'm willing to give it a shot (maybe there were issues in 4.*.* that were fixed in 5).  LGTM

**Pull request merged**
