### PR TITLE
fig bug: ssh timeout when create a machine using vmwarefusion driver.…

### PR DESCRIPTION
**Pull request by pphetra**
… See issue https://github.com/docker/machine/issues/4137

### CODE REVIEW

**Comment by shin-** [comment]
@SvenDowideit Do you mind taking a look at this one? Seems related to your changes in https://github.com/docker/machine/pull/4107 :cat:

**Comment by SvenDowideit** [comment]
@shin- yup - LGTM - @pphetra do you want to make the same fix to `drivers/vmwarevsphere/vsphere.go` ?

**Comment by mafrosis** [comment]
ping @pphetra :)

**Comment by shin-** [comment]
Amended and merged in #4194 

Thank you!

**Pull request closed without merging**
