### PR TITLE
virtualbox: virtualbox-hostonly-no-dhcp flag to avoid creation of the…

### PR DESCRIPTION
**Pull request by asiragusa**
… dhcp server

https://github.com/docker/machine/pull/3427

@nathanleclaire sorry for the long delay, here is the rebase of my PR

Signed-off-by: Alessandro Siragusa <alessandro.siragusa@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Just to clarify for me -- How will the machine get an IP if not using host only interface DHCP?

**Comment by asiragusa** [comment]
@nathanleclaire dnsmasq, here is a snippet from a provisioning script I have written:

```
local IP1=$(echo "$NETWORK_CIDR" | cut -d. -f 1)
local IP2=$(echo "$NETWORK_CIDR" | cut -d. -f 2)
local IP3=$(echo "$NETWORK_CIDR" | cut -d. -f 3)
    
cat << EOF | sudo tee /usr/local/etc/dnsmasq.conf 
dhcp-leasefile=/var/lib/dnsmasq.leases
bind-interfaces
expand-hosts
local=/$DOMAIN/
domain=$DOMAIN
dhcp-option=3

# Set this to the name of your VirtualBox host-only interface.
# dnsmasq will listen for DHCP and DNS requests on this interface as
# well as the loopback:
interface=$NET_NAME

# Enable the integrated DHCP server, you need
# to supply the range of addresses available for lease and optionally
# a lease time. If you have more than one network, you will need to
# repeat this for each network on which you want to supply DHCP
# service.
dhcp-range=$IP1.$IP2.$IP3.100,$IP1.$IP2.$IP3.253,240h

# This must be the address of you host on the $NET_NAME network
address=/host.vm/$IP1.$IP2.$IP3.1
EOF

sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist

sudo mkdir -p /etc/resolver
echo 'nameserver 127.0.0.1' | sudo tee /etc/resolver/vm
```

then I create the machine with

```
docker-machine create -d virtualbox --virtualbox-hostonly-no-dhcp --virtualbox-hostonly-cidr "$NETWORK_CIDR/24" --virtualbox-host-dns-resolver "$MACHINE_NAME"
```

then, as written in #3427 I am able to resolve default.vm and host.vm in both the vm and the host

**Comment by nathanleclaire** [comment]
Cool.  Thanks for the explanation.

Happy to merge if you will add this to the Virtualbox driver doc please

**Comment by asiragusa** [comment]
@nathanleclaire I updated the doc, let me know if it's ok for you.

**Comment by nathanleclaire** [comment]
LGTM

Thanks @asiragusa

**Pull request merged**
