### PR TITLE
Update default images to ubuntu 15.10

### PR DESCRIPTION
**Pull request by trecloux**
Updated the following drivers to use ubuntu 15.10 as default image:
* amazonec2 : tested on one region (eu-central-1)
* azure : tested the _classic_ image, not the image for Chinese regions
* exoscale : tested
* digital ocean : tested
* rackspace : tested
* google compute : tested

Non covered :  vCloud Air

Fix for #2361

### CODE REVIEW

**Comment by trecloux** [comment]
Please wait before merging, will add Google soon.

**Comment by dgageot** [comment]
@trecloux for google, you can use this image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1510-wily-v20151114`

**Comment by trecloux** [comment]
@dgageot I fixed the azure doc formating and added google cloud image update.

**Comment by nathanleclaire** [comment]
Nice work @trecloux !

I'll make an issue to bump the image on `exoscale`, which I believe is the only one remaining (maybe `openstack`?).

LGTM

**Comment by trecloux** [comment]
@nathanleclaire `exoscale` was included and tested.

For `openstack` there is no default image ID.

**Comment by nathanleclaire** [comment]
Ah OK great.  Thanks!

**Pull request merged**
