### PR TITLE
Add Linode driver

### PR DESCRIPTION
**Pull request by taoh**
Adds support of Linode to machine - a popular IaaS platform.

### CODE REVIEW

**Comment by taoh** [comment]
In commands.go I imported the driver as "github.com/taoh/machine/drivers/linode", which is a consequence of forking the original repository. This would need to be changed to github.com/taoh/docker/drivers/linode once the pull request is accepted. Is there a better way to do this on a forked repository?

**Comment by sthulb** [comment]
@taoh Yup, there's a better way, clone the repo into $GOPATH/src/github.com/docker/machine, then all the pkg paths will work.

**Comment by taoh** [comment]
@sthulb Thanks. Will do.

**Comment by taoh** [comment]
Close this pull request as I'm creating a new one following contribution guidelines.

**Pull request closed without merging**
