### PR TITLE
Another pass at linting

### PR DESCRIPTION
**Pull request by dmp42**

### CODE REVIEW

**Comment by dmp42** [comment]
ping @nathanleclaire @dgageot 

softlayer, openstack, amazonec2 are still excluded.

Everything seems safe, save a couple of properties on struct that I `json:`-ed to ensure backward compat.

Let me know what you think.

**Comment by dgageot** [comment]
@dmp42 woot! This one is huge. Since we had that recent problem with go templates, I'd rather take some time to review it.

**Comment by nathanleclaire** [comment]
@dgageot When you get a chance, which problem with Go templates are you referring to?

**Comment by dmp42** [comment]
@nathanleclaire I think @dgageot refers to https://github.com/docker/machine/pull/2202

**Comment by nathanleclaire** [comment]
Yep I saw that.  Thx

**Comment by dgageot** [comment]
Closing. Rebased with: #2241

**Pull request closed without merging**
