### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by brandoncc**

### CODE REVIEW

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
ping @ehazlett

**Comment by brandoncc** [comment]
@moxiegirl No problem, I think it is awesome that I am able to contribute even in a small way!

**Comment by brandoncc** [comment]
By the way I just found another one at:

https://docs.docker.com/reference/builder/

```
*/temp*
*/*/temp*
temp?
!LICENCSE.md
*.md
```

"LICENCSE" is misspelled, but I can't find it in the repo to commit a fix.

**Comment by thaJeztah** [comment]
@brandoncc that document is in the *docker* repository; the documentation is generated by combining the `/docs/` from all docker projects.

You can find that document here, but it looks like that typo is already fixed (but not yet published);

https://github.com/docker/docker/blob/master/docs/reference/builder.md

thanks for spotting that though!

**Comment by brandoncc** [comment]
Oh, thanks for clarifying that for me! I'm glad it is fixed already, if I find any more I will definitely create a PR :smile:

**Comment by thaJeztah** [comment]
Awesome! thanks for contributing!

**Comment by ehazlett** [comment]
Thanks!!! LGTM

**Pull request merged**
