### PR TITLE
Fix active host implementation for start, stop, etc.

### LINKED ISSUE #645: docker-machine stop not working
According to the documents:
>$ docker-machine stop
  $ docker-machine start
  If they aren't passed any arguments, commands such as docker-machine stop will run against the active host (in this case, the VirtualBox VM). You can also specify a host to run a command against as an argument. For instance, you could also have written:
  $ docker-machine stop dev
  $ docker-machine start dev

But I had tried several times, docker-machine stop doesn't work. only can stop dev machine with docker-machine stop dev.

Virutalbox: 4.3.22
docker-machine version 0.1.0
ocker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

I have boot2docker installed as well

### PR DESCRIPTION
**Pull request by nathanleclaire**
Fixes #645 

cc @sthulb @bfirsh @ehazlett 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by sthulb** [comment]
LGTM

**Comment by ehazlett** [comment]
LGTM

**Comment by ehazlett** [comment]
@nathanleclaire  In hindsight, should we add this to `getHosts` in case something else does not use `runWithContext`?

**Comment by nathanleclaire** [comment]
Hm, ultimately I want to mutate `runWithContext` into something that just takes a list of names instead (and eliminate passing the context everywhere), so I'm not really too worried about it.

**Comment by ehazlett** [comment]
ok

**Pull request merged**
