### PR TITLE
Fix building in docker

### PR DESCRIPTION
**Pull request by dmp42**
- now has default build target on `make`
- test depends on non-bogus target

### CODE REVIEW

**Comment by dmp42** [comment]
cc @jeanlaurent @dgageot @nathanleclaire

**Comment by nathanleclaire** [comment]
`go test` should already compile dependencies right?  Is `test` target doing other tests as well such as integration tests?  I thought those ensured that we compiled the binary first too.

**Comment by dmp42** [comment]
`test` is also a folder inside the repo, and make is confused by this, unless the target depends on another target to run. This is just to workaround make here.

**Comment by dmp42** [comment]
@nathanleclaire additionally the build now no longer tries to build _test files in cmd.

**Pull request merged**
