### PR TITLE
fixed issue-3145, enable engine-install-url in CentOS.

### PR DESCRIPTION
**Pull request by xinxian0458**
Signed-off-by: Jie Zhang <zhangjie0220@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Hi @xinxian0458 thanks for the pull request.  Looks pretty good, can you also take out the previously referenced `installOfficialDocker` method?  I think we don't need custom RPM handling anymore, `get.docker.com` seems to take care of that these days.

**Comment by nathanleclaire** [comment]
Excellent.

Can you please squash your commits into only one?  After that, I'm game to merge.  Thanks!

**Comment by dgageot** [comment]
Thanks @xinxian0458. Yes please squash your commits and get rid of the typo fixing part in this PR.

**Comment by xinxian0458** [comment]
Hi @nathanleclaire  and @dgageot , I'm sorry I don't know how to do that, can you please help me.

**Comment by dgageot** [comment]
Hey @xinxian0458, you did it! Thanks a lot!

LGTM

**Comment by nathanleclaire** [comment]
LGTM

Thanks @xinxian0458 !

**Pull request merged**
