### PR TITLE
FIX #2019 invalid env hints

### LINKED ISSUE #2019: docker-machine env --swarm wrong message?
I set up a swarm using docker machine with a virtualbox driver on my ubuntu 14.04 LTS.

docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://$TOKEN swarm_master

Then i added 2 more nodes... at the end i ask docker-machine to print the env to talk to the infrastructure with:

    root@ozzy-desktop:~# docker-machine env --swarm swarmmaster
    export DOCKER_TLS_VERIFY="1"
    export DOCKER_HOST="tcp://192.168.99.100:3376"
    export DOCKER_CERT_PATH="/home/ozzy/.docker/machine/machines/swarmmaster"
    export DOCKER_MACHINE_NAME="swarmmaster"
    # Run this command to configure your shell: 
    # eval "$(docker-machine env swarmmaster)"

In my opinion the last line is wrong, # eval "$(docker-machine env --swarm swarmmaster)" should be printed instead of 
    # eval "$(docker-machine env swarmmaster)"

I usually copy - paste and execute the last line so I end up talking to the swarm master virtual machine.

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
@dmp42 @nathanleclaire Can you please tal?

**Comment by dmp42** [comment]
LGTM

**Comment by dgageot** [comment]
This PR fixes #1289 too, fixes the hints printed for fish shell and adds tests.

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
FYI, we should think about moving over to using some kind of `UsageHintOptions` struct instead of passing five separate arguments to that function though.

**Pull request merged**
