### PR TITLE
Fixes for on-premise EC2 endpoints

### PR DESCRIPTION
**Pull request by MitchK**
This pull request relates to this issue: https://github.com/docker/machine/issues/653

**WIP**
 - [x] Allow to set a custom on-premise EC2 endpoint (currently added for testing internally)
 - [x] Add command line argument, replace the environment variable
 - [ ] Allow to trust self-signed certificates for on-premise EC2 endpoints
 - [ ] Add tests

### CODE REVIEW

**Comment by MitchK** [comment]
**Proposal**
Add two command line arguments:

 * ```--amazonec2-url=...``` - Covers protocol, host with region and port
 * ```--amazonec2-certificate=...``` - Allows to import a self-signed ```.pem``` certificate

Any comments?

**Comment by ehazlett** [comment]
I think we could add the args as I see this would be beneficial to ec2 compatible providers.  However, I think if we provide the `endpoint` arg we should allow the `EC2_URL` env var as well (as we do with other providers).

**Comment by MitchK** [comment]
Okay, you can now use ```--amazonec2-endpoint=https://xyz``` and also use the environment variable ```AWS_ENDPOINT```(instead of ```EC2_URL```).

Next thing to fix will be the certificate validation for self-signed certificates.

**Comment by ehazlett** [comment]
Any update on this?

**Comment by MitchK** [comment]
Yep, I'll try to add the certificate validation. ```--amazonec2-certificate=``` plus the environment variable will do it. Still my first steps with Go :)

**Comment by bgokden** [comment]
Are there any other development on this?

**Comment by MitchK** [comment]
Currently, I don't have too much time to dig into this. Closing for now. I also think that there are not many companies with on-premise AWS-like endpoints.

**Pull request closed without merging**
