### PR TITLE
Fixes issue #2342 - Issue provisioning swarm master with --replication through Docker Machine

### PR DESCRIPTION
**Pull request by drankinn**
added advertise flag to swarm manager template.
Uses the --swarm-addr parameter to set the advertise address for the manager
same as the swarm agent

### CODE REVIEW

**Comment by nathanleclaire** [comment]
LGTM

cc @docker/machine-maintainers 

@abronan @aluzzardi @vieux Any comment?

**Comment by abronan** [comment]
SGTM, `--replication` needs `--advertise` for the leader election mechanism.

**Comment by dgageot** [comment]
LGTM

**Comment by drankinn** [comment]
This is my first pull request in the docker community.   
Great experience
Thank you!

**Comment by nathanleclaire** [comment]
:+1: @drankinn

**Pull request merged**
