### PR TITLE
Document command-line completion installation

### PR DESCRIPTION
**Pull request by davidstosik**
This is a draft based on [the same doc for docker-compose](https://github.com/docker/compose/blob/master/docs/completion.md). It still needs changes, but will get the thing moving.

I updated and commented out the zsh doc, as docker-machine does not seem to have zsh completion scripts.

I'll need help on the available completions, as I merely created this file by copy-paste-update from docker-compose, after figuring out how to install completion for docker-machine on my system.

### CODE REVIEW

**Comment by jeanlaurent** [comment]
LGTM so we have a place to start adding completion in.

**Comment by dgageot** [comment]
@davidstosik Can you please rebase?

**Comment by davidstosik** [comment]
@dgageot Done. I think.

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
