### PR TITLE
Bare Metal Driver using OpenCrowbar API

### PR DESCRIPTION
**Pull request by zehicle**
This Machine driver provides all capabilities of a cloud driver except that it is giving out bare metal servers instead of VMs.  The driver is able to turn machines on and off plus SSH using per machine generated keys.  

It requires a running OpenCrowbar install (using the latest "Drill" code is required to get the SSH key insertion and pre-req roles).  The driver defaults will work against default OpenCrowbar and can be set using the Machine overrides.

I've provided additional details on http://robhirschfeld.com/2015/05/15/docker-machine-crowbar-driver-delivers-metal-containers/

### CODE REVIEW

**Comment by ehazlett** [comment]
Hi , thanks for your efforts and persistence in submitting this driver. We are extremely excited that there is so much interest in Docker Machine and we really appreciate your interest. However, at this time it is proving to be extremely difficult for us to keep up with reviewing and testing each of these drivers for inclusion in the Machine core. We really want to switch to a more pluggable model, as well as polish up a few things about the driver model which need to be changed to ensure a smooth and sustainable future.

Therefore, we will be moving to a plugin model for 0.5 and would love to have you involved in the design and development process. We are closing the outstanding driver PRs at this time, but please keep the code. We will stick closely to the current driver interface and you should be able to re-use a lot (if not all) of the existing driver along with the new plugin model. We will be moving all of the drivers which are merged directly into Machine today to the plugin model when it is available, so there will be no special treatment of those, and there will be documentation outlining the process of developing and using a Docker Machine driver plugin.

With all of that being said, we want to apologize for the lack of feedback on your pull request. As contributors ourselves, we understand that being left in limbo is no fun. We would have liked to address this sooner, and in the future we will be more responsive around these kinds of issues.

Once again, we thank you for the contribution and the tremendous support. Keep hacking strong!

If you want to contribute to the design of the plugin model, we'd love to get your input on this issue where we will be planning it:

https://github.com/docker/machine/issues/1626

@ehazlett & @nathanleclaire

**Comment by zehicle** [comment]
Thanks - that makes sense to me and I'm looking forward to moving to that
model.

On Fri, Jul 31, 2015 at 4:40 PM, Evan Hazlett <notifications@github.com>
wrote:

> Hi , thanks for your efforts and persistence in submitting this driver. We
> are extremely excited that there is so much interest in Docker Machine and
> we really appreciate your interest. However, at this time it is proving to
> be extremely difficult for us to keep up with reviewing and testing each of
> these drivers for inclusion in the Machine core. We really want to switch
> to a more pluggable model, as well as polish up a few things about the
> driver model which need to be changed to ensure a smooth and sustainable
> future.
>
> Therefore, we will be moving to a plugin model for 0.5 and would love to
> have you involved in the design and development process. We are closing the
> outstanding driver PRs at this time, but please keep the code. We will
> stick closely to the current driver interface and you should be able to
> re-use a lot (if not all) of the existing driver along with the new plugin
> model. We will be moving all of the drivers which are merged directly into
> Machine today to the plugin model when it is available, so there will be no
> special treatment of those, and there will be documentation outlining the
> process of developing and using a Docker Machine driver plugin.
>
> With all of that being said, we want to apologize for the lack of feedback
> on your pull request. As contributors ourselves, we understand that being
> left in limbo is no fun. We would have liked to address this sooner, and in
> the future we will be more responsive around these kinds of issues.
>
> Once again, we thank you for the contribution and the tremendous support.
> Keep hacking strong!
>
> If you want to contribute to the design of the plugin model, we'd love to
> get your input on this issue where we will be planning it:
>
> #1626 <https://github.com/docker/machine/issues/1626>
>
> @ehazlett <https://github.com/ehazlett> & @nathanleclaire
> <https://github.com/nathanleclaire>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/pull/1364#issuecomment-126818138>.
>



-- 
Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO/Founder (rob@rackn.com)

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: zehicle

**Comment by zehicle** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Rob

Confirm that you know Rob: https://www.linkedin.com/e/v2?e=0-im6cz9qq-27&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=6kmyYcQN&invitationId=6118771181932855296








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im6cz9qq-27&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGAeuMgUVi9EwAAAVOo-G1okDRupC2GiVSrbSKFYaGlKN7Mu4L6vZnL-BmEhOC2cETqkmoRvkvdLvYdGr0r1-GM9VhW5A2M3Nmynv7PPmiULEQu27ineV7v1r-rxTlLZjOHCM8sq3bYh9t15VrwaBDc-ow7ErwxHRmrnGvBGvwX5_CflcMiEgWbpSryMTnL-YR3&eid=0-im6cz9qq-27


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im6cz9qq-27&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-4grw7l-imfatvm3-34&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=6kmyYcQN&invitationID=6118771181932855296

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=-4grw7l-imfatvm3-34&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=6kmyYcQN&invitationID=6118771181932855296





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-4grw7l-imfatvm3-34&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-4grw7l-imfatvm3-34&loid=AQGWZrSIhtbcTQAAAVPJ-H-J357bi9j2Mvo0DLXnRiTgfc1PNMq4gMlV3zR9s44GJ2sE6_ul9yVCXBz5ZTAbMPRocIDXMIY3H2zKZIoSTtZqsiCFeVB8LZi0KHpp9SToAdQJa7YEeShEFYG9DugCZypGWyKzKOObsgAM_rVViJ0ixe0IPlex5KABxlK0PDgg0bD7

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-4grw7l-imfatvm3-34&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by nathanleclaire** [comment]
Hey @zehicle, not sure what's going on, but we seem to be getting a few errant notifications from your email on this thread.  You might want to look into fixing that.

**Comment by zehicle** [comment]
I'll see what I can do.

On Thu, Mar 31, 2016 at 12:51 PM Nathan LeClaire <notifications@github.com>
wrote:

> Hey @zehicle <https://github.com/zehicle>, not sure what's going on, but
> we seem to be getting a few errant notifications from your email on this
> thread. You might want to look into fixing that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/pull/1364#issuecomment-204050560>
>
-- 
Rob Hirschfeld
RackN.com, CEO & Founder
@zehicle, 512-773-7522

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-4grw7l-impb4u2p-ru&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=6kmyYcQN&invitationID=6118771181932855296

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=-4grw7l-impb4u2p-ru&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=6kmyYcQN&invitationID=6118771181932855296





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-4grw7l-impb4u2p-ru&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-4grw7l-impb4u2p-ru&loid=AQFD_xgB2I_OIAAAAVPuBMRnh3AorsI2nuHeEAtEXWHHmDFLp79D99nNt3zehDuhkKcQoBJ6rhbEQ8x_pCs-vrZEhMgEhXFLMa-yhnQnvwr4xf7mF13p-hFwNZ6-Xh9tCeo2MzJc5xDa0PeoY53jCfMnCM_WWqdTdDNa113ryx_WeNqlO2fUk19QXMg7ABjuxcYU

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-4grw7l-impb4u2p-ru&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
