### PR TITLE
Exclude all addresses from host-only interfaces

### PR DESCRIPTION
**Pull request by mjstevens777**
This PR addresses issue #3596 

It excludes all addresses from a host-only interface from being included in the list of host interfaces. The previous behavior was to exclude only addresses listed in excludeNets.

### CODE REVIEW

**Comment by mjstevens777** [comment]
The tests for this file are set up around network interfaces with a single address, which is not guaranteed by the go api. To test behavior with multiple interfaces, I would have to refactor the entire test file. Since I am not very familiar with go, I don't really think i should do this.

**Comment by nathanleclaire** [comment]
What issue does this fix?

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
Thanks!

**Pull request merged**
