### PR TITLE
Setting `DEBIAN_FRONTEND` to `noninteractive` in SoftLayer

### LINKED ISSUE #763: Softlayer sudo TTY issues
When provisioning machines with the Softlayer driver, I get the following output:

```
# docker-machine create -d softlayer --softlayer-user USER --softlayer-api-key APIKEY --softlayer-cpu 2 --softlayer-local-disk --softlayer-memory 4096 --softlayer-hostname swarm-slave-01 --softlayer-domain docker.domain.us --softlayer-region "tor01" --swarm --swarm-discovery token://b6d9b5bd9751414249b8a38f9222499c swarm-slave-01
INFO[0000] Creating SSH key...
INFO[0009] Getting Host IP
INFO[0027] Waiting for host to become available
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
INFO[0281] Configuring Swarm...
INFO[0290] "swarm-slave-01" has been created and is now the active machine.
INFO[0290] To point your Docker client at it, run this in your shell: $(docker-machine env swarm-slave-01)
```

This seems to be possibly an issue with sudo and needing to use DEBIAN_FRONTEND=noninteractive.

### PR DESCRIPTION
**Pull request by hairyhenderson**
Fixes #763

Signed-off-by: Dave Henderson <Dave.Henderson@ca.ibm.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
__EDIT__: Except I think that we actually don't want `-q` flag on `apt-get` command.  We want to see the output.  Can you please remove it?

**Comment by hairyhenderson** [comment]
@nathanleclaire - heh. I considered `-qq` originally, but figured it was nice to see non-error output for context, especially since it's only at debug level.

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
