### PR TITLE
Debian provisioner

### PR DESCRIPTION
**Pull request by chantra**
Add support to provision Debian hosts
Refactor the UbuntuProvisioner code into DebianFamilyProvisioner

### CODE REVIEW

**Comment by ehazlett** [comment]
Thanks for the contribution!  However, in this state this will not work.  Debian uses systemd for it's configuration and the docker install sets it up.  I have a working branch here https://github.com/ehazlett/machine/blob/debian-provisioner/libmachine/provision/debian.go

**Comment by ehazlett** [comment]
Just opened https://github.com/docker/machine/pull/1178 for feedback.

**Comment by chantra** [comment]
@ehazlett it does work on debian 7.8 (which is what I tested it on)

**Comment by chantra** [comment]
@ehazlett ok, I hacked together compatibility for Debian 7 and Debian 8.

I am a go n00b so feedback is more than welcome as I may have approach the solution from the wrong angle.

The end goal is to refactor as much as possible. Debian/Ubuntu should virtually use almost the same driver, only few changes should be required. Same goes to CentOS/RHEL...

The diff currently fail at passing: ./script/validate-dco I am sorting this out on my side.

**Comment by ehazlett** [comment]
Since Ubuntu differs quite a bit from Debian, I'm not sure why we need to deviate from just the Generic provisioner as in my #1178.  That only has the bits that are specific to Debian.  As for the older versions, I would say we only support the latest stable on each.  We don't go back for any other so I'm fine saying it's Debian jessie+.  It's just more code paths and issues to worry about with the various init config systems.

I would like to have a single PR for this.  I'm not saying mine is right -- I am just not sure we need the Debian "family" abstraction as they are quite different (see the diffs between the RedHat PRs -- ~30 lines of code for the others) and there are so many nuances between Ubuntu and Debian, to me they are their own provisioners, only sharing package systems.

Thoughts?

**Comment by chantra** [comment]
@ehazlett I seems there isa lot of code duplication overall. debian and ubuntu provisioner are pretty much the same but for some special cases (checking if sudo is installed, using systemd instead of upstart).
Maybe most of it should go into the generic provisioner though. Anyhow, there seem to be some common patterns that many distros fall into, those could be re-used across the codebase rather than be duplicated IMHO.

**Comment by ehazlett** [comment]
@chantra which duplication?  we could perhaps pull the stuff out of the `Provision` func but the ordering matters and we need to override certain things.  I will see if we can re-org the generic and reduce some of the duplication in both cases.

**Comment by ehazlett** [comment]
Thanks for the contribution! We have merged the Debian provisioner.  As such, closing this one.

**Pull request closed without merging**
