### PR TITLE
Amazon Ec2 - Add the option amazonec2-use-private-address

### LINKED ISSUE #1442: AWS with private addresses
I'm having a problem with docker machine creating non-public facing instances at AWS/EC2. If I add --amazonec2-private-addresses-only it doesn't add a public IP to the instance. However when there is no public IP present, the instance has no Internet access (this is normal for EC2 I think - no public Internet if you don't have a public IP).

What I really want is for docker-machine to spin up a VM with a public IP but connect to it through the private IP (since I have a VPN between my office and our VPC). Right now if I don't specify --amazonec2-private-address-only, docker-machine will default to connecting to it via the public IP.

It does create the instance and everything fine (I can ssh to it), but docker-machine says "Launching instance..." then hangs forever when I execute this command, and I assume that is because it trying to download docker to the Ubuntu AMI and not able to do so without public internet access:

    docker-machine create --driver amazonec2 --amazonec2-private-address-only=true --amazonec2-security-group=MySecurityGroup dtest002

Is what I'm looking for possible? I think it probably *would* work if I were to use docker-machine to create this VM without putting --amazonec2-private-address-only, then go in and modify my ~/.docker/machine/machines/dtest002/config file, change the IP from the public IP to the local IP, then maybe ssh into the dtest002 and change the docker config to bind only to the private IP. But that is some extra work. Any ideas?

### PR DESCRIPTION
**Pull request by rdgreis**
Fixes #1442

Adding the option --amazonec2-use-private-address to force the usage of private IP address instead of the public one. Specially useful at cases like described in #1442.

### CODE REVIEW

**Comment by robertjustjones** [comment]
Hey @rdgreis. To get the Travis check to pass, you'll need to use "commit -s" to add the "Signed-off-by" line on your commit messages. Just saw the same myself on my recent PR. Look there for an example. It only means that you wrote the code. See docker/docker contributing.md for more

**Comment by robertjustjones** [comment]
You'll also be asked the rebase to squash those commits... easy to do both at the same time.

**Comment by claudeatsafe** [comment]
@rdgreis any plans on merging this?

**Comment by ehazlett** [comment]
@rdgreis would you mind rebasing and making sure your commits are signed with the DCO (https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work).  Otherwise, I think this looks good.

/cc @nathanleclaire

**Comment by rdgreis** [comment]
Thanks @robertjustjones, my first time doing this sign/squash stuff.

@ehazlett rebased, I think it's ok now. :)

**Comment by claudeatsafe** [comment]
:+1: Thanks!

**Comment by ehazlett** [comment]
Closing as this was carried and merged in #1668.  Thanks!

**Pull request closed without merging**
