### PR TITLE
"rename" to rename the machine

### PR DESCRIPTION
**Pull request by waitingkuo**
To rename a machine, you can type

    machine rename OLDNAME NEWNAME

### CODE REVIEW

**Comment by ehazlett** [comment]
Coming back to this one.  I think we should also try to re-name the hostname of the machine since we match them on creation.  Thoughts?

/cc @sthulb

**Comment by sthulb** [comment]
Absolutely. It makes sense. I can take this PR. most of the work is done in my export/import branch.

**Comment by ehazlett** [comment]
@sthulb thx

**Comment by ehazlett** [comment]
This PR has gone stale.  Closing.

**Comment by johnraz** [comment]
I don't quite understand why this is closed? Did you just decide to not include the feature?

**Comment by xieyunzi** [comment]
Does anyone want to work on this?

**Comment by daghoidahl** [comment]
Is there any way to do it without this command currently?

**Comment by oleynikd** [comment]
How to rename a machine?

**Pull request closed without merging**
