### PR TITLE
OpenStack & Rackspace drivers

### PR DESCRIPTION
**Pull request by ggiamarchi**
Generic OpenStack driver and Rackspace specific driver based on the generic one.

##### To-do list :
- [x] Floating IP allocation and assignation
- [x] Allow user to provide names or id instead only id for
  - [x] Flavor
  - [x] Image
  - [x] Network
- [x] Call to `driver.AddPublicKeyToAuthorizedHosts()` is missing
- [x] Some `info` level should be at `debug` level or maybe not present at all
- [x] If tenant name and tenant id are both provided the driver should not fail
- [x] Reimplement docker installation and upgrade to target only ubuntu
- [x] Rackspace driver

### CODE REVIEW

**Comment by ggiamarchi** [comment]
@ehazlett I have updated docker to use 1.4.1 identity build like you did in the others drivers. Otherwise, fixes for the rackspace driver from @smashwilson have been merged.

**Comment by bfirsh** [comment]
@ggiamarchi @smashwilson Thanks for your great work on this.

A few things:

 - Could we set a default region? Or at least a better error... this is the error when no region is specified for rackspace:

```
FATA[0002] Discovered 4 matching endpoints: []tokens.Endpoint{tokens.Endpoint{TenantID:"942776", PublicURL:"https://iad.servers.api.rackspacecloud.com/v2/942776", InternalURL:"", AdminURL:"", Region:"IAD", VersionID:"2", VersionInfo:"https://iad.servers.api.rackspacecloud.com/v2", VersionList:"https://iad.servers.api.rackspacecloud.com/"}, tokens.Endpoint{TenantID:"942776", PublicURL:"https://hkg.servers.api.rackspacecloud.com/v2/942776", InternalURL:"", AdminURL:"", Region:"HKG", VersionID:"2", VersionInfo:"https://hkg.servers.api.rackspacecloud.com/v2", VersionList:"https://hkg.servers.api.rackspacecloud.com/"}, tokens.Endpoint{TenantID:"942776", PublicURL:"https://dfw.servers.api.rackspacecloud.com/v2/942776", InternalURL:"", AdminURL:"", Region:"DFW", VersionID:"2", VersionInfo:"https://dfw.servers.api.rackspacecloud.com/v2", VersionList:"https://dfw.servers.api.rackspacecloud.com/"}, tokens.Endpoint{TenantID:"942776", PublicURL:"https://syd.servers.api.rackspacecloud.com/v2/942776", InternalURL:"", AdminURL:"", Region:"SYD", VersionID:"2", VersionInfo:"https://syd.servers.api.rackspacecloud.com/v2", VersionList:"https://syd.servers.api.rackspacecloud.com/"}}
```

 - No output is displayed until a rackspace hosts has been created, so the command looks like it hung. Could we get a "Creating server..." log message or something?
 - Any chance the commits could be squashed a bit?

**Comment by bfirsh** [comment]
Also some debugging output is displayed when creating:

```
± % machine create -d rackspace rackspace                                                                          !371

+ [ https://get.docker.com/ = https://get.docker.com/ ]
+ sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
gpg: requesting key A88D21E9 from hkp server keyserver.ubuntu.com
gpg: key A88D21E9: public key "Docker Release Tool (releasedocker) <docker@dotcloud.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
+ sh -c echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list
+ sh -c sleep 3; apt-get update; apt-get install -y -q lxc-docker
+ sh -c docker version
INFO[0078] "rackspace" has been created and is now the active machine. To point Docker at this machine, run: export DOCKER_HOST=$(machine url) DOCKER_AUTH=identity
```

**Comment by rgbkrk** [comment]
@bfirsh If I can chime in here, the reason that @smashwilson probably didn't specify a region is for geographic liability. As an example, the Rackspace SDKs no longer support a default region in case someone is required to only have their data in Australia, Hong Kong, etc.

**Comment by ggiamarchi** [comment]
So, that means the parameter `--rackspace-region` should be mandatory i guess ? In that case we should just print a clear error message.

**Comment by smashwilson** [comment]
> @bfirsh If I can chime in here, the reason that @smashwilson probably didn't specify a region is for geographic liability. As an example, the Rackspace SDKs no longer support a default region in case someone is required to only have their data in Australia, Hong Kong, etc.

Yep yep, this is correct. (Thanks for stepping in, @rgbkrk, I was fighting off a bout of the flu.)

> So, that means the parameter --rackspace-region should be mandatory i guess ? In that case we should just print a clear error message.

Indeed. I'll get a PR to your PR today :smile:

**Comment by smashwilson** [comment]
@bfirsh: Okay, ggiamarchi/machine#5 and ggiamarchi/machine#6 submitted. Once those are in:

> Could we set a default region? Or at least a better error... this is the error when no region is specified for rackspace:

A missing region is now treated like the other mandatory parameters:

```
# OS_USERNAME and OS_API_KEY exported

ashl6947@MMN1F3FD58 ~/code/machine (better-region-error=) $ machine create --driver=rackspace regionless
FATA[0000] Region must be specified either using the environment variable OS_REGION_NAME or the CLI option --rackspace-region 
```

> No output is displayed until a rackspace hosts has been created, so the command looks like it hung. Could we get a "Creating server..." log message or something?

OpenStack server creation has an Info-level message:

```
ashl6947@MMN1F3FD58 ~/code/machine (creating-server=) $ machine create --driver=rackspace --rackspace-region="DFW" morelogs
INFO[0001] Creating server...                            Name=docker-host-6c81d6b9a12e860b24fe98130c1dcc10fe14bad77aadb61bf21faad59063ca89
INFO[0082] "morelogs" has been created and is now the active machine. To point Docker at this machine, run: export DOCKER_HOST=$(machine url) DOCKER_AUTH=identity 
```

> Also some debugging output is displayed when creating:

I've shunted that off to `/var/log/docker-install.log`. It's odd that it was appearing with debugging disabled anyway; the docker installation script must write output to stderr instead of stdout for some reason.

On a related note, I've also made it so that a failing docker installation won't prevent the host from being usable to `machine` as well. You can now use `machine ssh` or `machine rm` to correct the situation even if the install failed.

*Before:*

```
ashl6947@MMN1F3FD58 ~/code/machine ((8f3502d...) *) $ machine create --driver=rackspace --rackspace-region="DFW" before
INFO[0002] Creating server...                            Name=docker-host-b3ec793bca8e90496ea4c2aaf796b36b7c8a7d91c768facc3b3770e04e4f9d7c
dockery: unrecognized service
ERRO[0076] Docker installation failed                   
ERRO[0076] The driver assume your instance is running Ubuntu. If this is not the case, you should use the option --openstack-docker-install=false when creating the machine and then install manually 
FATA[0076] exit status 1                                
ashl6947@MMN1F3FD58 ~/code/machine ((8f3502d...) *) $ machine ls
NAME     ACTIVE   DRIVER      STATE   URL
before            rackspace           
ashl6947@MMN1F3FD58 ~/code/machine ((8f3502d...) *) $ machine rm before
INFO[0000] Deleting OpenStack instance...                MachineId=
ERRO[0000] Error removing machine before: Expected HTTP response code [204] when accessing URL(https://dfw.servers.api.rackspacecloud.com/v2/864477/servers/); got 404 instead with the following body:
404 Not Found

The resource could not be found.

    
FATA[0000] There was an error removing a machine. To force remove it, pass the -f option. Warning: this might leave it running on the provider. 
```

*After:*

```
ashl6947@MMN1F3FD58 ~/code/machine (creating-server *=) $ machine create --driver=rackspace --rackspace-region="DFW" betterfail
INFO[0001] Creating server...                            Name=docker-host-f5ed15c28ba15ecee340ffdceb3e5fdc70855ee70e9a82a569121d2c1e125b9c
ERRO[0045] The docker installation failed.              
ERRO[0045] The driver assumes that your instance is running Ubuntu. If this is not the case, you should use the option --openstack-docker-install=false (or --{provider}-docker-install=false) when creating a machine, and then install and configure docker manually. 
ERRO[0045] Also, you can use "machine ssh" to manually configure docker on this host. 
INFO[0045] "betterfail" has been created and is now the active machine. To point Docker at this machine, run: export DOCKER_HOST=$(machine url) DOCKER_AUTH=identity 
ashl6947@MMN1F3FD58 ~/code/machine (creating-server *=) $ machine ls
NAME         ACTIVE   DRIVER      STATE     URL
betterfail   *        rackspace   Running   tcp://23.253.110.90:2376
ashl6947@MMN1F3FD58 ~/code/machine (creating-server *=) $ machine ssh betterfail
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-37-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Thu Jan  1 00:00:10 1970
root@docker-host-f5ed15c28ba15ecee340ffdceb3e5fdc70855ee70e9a82a5691:~# exit
logout
ashl6947@MMN1F3FD58 ~/code/machine (creating-server *=) $ machine rm betterfail
INFO[0000] Deleting OpenStack instance...                MachineId=a62dd2cf-4209-4d02-8e99-c19cf0726509
INFO[0001] Deleting Key Pair...                          Name=docker-host-f5ed15c28ba15ecee340ffdceb3e5fdc70855ee70e9a82a569121d2c1e125b9c
```

**Comment by rgbkrk** [comment]
Looking great, I'm excited to use this!

**Comment by ehazlett** [comment]
LGTM

**Comment by ehazlett** [comment]
@ggiamarchi this is getting really close :)  Do you think you could squash some of the commits?

**Comment by ggiamarchi** [comment]
@ehazlett I have squashed commits when it was relevant and not annoying to read and understand the history. Finally, we came from 50 to 24 commits in the PR.

**Comment by ehazlett** [comment]
@ggiamarchi awesome - thanks!

**Comment by adrianotto** [comment]
@bfirsh and @ehazlett : Can you please take a moment to outline what needs to be done to overcome the merge conflict on this PR, and get it in? We are really interested in getting this merged. Please advise.

**Comment by rgbkrk** [comment]
It's a small merge conflict in the README, related to another PR landing before this one. Surprised it doesn't merge well. I did the rebase locally just fine. I'm guessing @ggiamarchi will be able to handle it just fine but I could make a PR to fix it up.

It would be nice if this was merged with the amount of functionality it has now. The Rackspace portion of this PR has existed as far back as https://github.com/bfirsh/docker/pull/10 and https://github.com/docker/machine/pull/18.

**Comment by ggiamarchi** [comment]
Rebased

**Comment by ehazlett** [comment]
@ggiamarchi could you do one more rebase?  there was a hostname update to set the name of the machine.  after this we should be good to merge.  thanks!

**Comment by ggiamarchi** [comment]
I have just rebased and made necessary changes to match the new `NewDriver` signature [9d91f45](https://github.com/ggiamarchi/machine/commit/9d91f458f5fe8c367ad741f9f6cfcc5830ab8dcc)

**Comment by ehazlett** [comment]
Thanks the work all!

**Comment by ggiamarchi** [comment]
Awesome ! :sunglasses:

**Comment by smashwilson** [comment]
:metal: It's great to see this. Thanks, everyone!

**Comment by rgbkrk** [comment]
:tada: Yay, thanks!

**Pull request merged**
