### PR TITLE
use yum repos for redhat like distros

### LINKED ISSUE #1527: switch to use repo for rpm
Refs https://github.com/docker/docker/pull/13680

### PR DESCRIPTION
**Pull request by ehazlett**
This uses the new Docker Yum repositories for the RedHat like distros in the provisioner (RHEL, Fedora, Centos).

Closes #1527

### CODE REVIEW

**Comment by nathanleclaire** [comment]
cc @bmangold this is relevant to your interests.

**Comment by nathanleclaire** [comment]
There's a merge conflict but code LGTM

**Comment by ehazlett** [comment]
Fixed.  Merging.

**Comment by thaJeztah** [comment]
Yay!

**Pull request merged**
