### PR TITLE
drivers/amazonec2: check if port is already opened in sg

### PR DESCRIPTION
**Pull request by andrestc**
The driver would try to open the ports provided in `--amazonec2-open-port` flag even if it was already present in the sg. This PR prevents this from happening.

Signed-off-by: André Carvalho <asantostc@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Thanks @andrestc -- Is there an issue filed for this the PR closes?

**Comment by andrestc** [comment]
Nope, I ran into this myself. Want me to create one?

**Comment by nathanleclaire** [comment]
Don't think it's needed just want to make sure we close one if it does exist!  Thanks

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
