### PR TITLE
fixed typos which were referencing the wrong example machines

### PR DESCRIPTION
**Pull request by londoncalling**
Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
This fixes issue #3257 reported by Kevin Carr <kevin@evolition.io> via @moxiegirl .

**Comment by londoncalling** [comment]
@moxiegirl can you review and let me know if it LGTYou and/or merge when build succeeds?

**Comment by moxiegirl** [comment]
Hey, I see your corrections.  I thought you weren't going to use "machine" in a generic sense? Catch me up when you have a chance.

**Comment by londoncalling** [comment]
Hi,
I was hoping first that the intro would clear up some of the confusion, and
the goal was to avoid using "machine" frequently in a generic sense.

On the other hand, I didn't want to totally avoid it in cases where that
would be forced and  awkward. I skimmed the examples where I fixed the
typos ... were you seeing inappropriate use of "machine" in those docs? Can
you show me where?

Thanks, Vicky

**Pull request merged**
