### PR TITLE
Decoupled RPC Types from API

### PR DESCRIPTION
**Pull request by allingeek**
Addresses #2325  

Signed-off-by: Jeff Nickoloff <jeff@allingeek.com>

	modified:   libmachine/drivers/plugin/register_driver.go
	modified:   libmachine/drivers/rpc/client_driver.go

### CODE REVIEW

**Comment by nathanleclaire** [comment]
NOT LGTM

Doesn't this change just reverses the problem?

```console
$ make machine && make install
cp /Users/nathanleclaire/go/src/github.com/docker/machine/bin/docker-machine /Users/nathanleclaire/go/src/github.com/docker/machine/bin/docker-machine-driver* /usr/local/bin
cp: /Users/nathanleclaire/go/src/github.com/docker/machine/bin/docker-machine-driver*: No such file or directory
make: *** [install] Error 1
$ docker-machine -v
docker-machine version 0.5.2-dev ( 296ff09 )
$ docker-machine ls
WARNING >>> Error attempting heartbeat call to plugin server: rpc: can't find service RpcServerDriver.Heartbeat
Error attempting to invoke binary for plugin 'virtualbox': rpc: can't find service RpcServerDriver.GetVersion
```

It fails for me because my local plugins have all registered `RPCServerDriver` (it's that way in master and in 0.5.1).

I do like the addition of the constants, though.  If it's possible, maybe we can register both names for backwards compatibility reasons, but I can't merge this in its current form.  Thanks @allingeek

**Comment by allingeek** [comment]
I'll update in a few hours.

**Comment by nathanleclaire** [comment]
Thanks man!

**Comment by dgageot** [comment]
Thank you @allingeek! Could you squash all your commits? Otherwise it looks pretty good and I'll have a test today.

**Comment by allingeek** [comment]
Merged.

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
