### PR TITLE
Update AVAILABLE_DRIVER_PLUGINS.md

### PR DESCRIPTION
**Pull request by yamamoto-febc**
Add maintainer e-mail for [docker-machine-sakuracloud](https://github.com/yamamoto-febc/docker-machine-sakuracloud).

Signed-off-by: Kazumichi Yamamoto <yamamoto.febc@gmail.com>

### CODE REVIEW

**Comment by dgageot** [comment]
ping @SvenDowideit Any idea why this is failing. I saw you were working in the documentation checks.

**Comment by yamamoto-febc** [comment]
rebased.

**Comment by dgageot** [comment]
LGTM

**Comment by jeanlaurent** [comment]
LGTM

**Pull request merged**
