### PR TITLE
Retry VirtualBox commands

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by jeanlaurent** [comment]
By reading the title, I guessed that you would add some sort of wait time and maximum retry, but there is none.

Are we sure that we aren't going to have an infinite loop ?

**Comment by dgageot** [comment]
No just a retry ;-) So, yes, the infinite loop can happen in theory but won't in real life. From my tests, the problem happens less than 1% of the time

**Comment by jeanlaurent** [comment]
LGTM

**Comment by nathanleclaire** [comment]
Can we please have a retry and break on error, even if it's only for a small amount?  I know the chances of an infinite loop seem small, but I think the awfulness of hitting an infinite loop is worth adding a few lines to prevent it.  After adding max retries, LGTM.

**Comment by nathanleclaire** [comment]
Also, we should consider sleeping for a small amount before each retry, otherwise we will hammer `VBoxManage` any time we try to request an action and the object is locked.

**Comment by nathanleclaire** [comment]
BTW, thanks for adding this.  It's very confusing to users when they get these kinds of messages.

**Comment by dgageot** [comment]
Two against one ;-) OK, I'll had a retry count and a small delay between retries.

**Comment by dgageot** [comment]
While I was at it, I added unit tests
@docker/machine-maintainers PTAL

**Comment by jeanlaurent** [comment]
:+1: for the retries

LGTM

**Pull request merged**
