### PR TITLE
minor updates to add Digital Ocean example heading and more links to …

### PR DESCRIPTION
**Pull request by londoncalling**
…driver plugin topics (fixing up to support docker/docker docs cloud install topic)

Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
@moxiegirl can you check this out?

**Comment by moxiegirl** [comment]
@londoncalling I really like your additions.  The introduction is much smoother, informative, and lively at the same time. 

If you have time to go further into this file and correct the older material in here:

* Some of the procedures could benefit from having actual steps rather than a mix of steps and narrative style.  This is in line with a lot of the findings of JMC (Nuremburg Funnel) -- people find step-wise easier to follow or to correct themselves against.

* The piece suffers from the royal `we` ---  second person `you` is more immediate and less distancing.  

* The future tense is used a lot in here.  There again most style guides ask for simple present unless otherwise important.  The thinking there is again a more immediate and less distancing tone.

**Comment by jeanlaurent** [comment]
LGTM

**Comment by dgageot** [comment]
LGTM

**Pull request merged**
