### PR TITLE
Add Scaleway driver

### PR DESCRIPTION
**Pull request by nlamirault**
This adds the code for a Scaleway [1] Cloud driver.
I update the Godeps.json file to add the go-scaleway [2] dependency.
Integration tests seems OK :

```bash
$ bats test/integration/driver-scaleway.bats 
 ✓ scaleway: machine should not exist
 ✓ scaleway: create
 ✓ scaleway: active
 ✓ scaleway: ls
 ✓ scaleway: run scaleway/busybox container
 ✓ scaleway: url
 ✓ scaleway: ip
 ✓ scaleway: ssh
 ✓ scaleway: docker commands with the socket should work
 ✓ scaleway: stop
 ✓ scaleway: machine should show stopped after stop
 ✓ scaleway: start
 ✓ scaleway: machine should show running after start
 ✓ scaleway: kill
 ✓ scaleway: machine should show stopped after kill
 ✓ scaleway: restart
 ✓ scaleway: machine should show running after restart
 ✓ scaleway: remove
 ✓ scaleway: machine should not exist
 ✓ scaleway: cleanup

20 tests, 0 failures
```

[1] : https://www.scaleway.com/
[2] : https://github.com/nlamirault/go-scaleway

### CODE REVIEW

**Comment by moul** [comment]
Subscribing to this topic.

I work at Scaleway and can help

**Comment by shouze** [comment]
:+1:

**Comment by Spy-Seth** [comment]
:+1:

**Comment by gmorel** [comment]
:+1:

**Comment by lfalorni** [comment]
:+1:

**Comment by dehy** [comment]
:+1:

**Comment by shouze** [comment]
This PR needs a rebase, but as [ScaleWay already supports Ubuntu Juju](https://blog.scaleway.com/2015/04/28/managing-your-scaleway-infrastructure-at-scale-with-juju/)... would be very cool to see a docker driver support!

**Comment by moul** [comment]
:+1:

**Comment by shouze** [comment]
Any chance to see it merged soon?

**Comment by ehazlett** [comment]
@shouze thanks for the contribution.  there is a process (https://github.com/docker/machine/blob/master/CONTRIBUTING.md#drivers) -- we will not get to this until after the 0.3 release.

**Comment by nlamirault** [comment]
See: https://github.com/docker/machine/pull/1389

**Pull request closed without merging**
