### PR TITLE
Simpler code for env usage hints.

### PR DESCRIPTION
**Pull request by dgageot**
We can just output the original os.Args in the
eval call.

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
@docker/machine-maintainers Can you take a look? Thanks!

**Comment by dmp42** [comment]
Simpler + Shorter -> Better!

@nathanleclaire wdyt?

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
Nice one :+1:

**Pull request merged**
