### PR TITLE
Add affinity group support in exoscale driver

### PR DESCRIPTION
**Pull request by runseb**
This improves the exoscale drivers and adds support for affinity groups.

Signed-off-by: Sebastien Goasguen <runseb@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Thanks @runseb -- looks pretty good, however we are in a code freeze window where we won't be merging anything new until after 0.8.0.  I intend to merge it after that (feel free to ping me if I am too laggard then).  Will you update the docs to include this as well please?  Thanks!

**Comment by runseb** [comment]
@nathanleclaire cool, 0.8.0 it is then. I just added the docs.
Not sure why the build is failing though, any hints would be nice.

**Comment by nathanleclaire** [comment]
@runseb it says:

```
drivers/exoscale/exoscale.go:269: client.CreateAffinityGroup undefined (type *egoscale.Client has no field or method CreateAffinityGroup)
drivers/exoscale/exoscale.go:285: client.GetAffinityGroups undefined (type *egoscale.Client has no field or method GetAffinityGroups)
drivers/exoscale/exoscale.go:352: topology.AffinityGroups undefined (type *egoscale.Topology has no field or method AffinityGroups)
drivers/exoscale/exoscale.go:389: unknown egoscale.MachineProfile field 'AffinityGroups' in struct literal
```

**Comment by cab105** [comment]
So I've found out that while the revision in Godeps.json has been updated to pull the correct version of the egoscale plugin, the appropriate files were not copied into place in the vendor directory.  I have rectified this in https://github.com/cab105/machine-1/tree/affinity.  Should this be treated as a new PR?

**Comment by nathanleclaire** [comment]
If the vendoring is off in this PR then it should be fixed in this PR.

**Comment by cab105** [comment]
I've been asked by @runseb to address the vendoring issue.  Would it make more sense to submit my fix and @runseb's in a new PR then?

**Comment by nathanleclaire** [comment]
@cab105 If you don't have access to the git remote this PR was originally submitted on, yes it would probably be easier.

**Comment by runseb** [comment]
closing this because this was taken care of in #3629

**Pull request closed without merging**
