### PR TITLE
Use Google default authentication

### PR DESCRIPTION
**Pull request by dgageot**
Because authentication is interactive in the google driver, it is broken by the new rpc plugin model.

Also users were complaining that there is no way to create machines non-interactively.

This PR introduce the usage of *Google Default Application Authentication* instead of an oauth interaction with the browser. It means that the experience is closer to what the users are used to with any
`gcloud` command.

### CODE REVIEW

**Comment by dgageot** [comment]
@jeffmendoza @nathanleclaire Can you take a look please?

**Comment by nathanleclaire** [comment]
Awesome.  Thanks for doing this.  Will take a look ASAP

**Comment by dgageot** [comment]
You might need to rebase on https://github.com/docker/machine/pull/2088

**Comment by nathanleclaire** [comment]
Merged #2088

**Comment by jeffmendoza** [comment]
I'm not getting the cli args to go through:
```bash
$ docker-machine create --help --driver google
Usage: docker-machine create [OPTIONS] [arg...]

Create a machine.

Specify a driver with --driver to include the create flags for that driver in the help text.

Options:
   
   --driver, -d "none"											Driver to create machine with.
   --engine-install-url "https://get.docker.com"							Custom URL to use for engine installation [$MACHINE_DOCKER_INSTALL_URL]
...
```
```bash
$ docker-machine create --driver google --google-project my-proj gce
Error setting machine configuration from flags provided: Please specify the Google Cloud Project name using the option --google-project.
```

**Comment by nathanleclaire** [comment]
@jeffmendoza Do you have the `docker-machine-driver-google` plugin binary installed (i.e. in `PATH`)?

**Comment by nathanleclaire** [comment]
Update: In the code there's a block like 

```
    if d.Project == "" {
        return fmt.Errorf("Please specify the Google Cloud Project name using the option --google-project.")
    }
```

but `d.Project` never gets set.  @dgageot what's the intended usage with this PR?

**Comment by dgageot** [comment]
That has to be a rebase fumble!
Le lun. 26 oct. 2015 à 23:02, Nathan LeClaire <notifications@github.com> a
écrit :

**Comment by nathanleclaire** [comment]
OK -- please make sure to fix and CC -- likewise please post some usage instructions.

**Comment by dgageot** [comment]
I can't fix that tonight. Will check tomorrow. Sorry...

**Comment by dgageot** [comment]
@nathanleclaire It should work now. /cc @jeffmendoza 
To make it work, it needs `gcloud` to be installed.
```
gcloud auth login
docker-machine create --driver google --google-project my-proj gce1
docker-machine create --driver google --google-project my-proj gce2
```

**Comment by ehazlett** [comment]
@dgageot nice work!  just tested and this works perfect.  

lgtm

**Comment by dgageot** [comment]
@docker/machine-maintainers ptal

**Comment by nathanleclaire** [comment]
Hey @dgageot .  I am trying to test it but can't figure it out.  I have created a Google Cloud project named "baguette" and enabled the "VM Instances" sub-section.  I have also run `gcloud auth login`.  It tells me `baguette` is my default project.

But:

```console
$ docker-machine create -d google --google-project baguette baggy
Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: You might have to run `gcloud auth login` to get the authorization credentials: googleapi: Error 400: Invalid value for project: baguette, invalid
```

Any ideas what's wrong?  I've run `gcloud auth login` many times.

**Comment by dgageot** [comment]
Google always use project name when it should really be project id.
Baguette is not the project name
Le mer. 28 oct. 2015 à 00:22, Nathan LeClaire <notifications@github.com> a
écrit :

**Comment by nathanleclaire** [comment]
I still get issue using `baguette-1111` which seems to be the project ID?

```console
$ docker-machine --debug create -d google --google-project baguette-1111 baggy
Docker Machine Version: 0.5.0-rc3 (361b123)
Launching plugin server for driver google
Found binary path at /usr/local/bin/docker-machine-driver-google
Plugin server listening at address 127.0.0.1:65128
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(baguette-1111) Calling RpcServerDriver.GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(baguette-1111) Calling RpcServerDriver.Close
Successfully made call to close driver server
Launching plugin server for driver google
Found binary path at /usr/local/bin/docker-machine-driver-google
Plugin server listening at address 127.0.0.1:65132
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(baggy) Calling RpcServerDriver.GetMachineName
(baggy) Calling RpcServerDriver.DriverName
(baggy) Calling RpcServerDriver.GetCreateFlags
(baggy) Calling RpcServerDriver.SetConfigFromFlags
Running pre-create checks...
(baggy) Calling RpcServerDriver.PreCreateCheck
(baggy) Calling RpcServerDriver.GetConfigRaw
(baggy) Calling RpcServerDriver.GetConfigRaw
Creating machine...
(baggy) Calling RpcServerDriver.Create
(baggy) OUT | Creating host...
(baggy) OUT | Generating SSH Key
(baggy) OUT | Creating instance.
(baggy) OUT | Creating firewall rule.
Error creating machine: Error in driver during machine creation: You might have to run `gcloud auth login` to get the authorization credentials: googleapi: Error 404: The resource 'projects/baguette-1111' was not found, notFound
```

**Comment by dgageot** [comment]
The error message changed. But I have no idea. I'll try with a brand new
project tomorrow
Le mer. 28 oct. 2015 à 01:33, Nathan LeClaire <notifications@github.com> a
écrit :

**Comment by nathanleclaire** [comment]
Thanks @dgageot

**Comment by dgageot** [comment]
@nathanleclaire It works with my brand new `cupcake-1112` project.

**Comment by dgageot** [comment]
@nathanleclaire I added a precheck for the project. This could give better feedback if the project is not found (for real of because of not using the project id) or when credentials are not valid.

I also updated the doc s/project name/project id/

Can you test again?

**Comment by nathanleclaire** [comment]
Sure thing

**Comment by nathanleclaire** [comment]
OK, my issue seems pretty clearly to be PEBKAC (mixing up my Google accounts).

Tried it and successfully created several instances.

Please rebase and squash, then: LGTM!

**Comment by dgageot** [comment]
@nathanleclaire squashed! Thanks for your time.

**Comment by nathanleclaire** [comment]
LGTM :+1:

**Pull request merged**
