### PR TITLE
New driver: Aliyun ECS

### PR DESCRIPTION
**Pull request by denverdino**
This PR includes the driver for [Aliyun Elastic Compute Service](http://www.aliyun.com/product/ecs/)
The Godeps is updated with the the [aliyungo](https://github.com/denverdino/aliyungo) dependency.

```
export DEBUG=true
export ECS_ACCESS_KEY_ID=<your_access_key_id>
export ECS_ACCESS_KEY_SECRET=<your_access_key_secret>
export ECS_REGION=cn-beijing
export ECS_SSH_PASSWORD=just4test
export MACHINE_DOCKER_INSTALL_URL=http://docker-mirror.oss-cn-hangzhou.aliyuncs.com/
# Optional for testing with VPC
export ECS_VPC_ID=<your_vpc_id>
export ECS_VSWITCH_ID=<your_vswitchid>

./machine create --driver aliyunecs test
```

I also wrote a tutorial for [Setup Docker Swarm Cluster on ECS with Docker Machine](https://github.com/denverdino/aliyungo/wiki/Docker-Swarm-on-Aliyun) in Chinese

If the integration testing need the test account for Aliyun ECS, please feel free to contact me. 

Thanks a lot

Signed-off-by: Li Yi &lt;denverdino@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Hi @denverdino -- This is not ported to the new plugin architecture per se, please see https://github.com/docker/machine/pull/1902 for the latest on that.  The new plugin model will allow anyone to distribute a Docker Machine driver plugin without needing to merge changes into upstream Docker Machine.  Please take a look at the progress in the PR I've mentioned and let us know your feedback.  Thanks!

- N

**Comment by denverdino** [comment]
Thanks, I will wait #1902 be merged

**Comment by nathanleclaire** [comment]
:+1:

**Comment by denverdino** [comment]
@nathanleclaire I have migrate the Aliyun ECS driver to the latest plugin architecture. And it works well.

[https://github.com/denverdino/machine](https://github.com/denverdino/machine)

Will we accept the PR for new plugin? 

For Aliyun is the largest cloud provider in China, this driver will be very helpful for developers  to use Docker technology in China. And we have be using the ECS driver for Docker Machine heavily in our internal projects for several months. It is pretty stable now. I and my colleagues can maintain this driver in coming years.

Thanks

**Comment by yanchanghai** [comment]
cool!

**Comment by nathanleclaire** [comment]
@danverdino We will not merge the `aliyun` plugin into the Docker Machine core -- instead you will be able to distribute it as a separate binary which works as long as the user has the plugin "installed".

**Pull request closed without merging**
