### PR TITLE
Remove @nathanleclaire as maintainer

### PR DESCRIPTION
**Pull request by nathanleclaire**
Sad to say this day has come! But, as always, change is the only constant of life.

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
cc @shin- @FrenchBen

**Comment by hairyhenderson** [comment]
😮

**Comment by SvenDowideit** [comment]
Boooo. Not lgtm.

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FrenchBen** [comment]
@nathanleclaire do you not wish to remain an external maintainer? :P

**Comment by nathanleclaire** [comment]
Nah, I can't keep up with all my side projects as-is!

LGTM

**Comment by shin-** [comment]
:wave:

**Pull request merged**
