### PR TITLE
Remove systemd-related driver duplication

### PR DESCRIPTION
**Pull request by nathanleclaire**
Good catch by @dgageot, I had forgotten to initialize the new instances of `GenericSSHCommander` where needed.

Everything should work swimmingly now.  Tested with GCE and it looks good on my end.

cc @docker/machine-maintainers 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
@SvenDowideit I see an issue with the documentation CI.  Not sure what's causing the failure.

**Comment by nathanleclaire** [comment]
cc also @londoncaling @moxiegirl in case you all might now what's up with the Jenkins docs CI thing.

**Comment by moxiegirl** [comment]
@nathanleclaire @SvenDowideit is now implementing the documentation validation we've been using on our test repo out into the world.  This PR has no `.md` files so it should not have triggered the documentation build.

At the moment, only Sven has the means to stop this error. He's been pinged.

**Comment by nathanleclaire** [comment]
Thanks @moxiegirl

**Comment by SvenDowideit** [comment]
ouch. so the problem is that this PR isn't rebased to master, and Jenkins isn't telling the job the branch point that is valid - so in this PR's case, the `git diff upstream/master..fc098` so it picked up the docs PR you merged for me as a change.

**Comment by SvenDowideit** [comment]
and resolved in https://jenkins.dockerproject.org/job/docs-machine-pr/32/console \o/ thank you for finding such a nice example of the problem - i'd hacked around it yesterday.

**Comment by nathanleclaire** [comment]
@SvenDowideit :+1:

**Comment by dgageot** [comment]
LGTM

**Pull request merged**
