### PR TITLE
Move `goauth2/oauth` dependency to `golang.org/x/oauth2`

### PR DESCRIPTION
**Pull request by dgageot**
This is to get rid of a deprecated package.

I had to migrate the digitalocean driver.

### CODE REVIEW

**Comment by dgageot** [comment]
ping @docker/machine-maintainers 

Managed to create/ssh into a digital ocean machine but you might want to check.

**Comment by dmp42** [comment]
@dgageot can we merge my godeps PRs first?

**Comment by dgageot** [comment]
@dmp42 yes. I merged your PR. Can you check this one?

**Comment by dmp42** [comment]
LGTM

**Comment by nathanleclaire** [comment]
Did you run the integration tests with `digitalocean` to ensure that everything works the same?

**Pull request merged**
