### PR TITLE
Fix: Error creating machine - Could not get lock /var/lib/apt/lists/lock - open

### PR DESCRIPTION
**Pull request by janeczku**
Creating the machine fails when the OS installation has not finished yet (dpkg or apt-get package managers are running) while the ubuntu provisioner tries to install software himself.
   
```
ERRO[0183] Error creating machine: error installing docker: exit status 100
bash: line 0: type: docker: not found
+ [ https://get.docker.com/ = https://get.docker.com/ ]
+ sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
...
+ sh -c echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list
+ sh -c sleep 3; apt-get update; apt-get install -y -q lxc-docker
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
E: Unable to locate package lxc-docker
WARN[0183] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0183] Error creating machine
```
  
Signed-off-by: Jan Broer <janeczku@yahoo.de>

### CODE REVIEW

**Comment by ehazlett** [comment]
@janeczku is this for the case where the system is running updates or something?

**Comment by janeczku** [comment]
@ehazlett yes, updates or any software installation that might still going on on the server after SSHd has launched. Could be the OS installation or some cloud provisioning going on (cloud-init,chef,etc...). At the moment this is not handled and will break the "machine create" as shown in the console log above.

**Comment by nathanleclaire** [comment]
Interesting... @janeczku could you explain a little bit more what the exact situation where you ran into this error was (what provider, machine create command, machine image, etc.)?

If we're going to implement this, there should be a `WaitForPackageManager` (or similar) that _all_ provisioners have to implement.

**Comment by janeczku** [comment]
@nathanleclaire, this error occurred on Google Compute Engine and Vultr (proposed driver) while provisioning Ubuntu 14.04 instances.
> docker-machine create -d google --google-project PROJECT_ID gce-test-instance  
    
> docker-machine create -d vultr --vultr-api-key API_KEY vultr-test-instance  
   
I use GCE with [project-wide metadata](https://cloud.google.com/compute/docs/metadata#project_and_instance_metadata), so that on first boot of each new instance a startup-script will run apt-upgrade to apply security updates and install the Newrelic agent for monitoring purposes.
Vultr on the other hand provisions its virtual machines from the OS installer (not from images). This means while the SSH daemon might already be running there is still some package manager stuff going on when docker-machine does the provision routine.

**Comment by dmp42** [comment]
@janeczku would you still be willing to carry this through?
Right now, it needs a rebase, then a review.

**Comment by janeczku** [comment]
@dmp42 sure just let me check first if this is still needed considering that the code has changed quite a bit since this PR was created.

**Comment by jeanlaurent** [comment]
Didn't see any recent issue on this error. But this is an edge case.

Should we close this or @janeczku can carry out the rebase ?

**Comment by jeanlaurent** [comment]
Closing, feel free to re-open.

**Comment by janeczku** [comment]
@jeanlaurent yep!

**Comment by mykter** [comment]
I just hit this provisioning an ubuntu 16.04 image on digitalocean:

```
$ ./docker-machine --version
docker-machine version 0.7.0, build a650a40

$ ./docker-machine create --driver digitalocean --digitalocean-access-token=<token> --digitalocean-image ubuntu-16-04-x64
<snip>
Provisioning with ubuntu(systemd)...
Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : sudo apt-get update
err     : exit status 100
output  : Reading package lists...
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
```

**Comment by ntfrnzn** [comment]
Same case as @mykter just now. Will look about for a workaround.

**Pull request closed without merging**
