### PR TITLE
Boot2Docker migration docs

### PR DESCRIPTION
**Pull request by ehazlett**
This is to get the Boot2Docker docs reviewed and approved.  The initial docs were merged as part of #979.  Please review `b2d_migration.md` and comment where we need to update.

Thanks!

/cc @SvenDowideit @fredlf

### CODE REVIEW

**Comment by hairyhenderson** [comment]
Just want to note that until this is merged, `master` is busted for anyone who develops on OS X right now, because of the duplicate-in-case-insensitive-filesystems addition that happened in d881aa8...

Or, maybe a rename of `docs/BOOT2DOCKER_MIGRATION.md` could get merged independently soon?

**Comment by nathanleclaire** [comment]
LGTM - as a side note, why not wrap to 80 characters?

**Comment by ehazlett** [comment]
@nathanleclaire probably because i used a Gist instead and I don't use much Python anymore ;)

I will update -- looks better in Vim ;)

**Comment by ehazlett** [comment]
Merging for now to fix the duplicate name issue.  I will reformat and submit a new PR.

**Comment by hairyhenderson** [comment]
thank you :)

**Comment by ehazlett** [comment]
:+1: yw

**Comment by nathanleclaire** [comment]
:+1:

**Pull request merged**
