### PR TITLE
Allow insecure connections in the Openstack driver.

### LINKED ISSUE #549: x509 and openstack
trying to run `machine-create` with `openstack` driver but keep getting this: 

```bash
ERRO[0000] Error creating machine: Get https://horizon.corp.foo.com/: x509: certificate signed by unknown authority
```

### PR DESCRIPTION
**Pull request by smashwilson**
Update Gophercloud to the latest `master` and take advantage of the configurable `http.Client` to permit insecure TLS connections in the OpenStack driver (at your own risk, of course).

Fixes #549.

/cc @ggiamarchi

### CODE REVIEW

**Comment by smashwilson** [comment]
This is a small fix - the remaining work is just testing and making sure that the Godeps changes are valid.

**Comment by ggiamarchi** [comment]
I'll take time to test it tomorrow.

**Comment by smashwilson** [comment]
@ggiamarchi Excellent, thanks! I was just going to request help here - I don't have a live devstack server any more, and I'm not sure how to set one up to serve over SSL if I did.

**Comment by smashwilson** [comment]
Squashed and rebased.

**Comment by smashwilson** [comment]
> So Rackspace CDN really can't be added to this page until the SDK work is done. Looking at Cloud Identity in the right hand pane (only api ref and dev guide), I was thinking I could do that for Rackspace CDN. And the SDK quick starts could be added later.
>
> So Ash, I guess we close the PR again and wait until 3/25.

:bow: Aye aye!

**Comment by smashwilson** [comment]
Oops. Wrong window.

**Comment by ggiamarchi** [comment]
LGTM

**Comment by smashwilson** [comment]
Excellent. Rebased on master deal with those conflicts.

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
