### PR TITLE
Add more command tests

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
ping @docker/machine-maintainers

**Comment by jeanlaurent** [comment]
LGTM

**Comment by jeanlaurent** [comment]
ping @docker/machine-maintainers

**Comment by nathanleclaire** [comment]
LGTM

There's already a `FakeAPI` in `libmachinetest` so I'll submit a quick follow up to use that instead (I know that may seem nitpicky but we've had serious code duplication issues in the past).

**Comment by dgageot** [comment]
@nathanleclaire Good, I couldn't find it. I'm all for getting rid of duplication

**Pull request merged**
