### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dmp42**
@dgageot this is the last part of #2160 

Just look at the Godeps file itself, not the rest obviously.

A chunk of them are certainly safe to update.
The drivers specific one could possibly be left alone for now (except digital ocean, and maybe google).

Ultimately, the golang philosophy should apply for most.

No emergency here - let's discuss this.

### CODE REVIEW

**Comment by dmp42** [comment]
I left the Azure stuff alone, because their repo doesn't cope well with `go get` :-) (poke @ahmetalpbalkan )

poke

**Comment by ahmetalpbalkan** [comment]
Hehe. Leave the azure stuff alone!!1  because our APIs are completely changed and I'll do a rewrite of the plugin :soon:.

**Comment by dmp42** [comment]
download

**Comment by dmp42** [comment]
@ahmetalpbalkan btw you know we are considering "outsourcing" plugins - and going to keep only a core set of important plugins in the main tree (pretty much like the registry).

We would be happy to keep azure, on the same terms and conditions we do in the registry :evil-grin:

**Comment by dmp42** [comment]
download 1

**Comment by dgageot** [comment]
@dmp42 build is failing. Can you take a look?

**Comment by dmp42** [comment]
@dgageot copying our chat here: both digital ocean and google drivers would have to be updated, if we decided to update their dependencies as well.

**Comment by dmp42** [comment]
@dgageot take it from here if you want to carry this through (I commited my (untested!) changes to digitalocean as well.

**Comment by dgageot** [comment]
Thanks @dmp42 I'm going to take a look at it

**Comment by dgageot** [comment]
@dmp42 This is a nightmare. More drivers are broken. Do we really want to update them all?

**Comment by dmp42** [comment]
@dgageot this is certainly not mandatory right now.
Can you do a smaller PR, without updating godo, compute nor rackspace?

**Comment by dgageot** [comment]
@dmp42 [here](https://github.com/docker/machine/pull/2391) I updated the dependencies for the google driver

**Comment by dgageot** [comment]
@dmp42 And the latest non-driver-related ones https://github.com/docker/machine/pull/2399

**Comment by dgageot** [comment]
Closing. What remains to be updated is rackspace related.

**Pull request closed without merging**
