### PR TITLE
wip: standardize install and configuration of docker

### PR DESCRIPTION
**Pull request by ehazlett**
This makes the default OS Ubuntu 14.04 amd64 and uses a "standard" method of installing and configuring Docker.  This will handle installing Docker as well as setting the default options to be unified across providers.  It also makes for an easier upgrade path as drivers simply need to call `InstallDocker`.

Drivers implemented and testing:

- [x] Amazon EC2
- [x] DigitalOcean
- [x] Azure
- [ ] Google
- [ ] vCloud Air
- [ ] Softlayer
- [ ] Rackspace

### CODE REVIEW

**Comment by ehazlett** [comment]
\o/ DO has fixed the issue with cloud init.  This is getting close as well :)

**Comment by thaJeztah** [comment]
Great news! And thanks to DO for fixing it

**Comment by bfirsh** [comment]
Great news!

**Comment by nathanleclaire** [comment]
:clap:

**Comment by ehazlett** [comment]
This will need a significant rebase and we are moving things around in new PRs.  This has stagnated.  Closing.

**Pull request closed without merging**
