### PR TITLE
Oracle Enterprise Linux provisioner

### PR DESCRIPTION
**Pull request by ezarko**
I am not a go developer and do not have the ability to recompile docker-machine and test this, but this should suffice for issue #1361 .  Can someone verify and get this in a future release?

### CODE REVIEW

**Comment by ezarko** [comment]
Fixed issues, updated commit message (signed and conformed to contributor guidelines) and squashed commits.  Now passes all checks!

**Comment by nathanleclaire** [comment]
So you haven't compiled and tested this yourself to verify that it's working?

**Comment by nathanleclaire** [comment]
If you have a local Docker installation working, you can compile the program with:

```
$ USE_CONTAINER=true make build-x
```

**Comment by ezarko** [comment]
```
$ bin/docker-machine-Windows-x86_64.exe create --driver generic --engine-env HTTP_PROXY=$HTTP_PROXY --engine-env HTTPS_PROXY=$HTTPS_PROXY --generic-ip-address 192.168.99.7 --generic-ssh-user holuser ol7
Running pre-create checks...
Creating machine...
(ol7) No SSH key specified. Connecting to this machine now and in the future will require the ssh agent to contain the appropriate key.
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ol...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: [sic: path removed]\bin\docker-machine-Windows-x86_64.exe env ol7
```

**Comment by ezarko** [comment]
Thanks for showing me USE_CONTAINER @nathanleclaire.  I had to make one final small change (due to being behind a corporate firewall and needing to pass in environment settings during yum update) and I can confirm that this works for me locally.

**Comment by ezarko** [comment]
PS- it might be worthwhile to use majorVersionRE in libmachine/provision/redhat.go->generateYumRepoList to select centos/6 or fedora/{20,21,23} instead of hardcoding to always use centos/7 and fedora/22 regardless of actual detected OS version.  I did this in the oraclelinux case.

**Comment by nathanleclaire** [comment]
> PS- it might be worthwhile to use majorVersionRE in libmachine/provision/redhat.go->generateYumRepoList to select centos/6 or fedora/{20,21,23} instead of hardcoding to always use centos/7 and fedora/22 regardless of actual detected OS version. I did this in the oraclelinux case.

Yeah, might be worth opening a new issue for that.

LGTM

**Pull request merged**
