### PR TITLE
FIX : Openstack driver do not remove keypair by default

### PR DESCRIPTION
**Pull request by bruno-morel**
#3261  - proposed solution: flag to activate key removal only if asked

### CODE REVIEW

**Comment by jrandall** [comment]
This seems like a reasonable solution to a massive problem with the docker-machine openstack driver - what is holding up getting this merged?

**Comment by nathanleclaire** [comment]
Why have a flag to indicate not to delete the keypair? This is the desired behavior in the case of a machine which creates a key as part of the creation process, so shouldn't it check that `openstack-keypair-name` is `""` before deleting instead?

**Comment by bruno-morel** [comment]
I'm not a big fan of non-explicit, magic behaviour, but if you think it's more on par with other driver's behaviour, I'll amend the commit to reflect this. Just let me know.

**Comment by bruno-morel** [comment]
@nathanleclaire any feedback ? want me to change the logic ?
I'd really like to push that fix forward... :)

**Comment by davidarcher** [comment]
I ran into this recently when using docker-machine against openstack the first time. For my use case, I'm actually fine with autogenerated keys but it was definitely surprising as a user when docker-machine deleted the keypair that i manually uploaded and was going to share between my launched instances.

+1 for just changing the logic so we only delete the key if it was autocreated by docker-machine.

**Comment by davidarcher** [comment]
Since this PR hasn't moved forward, I've opened up one of my one that uses the same logic as the EC2 driver. See https://github.com/docker/machine/pull/4358

**Comment by davidarcher** [comment]
This PR can be closed now that #4358 has gone in. It's finally fixed! 👍

**Comment by bruno-morel** [comment]
good job David :-)

**Pull request closed without merging**
