### PR TITLE
Add --github-api-token flag and troubleshooting section

### PR DESCRIPTION
**Pull request by nathanleclaire**
Closes https://github.com/docker/machine/issues/1483

Adds troubleshooting section to README

cc @ehazlett @dmp42 @moxiegirl 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
also cc @tianon

**Comment by tianon** [comment]
All seems pretty sane to me. :+1:

**Comment by sjackman** [comment]
The `--github-api-token` option worked for me. Thanks for this. Support for a `GITHUB_API_TOKEN` environment variable would be helpful.

**Comment by nathanleclaire** [comment]
@sjackman There is one `MACHINE_GITHUB_API_TOKEN`

```
  --github-api-token 						Token to use for requests to the Github API [$MACHINE_GITHUB_API_TOKEN]
```

**Comment by sjackman** [comment]
Great! Thanks. Perhaps this info could be added to the warning message `You may be getting rate limited by Github`.

**Pull request merged**
