### PR TITLE
Add appveyor.yml for native windows tests

### PR DESCRIPTION
**Pull request by StefanScherer**
For #2821 I started a test at AppVeyor. Here is the `appveyor.yml`. Feel free to tweak it for an official CI build + test.

An example can be found here: https://ci.appveyor.com/project/hypriot/machine/build/9

### CODE REVIEW

**Comment by dgageot** [comment]
Hi @StefanScherer Something strange happened with the circleci. Can you amend your commit to change the commit date and force push so that a new build is triggered?

**Comment by StefanScherer** [comment]
@dgageot I just restarted the CircleCI build. Hope that's enough.

**Comment by StefanScherer** [comment]
Rebuild failed, so I rebased the PR.

**Comment by StefanScherer** [comment]
Strange, the link to the details for the circleci build opens a circleci build at hypriot/docker and not docker/docker.

**Comment by StefanScherer** [comment]
OK, got it. CircleCI has mixed up the link. Now it is "yours" again. Another user of our team has watched the forked repo at CircleCI.

**Comment by dgageot** [comment]
LGTM

**Comment by dgageot** [comment]
ping @nathanleclaire @dmp42

**Comment by dmp42** [comment]
LGTM

**Pull request merged**
