### PR TITLE
Add bash completion for `docker-machine provision`

### PR DESCRIPTION
**Pull request by albers**
I'm not sure whether this is correct. I assume that `docker-machine provision` should work on running and stopped machines. But on a quick test, `docker-machine provision` only worked with a running machine.

Is this how it is supposed to work? If so, I will have to update this PR to only complete running machines.
Currently all machines are completed.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Nice, thanks @albers. Only running machines, since the binary will log in via SSH and execute some commands to do the provisioning.

**Comment by albers** [comment]
Is this also valid for `regenerate-certs`?

**Comment by nathanleclaire** [comment]
Yes

**Comment by albers** [comment]
@nathanleclaire The PR is updated so that only running machines are completed for `docker-machine provision`. Bash completion for `docker-machine regenerate-certs` was updated accordingly, too.
PTAL

**Comment by nathanleclaire** [comment]
Sweet! Thanks @albers

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
