### PR TITLE
Re-add make install to Makefile

### PR DESCRIPTION
**Pull request by nathanleclaire**
@dmp42 I use this target -- not sure why it was removed and it threw me for a loop.

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by dmp42** [comment]
Sorry - it got removed because it was not really working ($(PREFIX) ignored).

Let's re-add it if you depend on it.

Can you just fix it so it honors prefix:
`cp $(PREFIX)/bin/* /usr/local/bin`

... and maybe make sure it doesn't choke on subfolders? (eg: generated by cross-compilation)

**Comment by nathanleclaire** [comment]
Yeah sounds good!

**Comment by dmp42** [comment]
Mmm... maybe rebase? some unrelated commits are there.

**Comment by nathanleclaire** [comment]
Oops, yep I'll fix it

**Comment by dmp42** [comment]
LGTM!
Thanks @nathanleclaire

**Pull request merged**
