### PR TITLE
Migrate 'amazonec2' driver to AWS SDK

### LINKED ISSUE #858: Replace AWS driver
With the release of an AWS (alpha) SDK for Go, https://github.com/awslabs/aws-go

Using the official SDK has advantages over our current implementation since we wouldn't have to maintain lower level code.

### LINKED ISSUE #1571: EC2: docker-machine restart does not perform a reboot
# Problem
`docker-machine restart` appears to do a shutdown and restart of the EC2 instance, causing the EC2 instance to get a new external IP address. This can cause issues with other containers that reply on the IP address, since the external IP address is used as the default hostname.

screen shot 2015-07-22 at 10 25 55 pm

Machine running
```
$ docker-machine ls
NAME           ACTIVE   DRIVER         STATE     URL                         SWARM
foobar                  amazonec2      Running   tcp://52.2.125.236:2376     
```

Restart called
`$ docker-machine restart foobar`

After complete, it can be seen the IP address has changed
```
$ docker-machine ls
NAME           ACTIVE   DRIVER         STATE     URL                         SWARM
foobar                  amazonec2      Running   tcp://52.5.78.200:2376      
```

# Solution
Rebooting the EC2 retains the IP address / hostname

`$ docker-machine ssh foobar "sudo reboot"`

IP retained through the reboot
```
NAME           ACTIVE   DRIVER         STATE     URL                         SWARM
foobar                  amazonec2      Running   tcp://52.5.78.200:2376      
```

# Workaround
Use the following
`docker-machine ssh foobar "sudo reboot"`

# Environment

```
$ uname -a
Linux foobar 3.13.0-58-generic #97-Ubuntu SMP Wed Jul 8 02:56:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker-machine --version
docker-machine version 0.3.0 (0a251fe)
```

### PR DESCRIPTION
**Pull request by jeanlaurent**
This takes the PR #1850 from @euank and rebase it on current master. ( fixes #858 )
Oh, btw this fixes #1571 as restart is now properly handled.

This is an LGTM on @euank commits. I added a cleanup commit, which I let @docker/machine-maintainers appreciate.

### CODE REVIEW

**Comment by dgageot** [comment]
@jeanlaurent @euank Will review it on Monday

**Comment by euank** [comment]
Your additional change LGTM. Thanks! I would have been happy to make those changes if you asked on my PR, but this works as well.

**Comment by jeanlaurent** [comment]
@euank I wanted this PR to go with the next release ( next Monday ). And wasn't that comfortable to ask for a quick rebase, considering this is holiday time & we didn't find the time before to handle your PR. 

But good to know. I believe there is quite a bunch of PR enhancing the ec2 drivers that will be impacted.

**Comment by dgageot** [comment]
LGTM

**Pull request merged**
