### PR TITLE
driver exoscale: move egoscale lib from pyr to exoscale org

### PR DESCRIPTION
**Pull request by marcaurele**
Signed-off-by: Marc-Aurèle Brothier <m@brothier.org>

### CODE REVIEW

**Comment by marcaurele** [comment]
I will push another change for the package naming

**Comment by marcaurele** [comment]
Ready to be merged

**Comment by shin-** [comment]
LGTM, thanks!

**Comment by marcaurele** [comment]
v0.13.0-rc1 is working correctly regarding #4256 & #4255

**Pull request merged**
