### PR TITLE
Fix choke when starting from Saved state

### PR DESCRIPTION
**Pull request by nathanleclaire**
Closes https://github.com/docker/machine/issues/809
Closes https://github.com/docker/machine/issues/1412

cc @ehazlett 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by ehazlett** [comment]
LGTM

**Comment by jwaldrip** [comment]
Awesome, I was about to file an issue about this. Kudos!

**Comment by lhazlewood** [comment]
I'm getting this error with docker-machine 0.5.5 on a Mac running OS X Yosemite 10.10.5.  In what version is this fix slated to be released?

**Comment by nathanleclaire** [comment]
@lhazlewood Yes please file a new issue.

**Pull request merged**
