### PR TITLE
cloudstack driver

### PR DESCRIPTION
**Pull request by svanharmelen**
This is a fully working and tested CloudStack driver for docker machine. All info needed to use this driver for your (private) CloudStack setup can be found in the updated README.

Of course there are a lot of use cases (different CloudStack setups) that could need more and/or other options to make the driver also work for those use cases. But since this is not predictable and this is currently tested with standard basic and advanced zones, most use cases should be covered without additional work.

This PR is a follow up of PR #129

Signed-off-by: Sander van Harmelen <sander@xanzy.io>

### CODE REVIEW

**Comment by svanharmelen** [comment]
@dduportal would be great if you (and anyone else who's up for it) could give this a few test runs...

**Comment by dduportal** [comment]
@svanharmelen Which kind do you expect exactly :
* Use case scenarii in a markdown doc or here ?
* Path to a end-to-end testing (devcloud VM with automated tests)
* Go functionnal tests ?
* Basic shell script running our machine tests

?

(I just want to be sure :) )

**Comment by svanharmelen** [comment]
@dduportal well I don't expect anything really... I know you tested the driver before when it was just build and since it now changed quite a lot it would be nice if you can confirm your use cases still work as expected with the updated code.

The use cases I have myself are tested of course, but it would be nice to have some feedback and/or confirmations from other users.

And well... If your up to it, by all means write all the test you would like to add! Adding tests (both unit tests and functional tests) are still on the todo list.

If you want I can make you an collaborator of my `machine` fork so you can work in there and merge your PR's in there so they'll end up in this PR. On the other hand I also spoke with @ehazlett on IRC this afternoon and hopefully it will not take long anymore before we can merge this. Most likely as soon as v0.1.0 is release which is close to being done..

**Comment by dduportal** [comment]
Testing will be done around the end of the week (can't make access to our CS before)

**Comment by cortezone** [comment]
Hi svanharmelen,
I tried to apply this patch and got this error.  Any reason this could be the case?  I cloned the original machine repo, used wget to download the patch (425.patch) and used "git am" to patch.  I'm running all this on a coreos VM.  Could you please take a look and see what the issue is?

Kind regards,

coretezone

**Comment by svanharmelen** [comment]
@cortezone what error did you get? As I notice that it needs to be rebased again (that almost seems to become a daily task lately) I assume a build error?

Will try to update the PR so it can be build/merged again.

**Comment by cortezone** [comment]
The errors are as follows:

error: patch failed: README.md:266
error: README.md: patch does not apply
error: patch failed: commands.go:16
error: commands.go: patch does not apply

**Comment by svanharmelen** [comment]
@cortezone just rebased the PR so it should be good now...

**Comment by cortezone** [comment]
@svanharmelen works great thanks!

**Comment by cortezone** [comment]
@svanharmelen, hi.  I'm facing some issues with the cloudstack driver.  I've successfully built the binary and when I run it I get some syntax errors.  I need guidance.  Here's an example and the errors generated:
./machine create -d cloudstack --cloudstack-api-url="http://10.10.1.2/client/api"--cloudstack-template="coreos-production-xen-image" --cloudstack-offering="Container Instance" --cloudstack-api-key=FXHM348BTmSfn00000y4rk26Px6dTJYMBOHagJZrBytHLENIlYBp-z0J0r-YX4atcbOpTSOx0642duMUM99WDg --cloudstack-secret-key=zpSidvvP0Fwia-EsSxRyl5bEOa5lusP2vvxvsUSZuOt5D2tFI3-ohHqO5rooCv7vgd_yE-IIxveMq7W0L4ZjEA --cloudstack-no-public-ip=yes --cloudstack-zone="DEVZONE" node01 
ERRO[0000] Error creating machine: cloudstack driver requires the --cloudstack-public-ip option
WARN[0000] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0000] Error creating machine

TIA
@cortezone

**Comment by cortezone** [comment]
Hi @svanharmelen my bad.  I fixed the syntax and it's working.  I assumed that the cloudstack-no-public-ip required an argument hence the mistake.
Thanks for the good work.  One question though. Can I use for instance an Ubuntu template and still get it install Docker?  My test used a CoreOS template.

**Comment by svanharmelen** [comment]
@cortezone currently the driver is expecting a CoreOS image (see README), but I guess it would be nice to extend that later on so you can also use Ubuntu or EL...

**Comment by ehazlett** [comment]
@cortezone we will need to use Ubuntu 14.04 for the drivers.  That's what we have standardized on for now.  In the future we are planning to use cloudinit to allow for customization.

**Comment by cortezone** [comment]
Thanks @svanharmelen and @ehazlett.  I bumped into an issue using the driver today.  I launched a machine on CoreOS and it supposedly failed though the VM was created and I could use the instance in ACS GUI but Docker-Machine returned an error about an exit code of 255.  Error creating machine: exit status 255. Googling I saw something about vm name with "." or "-" not supported for the DigitalOcean driver though later retracted.  I've tried with vm name without "." or "-" but I get the same error though the VM gets created.
ERRO[0230] Error creating machine: exit status 255
WARN[0230] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0230] Error creating machine

**Comment by ehazlett** [comment]
Usually that's networking related I believe.  The "." and "-" was not an
issue or at least didn't appear to be.  I successfully created using both
and the OP never responded with any more debugging / issues.  It could be a
race condition with the instance being "up" but ssh not responding or ready
yet.

**Comment by svanharmelen** [comment]
@ehazlett check about Ubuntu 14.04 being the standardised OS for machine drivers. I'll update this PR accordingly within the coming days so it complies to that.

@cortezone did it happen once, or can you reproduce the problem?

**Comment by cortezone** [comment]
@svanharmlen this happened on three occasions with coreos and centos templates.  Will try with ubuntu 14.04 template tomorrow.

**Comment by svanharmelen** [comment]
@cortezone the driver will currently not work with CentOS and/or Ubuntu (unless your templates have cloud-init running on them)

**Comment by cortezone** [comment]
@svanharmelen and @ehazlett, I've tried with a Ubuntu 14.04 template and the result is the same.  I can ssh into the machine created so I guess the network is up.  If there's a timeout installing the ssh keys it might be because it takes time for the network to come up as the vm is created.
INFO[0000] Creating SSH key pair...
INFO[0000] Creating CloudStack instance...
INFO[0072] Stopping Docker...
ERRO[0072] Error creating machine: exit status 255
WARN[0072] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0072] Error creating machine

**Comment by ehazlett** [comment]
We are going to be refactoring the internals a bit very soon to help
alleviate the variance in the driver stack.  This should help with basic
things like ssh etc.  Also, you shouldn't need to use cloudinit at the
moment (we are hoping to move to that in the future and you won't have to
do anything in your driver for that).  Right now, all of the provider
drivers are installing from the docker apt repos.

**Comment by cortezone** [comment]
Hey guys,
patch application issues arising again.  Still with the README.md:306 patch does not apply.  Has this been rebased recently?
@cortezone

**Comment by svanharmelen** [comment]
@cortezone do you still have the issue? I see that the PR is still good to be merged automatically, so I would not expect any merge errors...

**Comment by cortezone** [comment]
Not sure what I'm doing wrong but this is what I get when I try to patch using 

git am < 425.patch


Applying: cloudstack driver
error: patch failed: README.md:306
error: README.md: patch does not apply
Patch failed at 0001 cloudstack driver
The copy of the patch that failed is found in:
   /root/machine/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

**Comment by cortezone** [comment]
Please go ahead and merge.  I believe the error must be coming from something in my environment.  Looks crazy though.

**Comment by svanharmelen** [comment]
@cortezone check... Not able to merge though, as we will need one more refactor to make the driver work with Ubuntu 14.04 and the default Docker apt repos...

**Comment by ehazlett** [comment]
@svanharmelen you may want to hold off for a bit longer.  we are working on the driver refactor which will be (hopefully) the last time you need to make changes to the driver as far as machine is concerned.  this is the last refactor to get all of the pending drivers on the same page and have them merged.  #756 is the issue if you want to track.  thanks!

**Comment by cortezone** [comment]
@svanharmelen and @ehazlett, 
I run the patch with a 3 way merge.  After a successful build I tried to create a machine (CoreOS template) but this failed.  The Cloud-init script couldn't get the ssh keys.  Below are the errors I could pick up.

machine create output:
INFO[0000] Creating CA: /root/.docker/machine/certs/ca.pem
INFO[0002] Creating client certificate: /root/.docker/machine/certs/cert.pem
INFO[0003] Creating SSH key pair...
INFO[0004] Creating CloudStack instance...
ERRO[0041] Error creating machine: error installing docker: exit status 255

WARN[0041] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0041] Error creating machine


CoreOS console stuff showing failure of ssh key fetch:

[  OK  ] Reached target Login Prompts.
[  OK  ] Started Authorization Manager.
[  OK  ] Reached target Multi-User System.
[  OK  ] Stopped Sets SSH key from metadata.
         Starting Sets SSH key from metadata...
[  OK  ] Started Modifies /etc/environment for CoreOS.
[    9.491095] cloudstack-ssh-key[654]: Adding/updating cloudstack:
[    9.498895] cloudstack-ssh-key[654]: /home/core/.ssh/authorized_keys.d/cloudstack.hYBiW54Mjn is not a public key file.
[FAILED] Failed to start Sets SSH key from metadata.
See "systemctl status cloudstack-ssh-key.service" for details.
[  OK  ] Stopped Cloudinit from CloudStack-style metadata.
         Starting Cloudinit from CloudStack-style metadata...
[  OK  ] Reached target Run Docker containers before main Docker starts up.
         Starting Docker Application Container Engine...
[  OK  ] Started Docker Application Container Engine.
[  OK  ] Started Cloudinit from CloudStack-style metadata.
[  OK  ] Started Load cloud-config from /usr/share/oem/cloud-config.yml.
[  OK  ] Reached target Load system-provided cloud configs.
[  OK  ] Reached target Load user-provided cloud configs.
[   10.188622] ip_tables: (C) 2000-2006 Netfilter Core Team
[   10.262409] bridge: automatic filtering via arp/ip/ip6tables has been deprecated. Update your scripts to load br_netfilter if you need this.

**Comment by cortezone** [comment]
VM was created as per instance running in ACS web gui but of course I can't access it without ssh key.

**Comment by cortezone** [comment]
Surprise surprise.  Apparently the keys were successfully uploaded and I could login with the key found at ~/.docker/machine/machines/<machine_name>.  CoreOS reports however that two units failed

CoreOS stable (557.2.0)
Failed Units: 2
  cloudstack-ssh-key.service
  docker.service

**Comment by svanharmelen** [comment]
@ehazlett thanks! Will keep an eye on #756 and refactor this one to align it right after it's merged... Will contact you as soon as that is done so we can review and (hopefully) get this one merged...

**Comment by svanharmelen** [comment]
@cortezone it could very well be that some things have changed between the moment this PR was created and current HEAD, that is causing issues when trying to use this PR and HEAD together.

As @ehazlett pointed out a refactor/update of the driver layout is forthcoming, so I'll purpose to not invest time in testing/debugging this PR until the refactor of the driver layout is done and this PR is refactored accordingly.

After that any testing would be more then helpful in getting the PR merged so we no longer have to keep refactoring and just use HEAD :wink:

**Comment by svanharmelen** [comment]
@ehazlett I noticed PR #756 is now merged... So would this be the right moment to refactor this driver and right afterwards review it? If so I'll make time for the refactor coming Monday.

Would be really nice if we can finally get this one in...

**Comment by ehazlett** [comment]
@svanharmelen yes.  i'm working on driver docs probably next week so if you want to start that would be great to get your feedback and make sure we don't miss anything.  thanks!

**Comment by xied75** [comment]
@svanharmelen @ehazlett We want to start trying this driver, please kindly advise should we grab the fork or patiently wait you guys finish the refectoring? :)

Best,

Dong

**Comment by svanharmelen** [comment]
@xied75 I think it would be smart to wait for the refactor... I'll have that planned for coming Monday, so if you can wait a few days...

Otherwise you could of course already try and play with this one, but currently it needs a CoreOS image (see the [readme](https://github.com/svanharmelen/machine/blob/master/README.md) for more info).

**Comment by runseb** [comment]
thanks @svanharmelen for your hard work on this. @ehazlett just so you know, there quite a few cloudstack cloud users who want to use machine and need this driver (same for the exoscale driver that is also cloudstack based).  so you have a big +1 from the cloudstack community to merge this. thx

**Comment by svanharmelen** [comment]
@runseb Thx! I was planning to update the PR today to be inline with the latest guidelines, but other prio's prevented me from doing so :disappointed:

But I'll expect to be able to do so before the end of this week...

**Comment by runseb** [comment]
good to hear, thanks for sticking to it.

**Comment by Kosta-Github** [comment]
any updates on this? could use it as well...

**Comment by svanharmelen** [comment]
Well... It's on my agenda for a while now, but things are way to busy to get anything done. Really hope to be able to make some time for this coming week...

**Comment by svanharmelen** [comment]
I must admit I'm having difficulties finding time to pick this one up... So if there is anyone out there who can/will step in, I'm more then willing to donate the code currently in this PR to you so it can be refactored and hopefully merged...

**Comment by runseb** [comment]
let me see. I might do it myself, but I will ask on the cloudstack list

**Comment by svanharmelen** [comment]
@runseb and? Any takers?

@dduportal don't know if you still use this or want to use it? As our company hardly uses any Docker I simple cannot find time to sit down for this (even through I don't believe updating this PR would be that much work, but still). So if you're interested you can just copy over the code to your fork and create a new PR based on that. I will then close this PR...

Let me know your thoughts! If nobody cares anymore, I'll just close this PR and call it a day :wink:

**Comment by dduportal** [comment]
Hi !

Sorry, our Cloudstack may (or may not) be replaced by another tech., discussions are going up, so i don't have more time those days.

I'm still interested anyway, to replace our vagrant + vbox stack by a docker-machine + b2d one.

I need time to check the changes, so you can close, we'll repopen a new one in the future when needed : it'll help maintainers to have a clear view I think.

**Comment by svanharmelen** [comment]
@dduportal thanks for your update! Will wait just a little more (also for @runseb his reaction) and if nothing happens will indeed close this one...

**Comment by runseb** [comment]
@svanharmelen give me another week. I am traveling right now.

**Comment by svanharmelen** [comment]
@runseb sure, no problem...

**Comment by atsaki** [comment]
Hi @svanharmelen , @runseb , @dduportal 

I want generic cloudstack driver to use docker machine on advanced zone.
I can have some time to write some code if it is needed.

Is there anything I can do?

**Comment by runseb** [comment]
@atsaki that would be great. We need to refactor this driver according to the exoscale driver that was recently merged. The go driver for cloudstack needs to be updated...

**Comment by svanharmelen** [comment]
@atsaki sounds good! I think the easiest way forward is you just copy the code in this PR (branch: https://github.com/svanharmelen/machine/tree/f-cloudstack-driver) to a new fork of the `machine` repo. Then if your ready to make a PR just give me a ping. I will then close this PR and refer to your new PR.

Does that sound like a plan?

**Comment by atsaki** [comment]
Hi @svanharmelen ,

Sorry for late reply.

I opened a new PR #1323.
I copied the code from your branch and modified to support basic zone and swarm.

**Comment by svanharmelen** [comment]
Closing this PR in favour of PR #1323 

Just gave my feedback on the code there, so that one should become the main PR for adding CloudStack support.

**Pull request closed without merging**
