### PR TITLE
added hyperv static mac address and vlan option for machine creation

### PR DESCRIPTION
**Pull request by sipicsg**
Signed-off-by: Sipics Gergely <gergely.sipics@possible.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
@sipicsg Cool, thanks for the PR.  It looks like there is some server failures from Coveralls in the CI build (not your fault).

**Comment by dgageot** [comment]
Hi @sipicsg could you also update the driver documentation please?

**Comment by jeanlaurent** [comment]
Thx for all these, @sipicsg, could you rebase rather than merge, so we dont have the merge commit ( a213d92 ) in the history here ? These will probably lift the dco/no flag too.

**Comment by sipicsg** [comment]
'I've got:

```
Bad response status from coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}
mk/coverage.mk:21: recipe for target 'coverage-send' failed
```
Is it my fault?

**Comment by dgageot** [comment]
LGTM. ping @jeanlaurent

**Comment by jeanlaurent** [comment]
LGTM

**Pull request merged**
