### PR TITLE
added documentation for --azure options

### PR DESCRIPTION
**Pull request by chanezon**
Now that machine becomes my favorite way of provisioning Docker hosts in Azure, making sure the docs are complete for other developers.

### CODE REVIEW

**Comment by ehazlett** [comment]
Thanks!  Would you mind signing the commit?

**Comment by chanezon** [comment]
Signed-off-by: Patrick Chanezon <patrick@chanezon.com>

**Comment by ehazlett** [comment]
You actually need to sign with "-s".  See https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work for details.   Thanks!

**Comment by chanezon** [comment]
Sorry, done.
I used git commit --amend --signoff

**Comment by ehazlett** [comment]
Since these are docs and you have the sign off manually above I will merge this time.  Next time please use the -s when committing.  You can also use the  validate-dco script to check. 

Thanks!

LGTM

**Comment by chanezon** [comment]
Thanks, I will sign it from the get go next time.

**Comment by ehazlett** [comment]
thanks!

**Pull request merged**
