### PR TITLE
cleanup log.*ln and correct typos error 

### PR DESCRIPTION
**Pull request by xiaohui**
1. cleanup log.*ln for #1081
2. add "\n" to config command
3. typos error

Signed-off-by: Xiaohui Liu <xiaohui.liu@ucloud.cn>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
I'm in favor of these changes.

@xiaohui Will you please squash all of your commits into one?

**Comment by thaJeztah** [comment]
ping @nathanleclaire I see the commits are squashed, PTAL

**Comment by xiaohui** [comment]
Thx,  @thaJeztah.  @nathanleclaire, I have squashed the commits, but the ci/circleci tested failed because of importing an non-exist package

**Comment by nathanleclaire** [comment]
The Circle issue is unrelated.  Thanks @xiaohui .

LGTM

**Pull request merged**
