### PR TITLE
Fixes #1289 Env swarm parameter lost on the eval help message

### LINKED ISSUE #1289: Env swarm parameter lost on the eval help message
The helper for the docker-machine env command is not consistent with the parameters passed :

````
$ docker-machine env --swarm swarm-master
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.110:3376"
export DOCKER_CERT_PATH="~/.docker/machine/machines/swarm-master"
export DOCKER_MACHINE_NAME="swarm-master"
# Run this command to configure your shell:
# eval "$(docker-machine env swarm-master)"
`````

Note : it doesn't say 

````
eval "$(docker-machine env --swarm swarm-master)"
````

So running that eval command will get me to the docker api of the swarm master, not exactly what I want.

See the port :
````
$ docker-machine env swarm-master|grep DOCKER_HOST
export DOCKER_HOST="tcp://192.168.99.110:2376"
$ docker-machine env --swarm swarm-master|grep DOCKER_HOST
export DOCKER_HOST="tcp://192.168.99.110:3376"
````

### PR DESCRIPTION
**Pull request by aperepel**
My go-fu is non-existent, and toolchain isn't where I want it to be yet, but was able to fix this nagging issue :)

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Looks like there's some funny business going on with the integration test PR commits ... I think you need a rebase.

**Comment by aperepel** [comment]
Yeah, pull/merge played a trick on me here, I'll redo and cherry pick, traveling the next couple days

**Comment by nathanleclaire** [comment]
@aperepel If you run `git rebase origin/master` on your feature branch, and then force push to that branch, it usually fixes it for me if I run into issues like this.  Would be easier than cherry-picking and re-opening a PR.

**Comment by aperepel** [comment]
Sorry, @nathanleclaire something was very wrong with the origin & upstream tracking. I've created a feature branch and opened a new PR since.

**Pull request closed without merging**
