### PR TITLE
Fix issue #4424 - Pre-create check: "Hyper-V PowerShell Module is not available"

### PR DESCRIPTION
**Pull request by beppler**
Pull request #4404 adds the ability to run Hyper-V driver when VMware PowerCLI is installed, but it make the pre-create check for Hyper-V module fail.

This corrects the test as indicated as best solution on #4424.

### CODE REVIEW

**Comment by dgageot** [comment]
LGTM

**Comment by gbraad** [comment]
Can this be tagged as a new release?

**Comment by krzysztofantczak** [comment]
Quick hack for people in hurry. Editing docker-machine binary file and replacing (ie. with vim or other editor - kind of - safe for binary files) :%s/Hyper-V/hyper-v/g works.

**Comment by gbraad** [comment]
I'd rather not choose to go for local patches, as this will result in issues later on.
At the moment we pull a revision ... waiting for a tag

**Comment by mtudor** [comment]
Although hacky, @krzysztofantczak suggestion did work for me (on Windows, C:\Program Files\Docker\Docker\resources\bin\docker-machine.exe - make a backup of the file first) if anyone is in a bind and needs a quick fix; at your own risk and bearing in mind the warning from @gbraad.

**Pull request merged**
