### PR TITLE
quote cmd path

### PR DESCRIPTION
**Pull request by princemaple**
## Description

see issue

## Related issue(s)

https://github.com/docker/machine/issues/4444

## PR description

I have no idea if this works. I don't write Go. Hoping someone could compile it and give it a go...

### CODE REVIEW

**Comment by princemaple** [comment]
At least the builds are green...

**Comment by princemaple** [comment]
Hi sorry I don't actually write Go. There isn't any existing Windows integration test example I can build upon, I have no idea how to do it. Would be great if someone could compile this branch and just give it a go on Windows.

**Comment by princemaple** [comment]
@shin- could you take a look?

**Comment by nekenk1** [comment]
No this is not working, I made another pull request to fix it: https://github.com/docker/machine/pull/4707

**Pull request closed without merging**
