### PR TITLE
Features/gandi driver

### PR DESCRIPTION
**Pull request by gdchamal**
Add a driver for Gandi Iaas provider

Same patching logic than in digitalocean driver is done to have a working docker daemon with identity support.

### CODE REVIEW

**Comment by ehazlett** [comment]
Thanks for the contribution!  I will get this in the integration tests to get the merge process started.

**Comment by gdchamal** [comment]
I rebased and adapt to new driver structure and workflow. It's working really fine using default image

**Comment by soulshake** [comment]
Hi @ehazlett. Is there anything preventing this from being merged, or anything that can be done to help?

**Comment by ehazlett** [comment]
@soulshake hey! this needs to be rebased against the new driver model (from the latest refactor).  here is the new spec: https://github.com/docker/machine/blob/master/docs/DRIVER_SPEC.md.

we are going to announce this to all of the driver PRs after the 0.2.0 release -- you beat me to it :)

**Comment by gdchamal** [comment]
Ok good to hear, I'll rebase in next days. Thanks for your reply.

**Comment by ehazlett** [comment]
@gdchamal thanks!

**Comment by gdchamal** [comment]
update done, all is working fine on my side.

**Comment by ehazlett** [comment]
Hi , thanks for your efforts and persistence in submitting this driver. We are extremely excited that there is so much interest in Docker Machine and we really appreciate your interest. However, at this time it is proving to be extremely difficult for us to keep up with reviewing and testing each of these drivers for inclusion in the Machine core. We really want to switch to a more pluggable model, as well as polish up a few things about the driver model which need to be changed to ensure a smooth and sustainable future.

Therefore, we will be moving to a plugin model for 0.5 and would love to have you involved in the design and development process. We are closing the outstanding driver PRs at this time, but please keep the code. We will stick closely to the current driver interface and you should be able to re-use a lot (if not all) of the existing driver along with the new plugin model. We will be moving all of the drivers which are merged directly into Machine today to the plugin model when it is available, so there will be no special treatment of those, and there will be documentation outlining the process of developing and using a Docker Machine driver plugin.

With all of that being said, we want to apologize for the lack of feedback on your pull request. As contributors ourselves, we understand that being left in limbo is no fun. We would have liked to address this sooner, and in the future we will be more responsive around these kinds of issues.

Once again, we thank you for the contribution and the tremendous support. Keep hacking strong!

If you want to contribute to the design of the plugin model, we'd love to get your input on this issue where we will be planning it:

https://github.com/docker/machine/issues/1626

@ehazlett & @nathanleclaire

**Pull request closed without merging**
