### PR TITLE
Remove Provider

### PR DESCRIPTION
**Pull request by ehazlett**
This removes the `provider` package.  It is no longer necessary and has been replaced by the provisioning system.

Refs #1190

### CODE REVIEW

**Comment by ehazlett** [comment]
Tested against VirtualBox, AmazonEC2 and DigitalOcean -- all work as expected.

**Comment by nathanleclaire** [comment]
+0 -121 :heart_eyes: :heart_eyes: :heart_eyes: 

LGTM

**Comment by nathanleclaire** [comment]
Travis is blowing up with "no install location" errors though, not sure what's up with that.

**Comment by ehazlett** [comment]
@nathanleclaire fixed PTAL

**Comment by nathanleclaire** [comment]
Nice LGTM

**Pull request merged**
