### PR TITLE
Retrive latest boot2docker release tag name from VERSION file directly

### PR DESCRIPTION
**Pull request by saratovsource**
I think there are no limits for directly fetching file content via raw requests?

### CODE REVIEW

**Comment by ehazlett** [comment]
@nathanleclaire you see any reason to not use this?

**Comment by nathanleclaire** [comment]
Hm, I do like the idea of addressing this concern (API request limit) but I don't know what that file is used for currently (and consequently how important / likely to get updated correctly it is).  cc @SvenDowideit @tianon do you have any thoughts on this?  Would you implement it this way in b2d-cli?

**Comment by ehazlett** [comment]
@SvenDowideit your thoughts on the above?

**Comment by tianon** [comment]
Hey, sorry I missed this.  This will work now, and _should_ continue to work in the future, but it does definitely mean there'd be a period of anywhere from a few minutes to a few hours after the updated file is pushed to `master` before the ISO is pushed that people will have failing upgrades.

**Comment by ehazlett** [comment]
@tianon No worries!  

I think the best route would be using the API since worst case scenario that would affect that requesting user while the file method would potentially affect a larger base.  Closing for now.  Thanks!

**Pull request closed without merging**
