### PR TITLE
Fix installation notes for 0.5.3

### PR DESCRIPTION
**Pull request by dgageot**
Fix the installation notes, now that we have a single binary

Related to https://github.com/docker/machine/pull/2453

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
@SvenDowideit Do you know what's failing?

**Comment by jeanlaurent** [comment]
LGTM 

Albeit, we must understand why the doc build is failing yet again.

**Comment by nathanleclaire** [comment]
Ah man, probably should add updating this page to the release process document as well.  I'm not sure it's covered in there but leaving those as v0.5.0 was definitely a mistake.

**Comment by dgageot** [comment]
Had to lint all the markdown documents to make the tests pass

**Pull request merged**
