### PR TITLE
get-started.md: use same machine name

### PR DESCRIPTION
**Pull request by henrik**
Instructions said to create a machine named "default" but then connect to one named "dev".

### CODE REVIEW

**Comment by dgageot** [comment]
Hi @henrik, I guess this will conflict with https://github.com/docker/machine/pull/2843

**Comment by henrik** [comment]
@dgageot Good catch. If that one won't be merged for a while maybe changing to "default" consistently would be worthwhile in the meanwhile then. And when it is merged the docs could rely on the implicit default. The current state of things is that the guide has commands that won't work due to this inconsistency.

**Comment by nathanleclaire** [comment]
Hi @henrik, thanks for the contribution.  My opinion is that we should use "default" everywhere in this guide as it's heavily the convention elsewhere.  If you find any inconsistencies in there please let us know!

**Comment by nathanleclaire** [comment]
FYI it's that way in master now that the mentioned PR's been merged: https://github.com/docker/machine/blob/master/docs/get-started.md

**Comment by henrik** [comment]
Nice!

**Pull request closed without merging**
