### PR TITLE
Add an errors column to docker-machine ls

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by jeanlaurent** [comment]
LGTM 

@nathanleclaire  I let you have the final word on it.

**Comment by jeanlaurent** [comment]
ping @nathanleclaire

**Comment by dgageot** [comment]
Let's merge it since there's one LGTM.
I'm going to work on added more tests to `ls.go`

**Comment by nathanleclaire** [comment]
LGTM -- we can iterate on it if we want to change anything.

This kind of thing is definitely thinking we might want to create a compound `error` type for aggregating multiple errors.

**Comment by dgageot** [comment]
@nathanleclaire the thing is most errors are fatal so there's little to aggregate in fact

**Pull request merged**
