### PR TITLE
Add xhyve driver

### PR DESCRIPTION
**Pull request by zchee**
Add xhyve driver.

@nathanleclaire seems unable to launch the xhyve. https://github.com/zchee/docker-machine-xhyve/issues/9
but, I know at least two Japanese people were the able to launch.

Would you let me know what your thoughts are on this matter?

If you think this repository is too development-stage, I will once close the pull request.
And I will do best to develop.

/cc @nathanleclaire

### CODE REVIEW

**Comment by dgageot** [comment]
LGTM. I didn't test the driver though. We might come up with a **tested** list in the future

**Comment by dgageot** [comment]
Merged with https://github.com/docker/machine/pull/2390

**Comment by zchee** [comment]
@dgageot 
Thanks.

BTW, `docker-machine-***` and `docker-machine-driver-***`, which is correct?
https://github.com/docker/machine/blob/master/docs/AVAILABLE_DRIVER_PLUGINS.md
If `docker-machine-driver-***` is correct, I want to rename at once.

**Comment by nathanleclaire** [comment]
@zchee `docker-machine-driver-*` is the correct name.

**Comment by zchee** [comment]
@nathanleclaire Thanks.

I will rename of the repository, and send the PR.
Please confirm.

**Comment by nathanleclaire** [comment]
@zchee SGTM

**Pull request closed without merging**
