### PR TITLE
gce: fix for instance not being refreshed on create

### PR DESCRIPTION
**Pull request by ehazlett**
This is in reference to https://github.com/docker/machine/pull/995#discussion-diff-29295038

### CODE REVIEW

**Comment by vincentbernat** [comment]
I think you should also restore the test against `err` value.

**Comment by zchee** [comment]
I tried this commit, but https://github.com/docker/machine/issues/1066 last comment.

**Comment by ehazlett** [comment]
@vincentbernat -- yep good catch

**Comment by ehazlett** [comment]
@vincentbernat fixed.  rebased.

**Comment by ehazlett** [comment]
@zchee i'm checking on that issue.

**Comment by ehazlett** [comment]
@zchee this is working fine for me: `config`, `env`, `ssh` all work fine for me with both the oauth flow and by specifying an existing token.  i'll continue debug for that error on that thread.

**Comment by zchee** [comment]
@ehazlett
BTW, I would have been api lock is too debug, do you How does development?

**Comment by zchee** [comment]
@ehazlett Ok, I'll retry now.

**Comment by zchee** [comment]
@ehazlett Sorry, I was also working properly now.
I do not know what happened :(

**Comment by jeffmendoza** [comment]
Just built and tested, works great.

**Comment by ehazlett** [comment]
@jeffmendoza thanks!

**Comment by ehazlett** [comment]
@zchee np :)

**Pull request merged**
