### PR TITLE
Rebase + fixes of '--tls-san' PR #1228

### LINKED ISSUE #1227: Server-side certs are too restrictive, need ability to add extra SANs
Right now, each generated server-side certificate (both for the Swarm master and the docker daemon) contain only one SAN (Subject Alt Name) which points to the Host IP (usually localhost).

This makes it too restrictive, it's not possible to connect to my Swarm API from my internal network...

I propose a global option `--tls-san' which allows to specify extra SANs.

### PR DESCRIPTION
**Pull request by jeanlaurent**
Added the ability to add extra SANs to all server-side certificates generated by machine.

Fixes #1227
Closes #1228
Allow https://github.com/samalba/machine/pull/1

### CODE REVIEW

**Comment by jeanlaurent** [comment]
this pass all integration tests.

ping @docker/machine-maintainers

**Comment by nathanleclaire** [comment]
Think we should hold off and wait to get back to mainline `codegangsta/cli` before merging workarounds like this?

In other words, while it's a nice feature, does the demand for it merit such a workaround?  I haven't heard much chatter about it lately.

**Comment by dgageot** [comment]
@jeanlaurent Could you clean up the commits (specially the merge commit) to make the workaround more visible?
This PR blocks another PR and two tickets. So +1 for merging and submitting a ticket to `codegangsta/cli`

**Comment by nathanleclaire** [comment]
As noted in standup today: should we maybe double down on trying to get back to mainline `codegangsta/cli` instead of bundling workarounds like this?

I had expected them to merge the PR upstream faster.

**Comment by jeanlaurent** [comment]
Rebased on vendored `codegangsta/cli`.
Workaround the issue on `GlobalStringSlice` where the issue was not in `codegangsta/cli` but in the way create is called somehow twice in the code.

cc @docker/machine-maintainers

**Comment by dgageot** [comment]
LGTM

**Pull request merged**
