### PR TITLE
Add SUSE Enterprise Linux and openSUSE provision

### PR DESCRIPTION
**Pull request by flavio**
Add support for SUSE Enterprise Linux and openSUSE.

Code revised to build against current master.

Signed-off-by: Flavio Castelli <fcastelli@suse.com>

### CODE REVIEW

**Comment by flavio** [comment]
This is an updated PR made after https://github.com/docker/machine/pull/1436 failed to build against latest master code.

ping @dmp42

**Comment by dmp42** [comment]
Thanks a lot @flavio - I know this has been lingering for some time...

Any doc or tests we can add for this?

**Comment by flavio** [comment]
I don't think we need to update the documentation, this has not been done for the other provisioners. Am I right?

About the tests, I don't think a unit test would be really useful. Probably an integration test would be better. Unfortunately that would take some time to be written (I have to understand how the Red Hat and the Rancher ones work).

We are however testing that internally at SUSE, I know it's not really great but at least it's something...

**Comment by dmp42** [comment]
LGTM
This is building and doesn't impact the rest.
I don't see a reason not to merge this.

@nathanleclaire are you happy with it?

**Comment by flavio** [comment]
@nathanleclaire is there anything I can do to help you make the final decision? We have already reached 0.5.0 rc3; I would really love to have this PR finally merged into 0.5.0. :pray:

**Comment by nathanleclaire** [comment]
Yup, I think it's OK as it's likely to be low impact on other parts of the code, LGTM

**Comment by flavio** [comment]
@nathanleclaire thanks a lot!

**Comment by nathanleclaire** [comment]
:+1:

**Pull request merged**
