### PR TITLE
driver/vmwarevsphere: Fix issue #2893 creating VMs using DRS cluster

### LINKED ISSUE #2893: vmwarevsphere driver:  --vmwarevsphere-hostsystem with wildcard doesn't work
Hello,

as @doxxx previously mentioned here: https://github.com/docker/machine/pull/1522#issuecomment-126779331

I am also not able to get the

```
 --vmwarevsphere-hostsystem <cluster>/* 
```

option to work . My cluster name is "home" is this example

```
Error creating machine: Error with pre-create check: path 'home/*' resolves to multiple hosts
```

If I put a hostname instead of the wildcard it works fine.

Any idea what could be wrong?

### PR DESCRIPTION
**Pull request by ajfeatherstone**
Fixes #2893

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@frapposelli - this is beYond my vmware experience

**Comment by ajfeatherstone** [comment]
I've verified that this works using a locally built version of docker-machine using VMWare vCenter Server 6.0.0 if that helps get this merged in.

**Comment by frapposelli** [comment]
LGTM 👍

**Comment by SvenDowideit** [comment]
@shin-

**Comment by shin-** [comment]
Thanks!

**Pull request merged**
