### PR TITLE
FIX #2129 Driver name is lost in migration

### LINKED ISSUE #2129: Driver name missing on upgrade from docker-machine 0.3.1 to 0.5.0-rc4
`$ docker-machine ls`
Driver "" not found. Do you have the plugin binary accessible in your PATH?

I placed all drivers in /usr/local/bin per the release notes.  Confirmed they are seen on PATH.

Here is what docker-machine 0.5.0-rc4 did when it translated the `config.json` file:

`$ more ~/.docker/machine/machines/dev/config.json.bak`
{"DriverName":"virtualbox","Driver":{"IPAddress":"192.168.99.100","SSHUser":"docker","SSHPort":53507,"MachineName":"dev","CaCertPath":"/Users/ljrittle/.docker/machine/certs/ca.pem","PrivateKeyPath":"/Users/ljrittle/.docker/machine/certs/ca-key.pem","SwarmMaster":false,"SwarmHost":"tcp://0.0.0.0:3376","SwarmDiscovery":"","CPU":-1,"Memory":1024,"DiskSize":20000,"Boot2DockerURL":"","Boot2DockerImportVM":"","HostOnlyCIDR":""},"StorePath":"/Users/ljrittle/.docker/machine/machines/dev","HostOptions":{"Driver":"","Memory":0,"Disk":0,"EngineOptions":{"ArbitraryFlags":null,"Dns":null,"GraphDir":"","Ipv6":false,"InsecureRegistry":null,"Labels":null,"LogLevel":"","StorageDriver":"","SelinuxEnabled":false,"TlsCaCert":"","TlsCert":"","TlsKey":"","TlsVerify":false,"RegistryMirror":null,"InstallURL":""},"SwarmOptions":{"IsSwarm":false,"Address":"","Discovery":"","Master":false,"Host":"tcp://0.0.0.0:3376","Image":"","Strategy":"","Heartbeat":0,"Overcommit":0,"TlsCaCert":"","TlsCert":"","TlsKey":"","TlsVerify":false,"ArbitraryFlags":null},"AuthOptions":{"StorePath":"/Users/ljrittle/.docker/machine/machines/dev","CaCertPath":"/Users/ljrittle/.docker/machine/certs/ca.pem","CaCertRemotePath":"","ServerCertPath":"/Users/ljrittle/.docker/machine/certs/server.pem","ServerKeyPath":"/Users/ljrittle/.docker/machine/certs/server-key.pem","ClientKeyPath":"/Users/ljrittle/.docker/machine/certs/key.pem","ServerCertRemotePath":"","ServerKeyRemotePath":"","PrivateKeyPath":"/Users/ljrittle/.docker/machine/certs/ca-key.pem","ClientCertPath":"/Users/ljrittle/.docker/machine/certs/cert.pem"}}}

`$ more ~/.docker/machine/machines/dev/config.json`
{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "192.168.99.100",
        "SSHUser": "docker",
        "SSHPort": 53507,
        "MachineName": "dev",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": "",
        "StorePath": "/Users/ljrittle/.docker/machine",
        "URL": ""
    },
    "DriverName": "",
[...]

I see the manual fix but did I miss a release note about skipping from 0.3.1 to 0.5.0?

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
ping @docker/machine-maintainers 

I think this solves the empty driver issue

**Comment by nathanleclaire** [comment]
Nice one, but I'm not sure I understand the motivation.  Migrations should always go from one version to the next, so if we need to control a flow from v1 to v3 both should be updated.  Testing the path from v0 => v3 directly seems very reasonable though.

**Comment by nathanleclaire** [comment]
That said this issue seems really important so I'll take some time today to focus on fixing it.

**Comment by jeanlaurent** [comment]
this fixes #2129

**Comment by nathanleclaire** [comment]
@jeanlaurent Yeah, I understand the issue it fixes, I misspoke a bit.  "It violates the model of the migrations" is more what I meant to say than "I don't understand the motivation".

**Comment by dgageot** [comment]
@nathanleclaire I let you tale a look. The idea was to reproduce what the user sees. He's got on old config that is migrated to v3. The driver name is lost in the process

**Comment by dgageot** [comment]
Users will always migrate to the latest version. Not to an intermediate version

**Comment by nathanleclaire** [comment]
@dgageot The migration loop is meant to go from one version to the next in sequence though.  I can duplicate the bug moving from `docker-machine-0.3.1` to present and I think this solution is probably good it just needs to be split across the existing migration functions.

**Comment by jeanlaurent** [comment]
@nathanleclaire I was just referencing the issue in comment, because it was not appearing in #2129 page.

**Comment by dgageot** [comment]
@nathanleclaire good! I let you improve the fix. Here it's the week-end! :-)

**Comment by nathanleclaire** [comment]
Yep NP @dgageot have a nice week-end!

**Comment by nathanleclaire** [comment]
I've submitted a combo pull request for this

**Comment by dgageot** [comment]
@nathanleclaire Thanks

**Pull request closed without merging**
