### PR TITLE
Download ISO from file schema - file:///...

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Allow boot2docker-url arguments to take a local file as ISO. This simplifies testing of boot2docker.iso build.

### CODE REVIEW

**Comment by ehazlett** [comment]
Thanks!

Could we add some checks around if a scheme exists (I mistakenly just tried to use a path and it failed) or perhaps if `http` isn't there then attempt to fallback to file automatically?

**Comment by rickard-von-essen** [comment]
I'll update this to default to file if ```url.Scheme == nil```

I also did some testing with ```net/url.Parse``` and Windows paths on go playground and it didn't work very well with driver letters and backslashes. So someone with access to Windows should create a patch  with specific Windows path handling.

**Comment by rickard-von-essen** [comment]
Done, now also posix paths work without the ```file://``` prefix.

**Comment by ehazlett** [comment]
+1 for working without `file` scheme.  I think the last piece is the windows paths.  I will see if I can take a look.

**Comment by nathanleclaire** [comment]
This should work now in master, so I'm closing this PR.

**Pull request closed without merging**
