### PR TITLE
rebuild-ca and regenerate-certs commands

### PR DESCRIPTION
**Pull request by ehazlett**
This adds `tls-rebuild-ca` and `tls-regenerate-certs` for rebuilding the local CA cert and keys as well as generating new certificates and propagating them to the specified machines.  This should resolve issues like #531 as well as provide a mechanism to completely re-key all machines.

### CODE REVIEW

**Comment by mrevilme** [comment]
+1

**Comment by sthulb** [comment]
Perhaps this can be linked into my PR about certs/identity #688

**Comment by ehazlett** [comment]
@sthulb +1.  Right now, there isn't much to it.  It simply calls the other functions to regenerate.  I think your PR is needed for machine server.  This would temporarily give rotation capabilities and the ability to reset the TLS config on the engine (assuming you have the SSH keys).

**Comment by sthulb** [comment]
Sure, implement them how you want for now, whilst we're < 1.0 we can fiddle with command structure.

**Comment by ehazlett** [comment]
@bfirsh thoughts?  i went back and forth on the naming.  i'm not tied to them.

**Comment by jeffdm** [comment]
:+1:

**Comment by bfirsh** [comment]
A command for this would help people get out of that crappy situation, I suppose. Though I'm a bit concerned about adding this because we're not fixing the root cause of a bug.

Questions:
 - Are there any reasons why you want to rotate all of your keys, beyond fixing that bug and general good security practice?
 - Why would you want to rebuild your CA?
 - I wonder if we need both commands... If you rebuild your CA, don't you always need to regenerate your certs? If you want to rebuild all your certs, is there any harm in also rebuilding the CA?

**Comment by ehazlett** [comment]
Unfortunately, I cannot get this reproduced.  What appears to be happening is the IP SAN isn't valid for the specified cert (even though changing IPs I cannot reproduce).  I don't think there is any other way to fix this unless we set a wildcard for all access.  Perhaps this would be ok for the local drivers but I think the potential would still be there for the cloud providers too.  Take ec2 for example, you could stop and get another IP.  I don't know any other way than regenerating certificates.

General good security practice for start.  If your CA gets compromised, you would want to build a new one.  If you generate a new CA, you don't have to regenerate all certs because we store a copy of the ca and cert in the machine directory to be self-contained.  This allows for a "rolling" cert re-issue.

**Comment by bfirsh** [comment]
I think setting a wildcard hostname and verifying the exact cert is a good idea. I'm pretty sure if you don't need a CA for Docker's TLS. You can pass the host's certificate to `--tlscacert` directly and it'll verify that the host is presenting specifically that certificate.

**Comment by bfirsh** [comment]
In terms of naming, I like commands which start with verbs. So if we're having one command, I would vote `regenerate-certs`. If we're having two commands, it's a bit more complex...

**Comment by ehazlett** [comment]
Ok so for server certs we generate a wildcard?  I think it's less secure but would alleviate the issue and as long as we verify the cert I would be ok with it.

thoughts @sthulb @ggiamarchi @andrewwatson

**Comment by ehazlett** [comment]
i don't think we would want to force a regeneration of the CA as that would cause confusion I think.  I think two commands is better.

**Comment by bfirsh** [comment]
Why would you want to regenerate the CA? If that's something that doesn't happen that often, could we recommend running `rm -r ~/.docker/machine/certs; docker-machine regenerate-certs`?

**Comment by ehazlett** [comment]
I think this could be modified to only generate the CA certs if they don't exist and thus a single command would suffice.

**Comment by md5** [comment]
FYI, I don't think you can "wildcard" with an IP SAN, so you'd have to create a fake hostname/domain name for the Machine-created Docker hosts.

**Comment by md5** [comment]
> I think setting a wildcard hostname and verifying the exact cert is a good idea. I'm pretty sure if you don't need a CA for Docker's TLS. You can pass the host's certificate to --tlscacert directly and it'll verify that the host is presenting exactly that certificate.

@bfirsh Could you clarify what you mean here?

**Comment by md5** [comment]
Will Go not check that the certificate used as a trust root includes the CA extension?

**Comment by md5** [comment]
I'm pretty sure it checks for the CA extension of the asserted trust roots here: https://github.com/golang/go/blob/c2317db2f9bf9f097f0bc297004a8f581b944206/src/crypto/x509/x509.go#L593

**Comment by sthulb** [comment]
I'm ok with wildcard certs if we can generate them.

**Comment by ehazlett** [comment]
it looks like @md5 is correct.  I just tried to create some using wildcards (`*` and `0.0.0.0`) which both do not work.  It looks like we are going to have to support either detection of failed connections or the ability to re-cert as we probably cannot rely or generate hostnames for all instances.

**Comment by ehazlett** [comment]
@bfirsh so we ran into this again in irc.  i think this would be good to get in.  I think removing the CA command and defaulting to relying on removing manually would suffice for now.  thoughts?

**Comment by bfirsh** [comment]
@ehazlett :+1: that sounds great. I think a `regenerate-certs` command could be easier to understand.

Actually, come to think of it, isn't the CA generated automatically on first start if it doesn't exist?

**Comment by ehazlett** [comment]
@bfirsh correct -- if the ca/client certs do not exist, they get auto-generated on first machine create.

**Comment by ehazlett** [comment]
Closing this PR in favor of #770.  It is the exact same (which the name as `regenerate-certs`) only created against the new driver refactor for easier merge.

**Comment by sporkmonger** [comment]
FWIW, I just ran into this after running b2d via Kitematic and then spinning up two other docker-related VMs subsequently. The Kitematic-spawned b2d VM seems to have gotten a new IP in the process somehow and then `certificate is valid for 192.168.99.101, not 192.168.99.100`. Running `docker-machine regenerate-certs default` resolved successfully.

**Pull request closed without merging**
