### PR TITLE
Rename libmachine.Machine to libmachine.Provider

### PR DESCRIPTION
**Pull request by nathanleclaire**
cc @ehazlett @hairyhenderson 

This renames `libmachine.Machine` to `libmachine.Provider`

Closes https://github.com/docker/machine/issues/936

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Ergh, I've missed a few uses.  Will push them shortly.

**Comment by nathanleclaire** [comment]
OK, I think that's everything now.

**Comment by hairyhenderson** [comment]
Any reason in particular you didn't rename machine.go to provider.go? Otherwise looks great. :)

**Comment by ehazlett** [comment]
+1 for renaming `machine.go` to `provider.go`.   Otherwise looks good.

**Comment by nathanleclaire** [comment]
> Any reason in particular you didn't rename machine.go to provider.go? Otherwise looks great. :)

Because I didn't realize :)  Good catch, I will update.

**Comment by nathanleclaire** [comment]
Updated, PTAL

**Comment by hairyhenderson** [comment]
Woot. :+1:

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
