### PR TITLE
respect proxy settings for b2d downloads

### PR DESCRIPTION
**Pull request by databus23**
This fixes docker-machine with boot2docker behind a (corporate) http_proxy

### CODE REVIEW

**Comment by shawnzhu** [comment]
+1.

@ehazlett I'm curious if it's worth to customize transport of http client just because we want http connect timeout (not https) to be 5 seconds. the default transport will provide proxy support. I also found that it customize transport in docker base because of customized `tlsConfig`.

**Comment by ehazlett** [comment]
@shawnzhu i'm ok with removing the dialTimeout and use the default as long as it supported proxy (I haven't verified that).  I'm weary of a long timeout trying to reach the b2d endpoint, but I'm ok following upstream if docker does the same.

**Comment by shawnzhu** [comment]
@ehazlett According to the [http client of docker registry client](https://github.com/docker/docker/blob/master/registry/registry.go#L46), the customized parameters are:

* `DisableKeepAlive`
* `Proxy`
* `TLSClientConfig`

Plus a timeout switch on ConnectionTimeout (5 seconds) or ReceiveTimeout (1min). So you're right about keeping the timeout.

So I prefer this PR plus option `DisableKeepAlive`

**Comment by databus23** [comment]
@bfirsh Any specific reason this removed from the 0.2.0 milestone? Its a pretty low hanging fruit which improves the usability of machine in corporate networks with mandatory http_proxy considerably?

**Comment by radiumx3** [comment]
@bfirsh @ehazlett  Is this going to be implemented anytime soon ? We were about to prototype a solution based on docker machine but this is the first struggle of our long journey.
Why it has been dropped from 0.2 without any communication about it ?!

**Comment by ehazlett** [comment]
@radiumx3 @databus23 no just misclick in waffle ;)  I'm reviewing this today.

**Comment by ehazlett** [comment]
@databus23 would you mind adding the suggestions from @shawnzhu ?  I think matching the upstream docker updates would be good.

@radeksimko @databus23 are you ok with testing?  i can get a proxy setup local but having some more testing would be great.  thanks!

**Comment by databus23** [comment]
@ehazlett Do you mean adding the `DisableKeepAlive` option? Sure why not. I don't think we should add the whole `TlsClientConfig` from the registry though. I don't think the special certificate handling (/etc/docker/certs.d/...) makes sense for machine.

**Comment by databus23** [comment]
@ehazlett Oh and I'm very much ok with testing. As it stands docker-machine does not work in my corporate network because of this. :)

**Comment by sthulb** [comment]
+1 This should have been here for 0.1.0 :)

**Comment by ehazlett** [comment]
@databus23 good point.  let's leave the TLS off -- we can always add it if neeede.  thanks!

**Comment by databus23** [comment]
So I added the `DisableKeepAlive` option, rebased on master and tested that it works in my corporate environment with a mandatory http proxy.

**Comment by sirlatrom** [comment]
Please *do* add it, if that will enable me to specify e.g. a CA to use when
communicating with specific hosts. Otherwise I will not be able to use
machine...

**Comment by databus23** [comment]
@sirlatrom I don't think implementing a custom trust store for certificates is the way to go. Instead docker-machine should be using the default ca store of the operating system and if you use a self-signed certificate or custom CA it should be placed there. There is currently a bug with that at least on OSX which is tracked here https://github.com/docker/machine/issues/491

**Comment by sthulb** [comment]
I think maybe we should add it. Explicitly for the OS X bug.

**Comment by databus23** [comment]
@sthulb I would prefer a general solution to the problem as proposed in #491. This is a general problem when shipping cross-compiled (darwin) go binaries that do https communication. Adding this for the b2d download case only solves one specific case. This will come up again and again for different cases and requires to customize every `http.Transport`.
Also I don't think its a good practice  to maintain separate trust stores for https clients, they should use the system store IMO.

**Comment by databus23** [comment]
In general I think the custom certificate discussion should be moved to #491. This issue is about fixing docker-machine behind a mandatory proxy (aka in a corporate environment). It is as easy as a one line change, doesn't break anything and I would very much like it to happen fast.
Even adding the `DisableKeepAlive` option was already out of scope IMO but I went with it in the hopes of getting closer to a merge. :)

**Comment by sthulb** [comment]
You're right, I never meant it in terms of your issue, I was just voicing an opinion :)

But in general, it might be nice to add it back.

**Comment by ehazlett** [comment]
I agree with @databus23.  The cert issue is different and I don't think we want to manually manage a cert store (I am not in favor of this).

**Comment by ehazlett** [comment]
Tested with local Squid to GH for b2d -- works great.  Thanks!  LGTM

**Comment by sirlatrom** [comment]
You're absolutely right about that. I'm looking forward to trying it out in
Windows behind a corporate proxy which inserts its own certificate in the
chain.

**Pull request merged**
