### PR TITLE
Ensure that attempt to remove instance and SSH key both go through

### PR DESCRIPTION
**Pull request by nathanleclaire**
Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
@tianon @dgageot  What do you think about this? I tried to test it by deleting the instance but not the SSH key pair before attempting `docker-machine rm` and it seemed to work, but it also didn't spit any error message back at me, so I suspect the conditions resulting in dangling SSH keys might be slightly more difficult to track down.

**Comment by tianon** [comment]
If the terminate fails for some reason (lack of network connection, etc), wouldn't this mean that our SSH key is now gone and we have no way of accessing the VM anymore?

**Comment by nathanleclaire** [comment]
@tianon Indeed, but if you're requesting `docker-machine rm`, that instance is as good as gone to the user anyway, right?

**Comment by nathanleclaire** [comment]
So, to me it sort of seems like expecting to be able to salvage deleted files if UNIX `rm` were to fail for some reason.

**Comment by tianon** [comment]
Yeah, that's fair -- that makes me wonder what `rm`'s behavior is when it comes across a failure halfway through a recursive `rm`. :smile:

**Comment by tianon** [comment]
Well, that answers that:
```console
$ mkdir -p a/b/c
$ mkdir -p e/f/g
$ mkdir -p h/i/j
$ sudo chown -R root:root e
$ rm -rf a e h
rm: cannot remove ‘e/f/g’: Permission denied
$ find
.
./e
./e/f
./e/f/g
$ 
```

LGTM :+1:

**Comment by nathanleclaire** [comment]
Nice

**Comment by nathanleclaire** [comment]
> Yeah, that's fair -- that makes me wonder what rm's behavior is when it comes across a failure halfway through a recursive rm. :smile:

It doesn't just print "Oops" to STDERR and exit 1?

**Pull request merged**
