### PR TITLE
Restore provision/systemd support for docker versions <1.12

### PR DESCRIPTION
**Pull request by rifelpet**
This PR adds systemd support for docker versions older than 1.12.  At the moment if someone either uses a custom `--engine-install-url` which installs an old version of docker, or the instance already has an older version of docker installed, the provision will fail because the unit's `ExecStart` is set to `dockerd` instead of `docker daemon`. 

This checks the docker version and uses the appropriate Exec command.

For reference, this version support already exists with the [coreos](https://github.com/docker/machine/blob/master/libmachine/provision/coreos.go#L68-L94) provisioner.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Can you please take a look at the drop-in changes I just merged and see if you might need to rebase on top? Thanks!

**Comment by rifelpet** [comment]
@nathanleclaire I rebased and fixed a conflict

**Comment by nathanleclaire** [comment]
LGTM

Thanks @rifelpet !

**Comment by nathanleclaire** [comment]
I am not sure what's up with Travis. kicking off another build

**Comment by rifelpet** [comment]
@nathanleclaire Yeah I saw that it was failing but it looks like it passed now.

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
Thanks @rifelpet !

**Pull request merged**
