### PR TITLE
New navigation for 1.10 Release

### PR DESCRIPTION
**Pull request by moxiegirl**
For 1.10 we are changing the taxonomy to product-specific menus. 

image

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by dmp42** [comment]
cc @docker/machine-maintainers

**Comment by jeanlaurent** [comment]
We wrote some feedback inline. PTAL @moxiegirl

**Comment by moxiegirl** [comment]
@jeanlaurent @dgageot This PR is about changing the menus.  To @dgageot point, we should be using "Machine" in the menus consistently.  I'll update to that.  We do that here to conserve space on the menus and, well, Docker is assumed given the other clues on the website like the logo and so forth.  We do add the Docker back in on the titles for SEO.

**Comment by jeanlaurent** [comment]
@moxiegirl ok for the 3rd party driver. I'll file an issue or write it down in a PR,

**Comment by moxiegirl** [comment]
Thanks @jeanlaurent!

**Comment by moxiegirl** [comment]
@jeanlaurent @dgageot updated.  See revised screen capture.

**Comment by jeanlaurent** [comment]
LGTM

We will perform all the submitted changes that did not went through in a separate PR.

**Pull request merged**
