### PR TITLE
Add more detail to roadmap

### LINKED ISSUE #680: Add more detail around to roadmap
See original: https://github.com/docker/machine/blob/dcf6c780113d888049121c6312aaaaa0db80691c/ROADMAP.md

It would be nice if the roadmap had a narrative which explained some background, what high-level things are needed, some reasoning behind them, then linked off to specific features which satisfy them.

### PR DESCRIPTION
**Pull request by bfirsh**
There's now a bit of a narrative to explain the why, then some links off to GitHub issues explaining the how.

Closes #680

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@bfirsh off-topic: is there a plan for creating multiple docker hosts (or a predefined topology) at once with single `machine create` command? this can help a great deal in "swarm" story. if so, it might be better to have it in the roadmap I guess.

**Comment by thaJeztah** [comment]
@ahmetalpbalkan like this: https://github.com/docker/machine/pull/715?

**Comment by ahmetalpbalkan** [comment]
@thaJeztah yeah, I guess. :-)

**Comment by bfirsh** [comment]
@ahmetalpbalkan Imagine something like this:

    $ docker-machine swarm create -d digitalocean --size 20 myswarm

**Comment by ahmetalpbalkan** [comment]
@bfirsh any plans for leveraging built-in resource template systems of cloud providers? I guess GCP has something and Azure one is in beta, gonna come out soon. With those template engines you can just issue a template saying I need 20 instances of this and the cloud service will take care of the rest for you.

**Comment by nathanleclaire** [comment]
@ahmetalpbalkan Would that be different from "pre-baking" the machine images?  Do you have a link to some documentation on such a facility as an example?

**Comment by nathanleclaire** [comment]
@bfirsh I like the greater level of detail and explanations, but I would prefer to keep the checkboxes as a quick and concise reference.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire we do have several methods to do that on Azure (e.g. you can come as an ISV to our marketplace, add your stock image and people can deploy using that, just like pre-baked distro images). I can connect you folks with our PMs to figure that out.

However, we are planning to support "create `N` VMs with this configuration and run these commands on startup (i.e. docker installation steps)" on Azure as our new API set is going to be released very soon.

The real-world use case of swarm clusters on Azure will probably contain some extra details in topology like "affinity groups" (which places VMs in spatially close racks/clusters in DC) and "virtual networks" which makes instances talk to each other safely in a VLAN. In the long term we must support these stuff from docker-machine as well since they're most likely gonna come as feature requests anyway, but I can't really do much at this point because the APIs are new and there's some time for them to go GA.

**Comment by bfirsh** [comment]
@nathanleclaire We can add items to the lists roadmap that are specific things we're working on to satisfy the high-level goals. For smaller things and general tech tasks, I think issues work much better than checkboxes in a static document.

See also Compose's roadmap: https://github.com/docker/compose/blob/master/ROADMAP.md

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
