### PR TITLE
Add support for VMware Workstation to Fusion driver

### PR DESCRIPTION
**Pull request by cab105**
Signed-off-by: Christopher A. Baumbauer <cab@cabnetworks.net>

### CODE REVIEW

**Comment by cab105** [comment]
This is to resolve issue #3868.

**Comment by StefanScherer** [comment]
I think it would be better to have a `vmwareworkstation` driver instead of using the `vmwarefusion` driver for VMware Workstation. For Windows VMware Workstation there is an external driver plugin at https://github.com/pecigonzalo/docker-machine-vmwareworkstation/, maybe you should start something similar for Linux. An external plugin has the advantage that you don't have to wait until the driver plugin got merged into core codebase.

**Comment by cab105** [comment]
Perhaps, but this would result in a lot of duplicate code between the Fusion
and Linux workstation driver which is why I moved the files back away from the
arch specific naming convention.

The modification itself is mainly adding arch switches to tell the driver to
look in /etc instead of /Library for the vmware specific network configs, and
/usr/bin instead of /Applications/VMWare\ Fusion.app for vmrun.

Windows Workstation is a completely different beast, and is one I'm not too
familiar with overal.

**Comment by nathanleclaire** [comment]
@cab105 

> Perhaps, but this would result in a lot of duplicate code between the Fusion
and Linux workstation driver which is why I moved the files back away from the
arch specific naming convention.

Did you consider writing a driver plugin that embeds the existing workstation driver? e.g. (totally spitballing this code),

```go
package vmwareworkstation

import "github.com/docker/machine/drivers/vmwarefusion"

type Driver struct {
    vmwareFusion.Driver
}
```

You could re-use a lot of the methods, and just "over-ride" the methods you want to change.

**Comment by nathanleclaire** [comment]
At any rate, we're unable to accept new plugins in the core right now.  Thanks for the contribution @cab105 , my suggestion would be to make and distribute a `docker-machine-driver` plugin

**Pull request closed without merging**
