### PR TITLE
Move closures to be named functions

### PR DESCRIPTION
**Pull request by nathanleclaire**
This will make them easier to test and the file easier to read.

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Hm, maybe they should be like `cmdStart` instead?  There's no reason they might be exported.

**Comment by ehazlett** [comment]
@nathanleclaire +1 for unexported.  I don't see why they would need to be either.

**Comment by nathanleclaire** [comment]
K, changed to unexported

**Comment by ehazlett** [comment]
test fails

**Comment by nathanleclaire** [comment]
Heh, accidentally duplicated a function.  Fixed

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
