### PR TITLE
Lint, second pass

### PR DESCRIPTION
**Pull request by dmp42**
@nathanleclaire this one is more involved than the first.

I would like to sit with you and review it four hands to make sure this is gold. 

Note that this also enable `make lint` by default on test and on CI.

### CODE REVIEW

**Comment by dmp42** [comment]
Build is successful locally. Travis is perplexing.

**Comment by dgageot** [comment]
@dmp42 Can you please rebase?

**Comment by dmp42** [comment]
Yeah my bad.
And I added no-cache to try to force travis to refresh, but that shouldn't be required.

**Comment by nathanleclaire** [comment]
It looks pretty good.  I see nothing which seems unreasonable.  LGTM

**Comment by dmp42** [comment]
Thanks @nathanleclaire 

I believe doing this sooner than later is important - we may trigger a few bugs, but better now that when drivers are being outsourced.

**Comment by nathanleclaire** [comment]
Yes my reasoning is that I gave it a sweep and everything seems safe, if we run into issues it will likely be before 0.5.1 and if any come up after it won't be too long to get a patch out to fix them.

**Pull request merged**
