### PR TITLE
Added a remote-build script that streams tgz'ed binaries to stdout

### PR DESCRIPTION
**Pull request by saturnism**
Signed-off-by: Ray Tsang <saturnism@gmail.com>

### CODE REVIEW

**Comment by ehazlett** [comment]
I like this idea!  Do you think we could merge this into the existing build script as an option or something?

**Comment by saturnism** [comment]
ehazlett - sure! I can take a look at that.

Before I make modifications though, here is the thought on what it may look like... Any preferences?

Regular build:
```
    $ script/build 
```

Remote build:
```
    $ script/build -r
```
Or, generically, output binaries in tgz format?
```
    $ script/build -o
    $ script/build -
````

**Comment by sthulb** [comment]
Without looking over the changes, what's the behaviour? Output all binaries in one tgz or each in tgz format?

**Comment by saturnism** [comment]
it will output all the binaries in one tgz

**Comment by saturnism** [comment]
quick ping

**Comment by nathanleclaire** [comment]
Definitely want to support this - we are in a bit of a shuffle to get some stuff in right now, but soon I want to integrate this style of build into a `make remote` option or otherwise.

**Comment by ehazlett** [comment]
Thanks for the follow up. I think a -r option would work for now. Thanks!

**Comment by nathanleclaire** [comment]
We've added this in a slightly different way now, thanks!

**Pull request closed without merging**
