### PR TITLE
save configuration even if vm creation failure

### PR DESCRIPTION
**Pull request by TrumanLing**
1.save configuration even if vm creation failure
 2.delete local storage without -f option if server create return err

### CODE REVIEW

**Comment by ehazlett** [comment]
Can you explain the issue this is solving?

**Comment by TrumanLing** [comment]
@ehazlett add field ```CreateCmdReturnErr``` to check status of command ```server.Create```, if command return error, OpenStack nova service doesn't issue instruction to create instance, but it creates local storage for this creation, so add code ```h.SaveConfig``` to store ```error return``` of creation, it is convenient to make ```force delete```  when issuing ```rm``` command in source code, even though it can be manually ```rm``` with option ```-f```.
In addition,  code ```h.SaveConfig``` can store ```instance id``` when command ```server.Create``` return successfully but OpenStack nova service failed at period of implementing code ```d.waitForInstanceActive```, in such case, if no ```instance id``` is stored, it will return ```itemNotFound (404)``` when issuing ```ls``` and ```rm``` or other command, at least storing ```instance id``` makes consistence between local storage and remote OpenStack.

**Comment by TrumanLing** [comment]
@ehazlett PTAL

**Comment by ehazlett** [comment]
@nathanleclaire wdyt?

**Comment by nathanleclaire** [comment]
-1

1. We can't merge anything in which isn't fully implemented
2. The `Driver` interface is way overloaded already
3. Saving config is already over-done and I don't want to keep piling on more stuff.  Config should be saved when the instance is created, and it's why we have made a concentrated effort to exit from the `Create` call as soon as possible (when the relevant bits e.g. instance ID have been filled in).  We haven't updated all the drivers, though, and some still do things like poll for state or IP address that they don't need to.
4. An `error` implies that `Create` failed, not succeeded.  If it succeeded but didn't exit `Create` for whatever reason, the `Create` method should exit sooner.

**Comment by nathanleclaire** [comment]
I'm going to close this, but feel free to open a proposal in the issues detailing the specific problem you are trying to solve and how.

**Pull request closed without merging**
