### PR TITLE
ec2 Don't force user to use VPC_ID but use the default one when available

### PR DESCRIPTION
**Pull request by jeanlaurent**

### CODE REVIEW

**Comment by jeanlaurent** [comment]
Removed duplication you hinted @dgageot ( it was dead code left during refactoring) and extracted a few errors.

**Comment by dgageot** [comment]
@jeanlaurent I still see the duplication

**Comment by jeanlaurent** [comment]
Yeah duplication was added in 0d2bc08 and removed in e37fcb5.
Now all is done in  0d2bc08...

**Comment by dgageot** [comment]
LGTM

**Pull request merged**
