### PR TITLE
Revert "Bump version for 0.8.0"

### PR DESCRIPTION
**Pull request by nathanleclaire**
This reverts commit 324f31ea4b9486a97ad928f81b6527e2fa239842.

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire I'm trying to understand this commit

**Comment by nathanleclaire** [comment]
Careful, you might hurt your brain.

It's less weird than it looks -- essentially, I made a mistake in the 0.8.0 release because out of old habit I submitted a bump branch PR, forgetting that our release script takes care of this change automatically (whether or not it _should_ do that is another matter entirely, but it's what we're working with for now).  Since the release script was failing trying to change this value when it was already `0.8.0` and blocking the completion of the release, easiest solution was just to revert my bump PR.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire people think the code they compile off of master is 0.7.0. https://github.com/docker/machine/issues/3656#issuecomment-240065242

**Comment by nathanleclaire** [comment]
Yeah I guess the release automation also has a bug where it does not commit and/or push the `0.8.0` change.  We should re-do this change and meanwhile I'll look into fixing the janky release code.

**Pull request merged**
