### PR TITLE
Update docs usage and output

### PR DESCRIPTION
**Pull request by nathanleclaire**
cc @ehazlett 

Updated usage and output where I saw fit for the 0.3.0 release.

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by ehazlett** [comment]
LGTM

**Comment by ehazlett** [comment]
@moxiegirl PTAL

**Comment by ehazlett** [comment]
Merging as this is aesthetic changes and is required for release.

**Comment by nathanleclaire** [comment]
+1 Thanks @ehazlett

**Pull request merged**
