### PR TITLE
Fix boot2docker import regression

### PR DESCRIPTION
**Pull request by nathanleclaire**
Closes https://github.com/docker/machine/issues/2153

cc @docker/machine-maintainers 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by dgageot** [comment]
LGTM

**Comment by pditommaso** [comment]
I'm getting the same problem. Is there any patch or workaround available?

**Comment by dgageot** [comment]
@pditommaso Did you test with this PR?

**Comment by pditommaso** [comment]
No. Mainly because I've no clue how to do that.

**Comment by wckao** [comment]
Is the bug supposed to be fixed in docker-machine 0.5.1 which is supposed to be released in toolbox 1.9.0d?  I just downloaded 1.9.0d Mac version, and it included docker-machine 0.5.0 instead of 0.5.1 as stated on https://github.com/docker/toolbox/releases.

**Comment by mkempf** [comment]
Same here on windows. I just downloaded 1.9.0d Windows version, and it included docker-machine 0.5.0 instead of 0.5.1 as stated on https://github.com/docker/toolbox/releases.

**Comment by nathanleclaire** [comment]
Docker Machine 0.5.1 should fix this issue but isn't out yet.  It seems to be a typo on the Toolbox release.

**Pull request merged**
