### PR TITLE
Filter openstack floating IPs by tenant ID

### PR DESCRIPTION
**Pull request by boyvinall**
Merge j2sol:filter-openstack-floating and fix up for comments in PR #1809.

Signed-off-by: Matt Vinall <matt.vinall@imgtec.com>

### CODE REVIEW

**Comment by GonZo** [comment]
:+1:

**Comment by dgageot** [comment]
cc @ggiamarchi please take a look.

**Comment by dgageot** [comment]
Otherwise LGTM

**Comment by jeanlaurent** [comment]
LGTM

**Comment by j2sol** [comment]
Thanks for picking this up, I hadn't had a chance yet.

**Comment by boyvinall** [comment]
No worries dude. Same thing bit me. Happy to help :)

**Pull request merged**
