### PR TITLE
Add COMPOSE_CONVERT_WINDOWS_PATHS to `docker-machine env` output

### PR DESCRIPTION
**Pull request by shin-**
See related Compose change for context: https://github.com/docker/compose/pull/4026

This is my first contribution to machine (the shame!), so this might be a little rough around the edges.

Also, I tried to add some tests for this, but with the dependency on `runtime.GOOS` I'm not quite sure how to do that. Appreciate any guidance!

### CODE REVIEW

**Comment by nathanleclaire** [comment]
`runtime.GOOS` is public (exported) so you can just set it and set it back in the test probably

**Comment by nathanleclaire** [comment]
this might break the existing tests when run on windows anyway though...

**Comment by shin-** [comment]
Added test and updated the existing tests to make sure they don't break on Windows.

**Comment by nathanleclaire** [comment]
Oh yeah, cool, this solution seems pretty good.  Joffrey on beast mode with these tests

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
