### PR TITLE
Linting 2

### PR DESCRIPTION
**Pull request by dmp42**
Everything but libmachine & drivers (except inline documentation).

Is on top of the drivers cleanup.

### CODE REVIEW

**Comment by dmp42** [comment]
On-top of #2074

**Comment by dmp42** [comment]
Second step to fix #1887 

See https://github.com/docker/machine/pull/2074#issuecomment-150729020 for context

**Comment by dgageot** [comment]
LGTM

**Comment by dgageot** [comment]
@dmp42 Can you rebase please?

**Pull request closed without merging**
