### PR TITLE
update roadmap for 0.4.0

### PR DESCRIPTION
**Pull request by ehazlett**
The next release we want to focus on stability and improvements to the local providers.  These are the focus points:

* Finalize Boot2Docker Migration (OS)
* Provisioning Stability (error reporting, re-provisioning existing hosts)
* Local Provider Improvements (make VirtualBox, Fusion, Hyper-V extremely stable)

### CODE REVIEW

**Comment by sthulb** [comment]
+1 I can get behind this :)

**Comment by hairyhenderson** [comment]
Nice and focused - LGTM!

**Comment by nathanleclaire** [comment]
:+1: 

Some specific callouts I'd like to see (might fill in more as I remember them):

- OSX/Windows installer (preferably unified with KM / Compose etc.), like what b2d has today
- Improved per-driver logging.  I'd like to see a structure where machine operations log their debug output to the relevant folder on disk, whether or not they are displayed to the terminal when they are happening, and can be queried later with something like a `docker-machine logs dev` command.

**Comment by ehazlett** [comment]
@nathanleclaire +1

**Comment by nathanleclaire** [comment]
Another:

- A command (or script) which will generate information about the host system and environment for debugging purposes, similar to the one that Docker has.

**Comment by efrecon** [comment]
This focuses on stability and this is good. If you were to consider new features, I would suggest a way to specify labels to attach to created machines so that swarm can make use of these labels for orchestration.

**Comment by nathanleclaire** [comment]
> This focuses on stability and this is good. If you were to consider new features, I would suggest a way to specify labels to attach to created machines so that swarm can make use of these labels for orchestration.

@efrecon I'm not sure if this is exactly what you're after, but in Machine master today you can use `--engine-label` to do this, e.g.:

```console
$ docker-machine create -d amazonec2 --engine-label disk=ssd --engine-label size=micro foobar
```

It will set the labels on the Docker daemon, you should be able to see them using `docker info`.

**Comment by efrecon** [comment]
Thank you @nathanleclaire ! It is what I was looking for, I had missed that option, so disregard my comment...

**Pull request closed without merging**
