### PR TITLE
Adding --format/-f option to inspect subcommand

### PR DESCRIPTION
**Pull request by hairyhenderson**
This is inspired by docker's `inspect --format` flag.

For example:

```
$ machine inspect -f "{{json .HostOptions.EngineOptions}}"
{"Dns":null,"GraphDir":"","Ipv6":false,"Labels":null,"LogLevel":"","StorageDriver":"","SelinuxEnabled":false,"TlsCaCert":"","TlsCert":"","TlsKey":"","TlsVerify":false,"RegistryMirror":null}
```

Or:

```
$ machine inspect -f "{{prettyJSON .Driver}}"                   
{
    "MachineName": "dev-fusion",
    "IPAddress": "172.16.62.129",
    "Memory": 1024,
    "DiskSize": 20000,
    "CPUs": 8,
    "ISO": "/Users/hairyhenderson/.docker/machine/machines/dev-fusion/boot2docker-1.5.0-GH747.iso",
    "Boot2DockerURL": "",
    "CaCertPath": "/Users/hairyhenderson/.docker/machine/certs/ca.pem",
    "PrivateKeyPath": "/Users/hairyhenderson/.docker/machine/certs/ca-key.pem",
    "SwarmMaster": false,
    "SwarmHost": "tcp://0.0.0.0:3376",
    "SwarmDiscovery": "",
    "CPUS": 8,
    "SSHUser": "docker",
    "SSHPort": 22
}
```

~~:warning: some stuff that seems like it should work doesn't:~~
```
$ machine inspect -f "{{.Driver.IPAddress}}"   
FATA[0000] template: :1:9: executing "" at <.Driver.IPAddress>: can't evaluate field IPAddress in type drivers.Driver 
```

~~This is because `IPAddress` isn't part of the `drivers.Driver` interface, so technically it makes sense, but it's probably going to be surprising to users. I'm not totally sure how to handle this, but I have a vague idea. I'm open to suggestions :)~~

**Update:** This works now:
```
$ machine inspect -f "{{.Driver.IPAddress}}"   
172.16.62.129
```

### CODE REVIEW

**Comment by sthulb** [comment]
I guess for the IP address stuff you'd have to dynamically add the IP address from `GetIP` to the JSON.

I'm unsure about adding a testing lib though.

**Comment by hairyhenderson** [comment]
@sthulb - hrm, yeah. I was thinking I could also `json.Marshal()`/`json.Unmarshal()` - that might work too.

re: adding the `testify` dependency, @ehazlett mentioned he was OK with that last night. Any specific reason this would be a bad idea? Seems to me making it easier to write tests would be a bonus, given the current state of coverage :)

**Comment by sthulb** [comment]
My  issue  is that 2% of tests are  using it :) I guess another PR converting the 98% is needed

**Comment by ehazlett** [comment]
This seems pretty good.  I cannot get the IP though.  Returning `<no value>` for me for a running machine.

**Comment by ehazlett** [comment]
ping @hairyhenderson

**Comment by hairyhenderson** [comment]
@ehazlett - Hmm. I must've been testing with vmware-fusion and not virtualbox. I can see it with fusion, but I also see `<no value>` with virtualbox. Though I can't see the IPAddress at all with the vanilla `machine inspect`, so maybe something's up with the virtualbox driver... I'll dig into it :)

**Comment by hairyhenderson** [comment]
We've chatted a bit about this in IRC, but the short story is - virtualbox.Driver doesn't actually _have_ a IPAddress field, so it's totally expected behaviour...

**Comment by ehazlett** [comment]
Ah ok this makes sense.  I think it will be odd though to have some drivers return IPs and some not.

**Comment by hairyhenderson** [comment]
@ehazlett - true. but I think that's more something that should be harmonized among all the drivers... This PR is really just about templating the `inspect` output...

**Comment by ehazlett** [comment]
@hairyhenderson valid point.  LGTM

**Comment by ehazlett** [comment]
ping @nathanleclaire

**Comment by hairyhenderson** [comment]
Ok, this is rebased after #923 - PTAL @ehazlett & @nathanleclaire :)

**Comment by ehazlett** [comment]
LGTM

**Comment by nathanleclaire** [comment]
Just a few things:

1. Can we please call the function `prettyjson` instead of `prettyJSON`?  I think it would be slightly more idiomatic for Go template functions.
2. After discussion, @ehazlett and I are both OK with the introduction of the additional testing library, but in the future please introduce such a dependency in a separate PR with a proposal (it doesn't have to be big and elaborate, just some motivations and potential concerns).

**Comment by hairyhenderson** [comment]
@nathanleclaire - sure, I'll rename `prettyJSON` to `prettyjson`.

No problem - wasn't totally sure about how to go about introducing a dependency. A separate PR makes a lot of sense - will do that in future :)

Thanks!

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
