### PR TITLE
driver doc updates

### PR DESCRIPTION
**Pull request by ehazlett**
This updates the driver docs with the latest changes and an overview on driver creation and integration.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
If we update the Driver interface in the future (likely) we'll have to also update this document, so perhaps we should link to the relevant file instead (at least for the interface bits).

I think I'd also introduce the interface first, and then follow up with a small explanation that "And in order to provide this functionality most drivers end up as a struct that implements these methods with parameters similar to the following", since it's not strictly necessary to have those exact fields.  

Also, tangentially, since those fields are very common, we could probably provide a `struct` that drivers can embed which has them like you mentioned in that one issue, and recommend that as a way to keep things consistent across drivers.

**Comment by ehazlett** [comment]
Yeah I was going to just have the link but then figured it would be good to have the docs in one place.  I'll update to just have the link as our docs are out of sync now in places and I'm sure this would get worse.

I like the idea of embedding too.  I will leave that out of this doc update though.

Thanks

**Comment by ehazlett** [comment]
@nathanleclaire This has been updated - PTAL

**Comment by nathanleclaire** [comment]
LGTM thanks for doing this.  I want to do some focusing on docs today as well.

**Comment by ehazlett** [comment]
Thanks

**Pull request merged**
