### PR TITLE
Driver for Boot2Docker Hyper-V

### PR DESCRIPTION
**Pull request by jeffmendoza**
Works with my custom boot2docker.iso with ident auth, see https://github.com/MSOpenTech/machine/compare/hyper-v?expand=1#diff-235ba5d4b413618fd451b3ac9da1d110R419

Requires a docker client with ident auth, as all of machine does atm.

I'm starting to merge code between this driver and virtualbox into common b2d functionality.

I'm thinking this could be built-in only for the Windows build of machine, makes sense? I can't think of a way this could be used in a Mac or Linux binary.

### CODE REVIEW

**Comment by ehazlett** [comment]
@jeffmendoza just wanted to give an update here.  we are working on our integration test suite.  once we have a way to test hyper-v we will work on getting this merged.  thanks!

**Comment by jeffmendoza** [comment]
@ehazlett Thanks, I'll rebase and make sure everything is still working.

**Comment by jeffmendoza** [comment]
@ehazlett @bfirsh Fully rebased and up to date with TLS auth. Can we get this in for 1.0?

**Comment by ehazlett** [comment]
We won't be able to get this in for the 0.1.0 since it was after our freeze.  We should be able to get it in in the next round.

I will also start testing this against my Hyper-V installation as well.

Thanks!

**Comment by jeffmendoza** [comment]
@ehazlett This is really rough, considering we've had this open for 56 days now, not counting the time it was open against hosts, before machine existed. Is there anything I can do to help get it in?

**Comment by ehazlett** [comment]
@jeffmendoza hey -- sorry about this.  i wasn't aware this driver has this much history.  let me see what we can do.

**Comment by ehazlett** [comment]
I have rebased against the latest master here: https://github.com/ehazlett/machine/tree/hyper-v

First run I am getting `Error creating  machine: no vswitch found`

**Comment by ehazlett** [comment]
Ok so after going through the NAT creation exercise, I can confirm this is working.  Perhaps we should link this in the documentation? @jeffmendoza thoughts?

**Comment by jeffmendoza** [comment]
Yes, I documented the '--hyper-v-virtual-switch' option in the readme, but adding a note that you need to have an existing one would be great.

**Comment by ehazlett** [comment]
@jeffmendoza could you check that branch above (or optionally rebase yourself -- i did it to save you some work -- there was a few changes to the b2d stuff - your attribution is still there :) ).  i also added the note to the readme.  in the future i think it would be better to do a check but this should suffice for now.

**Comment by jeffmendoza** [comment]
Yes, I checked over your branch, looks great, thanks for the rebase.

**Comment by ehazlett** [comment]
Closing this one in favor of the rebase (as @jeffmendoza approved): #493

**Pull request closed without merging**
