### PR TITLE
Fixing Filestore.GetActive to handle the case where `--swarm` is used

### LINKED ISSUE #1136: New active host tracking does not support swarm / master node
Because we query the URL directly, the new active host tracking does not match `<masterIp>:3376` correctly (the URL returned for that instance uses port `2376`).  It should support tracking the active master node if present and set as "active" with `env --swarm`, although I am not sure how to do so in a non-hacky way at the moment (obviously the inelegant solution is to replace `2376` with `3376` in the URL, and check if that matches).

### LINKED ISSUE #1311: `docker-machine active` can't find active when `env --swarm` was used
Business as usual:

```console
$ eval "$(machine env hairyhenderson)"
$ docker-machine active                      
hairyhenderson
```

But when I add `--swarm` to the mix:

```console
$ eval "$(docker-machine env --swarm hairyhenderson)"
$ docker-machine active
Error getting active host: Active host not found
```

### PR DESCRIPTION
**Pull request by hairyhenderson**
Fixes #1311 and fixes #1136

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by hairyhenderson** [comment]
Note - this is _vaguely_ (but not directly) related to #1253...

**Comment by nathanleclaire** [comment]
I'm -1 on this.  The URL is a "first order" reference to what you are hitting when you run Docker commands - if the URL matches you _know_ that is the "active" host.  The name is "second order" and could lie to you - consider this type of situation:

```console
$ docker-machine create -d virtualbox dev
... yay ...
$ eval $(docker-machine env dev)
(dev) $ docker-machine stop dev; docker-machine rm dev
(dev) $ docker-machine create -d virtualbox dev
(dev) $ docker-machine active 
dev
(dev) $ # It's a lie, DOCKER_HOST does not point to "dev".
```

**Comment by hairyhenderson** [comment]
@nathanleclaire - ahh... I hadn't thought of that.

Ok, I'll rework this to fix the problem in a better way.

**Comment by hairyhenderson** [comment]
Ok, reworked. Changed title of PR to reflect what's actually going on.

**Comment by hairyhenderson** [comment]
So, over the past couple months, this PR is totally busted. But the latest `master` _still_ exhibits the problem from #1311 and #1136:

```console
$ eval "$(docker-machine env --swarm vbox-swarm-master)" 
$ docker-machine active
Error getting active host: Active host not found
```

I'm going to rebase and reimplement the fix.

**Comment by hairyhenderson** [comment]
Actually, I'm going to open a brand new PR for this - the rebasing is super ugly.

**Pull request closed without merging**
