### PR TITLE
IRC Req: EC2 IAM Instance Profile

### PR DESCRIPTION
**Pull request by sthulb**
Signed-off-by: Simon Thulbourn <simon+github@thulbourn.com>

### CODE REVIEW

**Comment by ehazlett** [comment]
Thanks!

I am getting a `403` error when trying to use this with an IAM profile with full access.  Is there something else that needs to be done?

Also, can you update the readme?

**Comment by diginc** [comment]
Thanks!  Works for me, the EC2 was created with a limited IAM Role that I created separately.  Used AWS Access/Secret of a full privileged account.

**Comment by sthulb** [comment]
@ehazlett I make no guarantee the role has permissions, just that it can be associated with an instance :) 

I'll update the readme.

**Comment by sthulb** [comment]
@ehazlett Ready now :)

**Comment by ehazlett** [comment]
Sure I was just trying to test it and was only getting fails :)

**Comment by sthulb** [comment]
Role 
```json
{
    "Role": {
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": "sts:AssumeRole",
                    "Principal": {
                        "Service": "ec2.amazonaws.com"
                    },
                    "Effect": "Allow",
                    "Sid": ""
                }
            ]
        },
        "RoleId": "AROAJAGZD3BHC6K442VHI",
        "CreateDate": "2015-02-01T19:09:54Z",
        "RoleName": "docker-machine",
        "Path": "/",
        "Arn": "arn:aws:iam::696338148343:role/docker-machine"
    }
}
```

**Comment by diginc** [comment]
I noticed this did not make it into the beta release.  Integration with other AWS services such as CodeDeploy (among others) is impossible without this feature.

**Comment by ehazlett** [comment]
It needs a rebase

**Comment by sthulb** [comment]
@ehazlett Rebased and ready to go!

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
