### PR TITLE
Factoring Bats tests

### PR DESCRIPTION
**Pull request by vincentbernat**
Hey!

I noticed that many driver Bats tests are just copy/paste of another one. I wanted to factor them to avoid divergence between tests. The first commits are just a normalization step for the last commit. Unfortunately, I understood how Bats work only at the end (when I wanted to test the changes): it uses a preprocessing phase to replace the `@test` markers, so it is currently not possible to put common tests into another file. I have opened an issue about this: https://github.com/sstephenson/bats/issues/99

Until there is a solution, this PR is useless. I just push it here for reference, in case there is a workaround. Feel free to close it if you don't like unresolvable PR to hang around.

### CODE REVIEW

**Comment by ehazlett** [comment]
@vincentbernat yeah i tried the same thing :)  Thanks for the PR -- hopefully we'll get inclusion and can remove the boilerplate. Thanks!

**Comment by nathanleclaire** [comment]
I think that we might be able to make this type of thing work if we wrapped the calls to bats with our own script.  Discussion: https://github.com/sstephenson/bats/issues/100

E.g., `test/integration/run.sh virtualbox`, would set the `NAME` and `DRIVER` environment variables based on `$1`, and then call `bats b2dcommon.bats` which contains common tests.

**Comment by ehazlett** [comment]
@nathanleclaire what does this mean for #1158?

**Comment by vincentbernat** [comment]
@ehazlett don't bother with this PR, I'll check the other PR when it is done.

**Comment by ehazlett** [comment]
Thanks!

**Pull request closed without merging**
