### PR TITLE
Add XenServer driver for docker machine

### PR DESCRIPTION
**Pull request by phusl**
The PR adds a Docker Machine driver for XenServer. The driver implements all standard interfaces and thereby enables the management of machines on XenServer hosts.

In a nutshell:
* The driver downloads a boot2docker.iso from
  github.com/xenserver/boot2docker. (Note: We already submitted a
 boot2docker PR with XenServer tools support here:
  https://github.com/boot2docker/boot2docker/pull/935).
* The driver imports the boot2docker.iso as the primary virtual disk.
* The driver generates an ssh-key-tarball with the "boot2docker,
  please format-me" magic header and uploads this as the second
  virtual disk machine.
* Upgrades are currently not supported due to the custom ISO until https://github.com/boot2docker/boot2docker/pull/935 is accepted.

Would appreciate feedback, questions, testing/review, error-reports - and a merge, once it's proven.

Signed-off-by: Phus Lu <phus.lu@citrix.com>

### CODE REVIEW

**Comment by phusl** [comment]
For make review easier, I separated this  PR to 2 commits, the top commit is XenServer driver code change and the following commit is for Gedeps files.

**Comment by Tebro** [comment]
+1 :thumbsup:

**Comment by ehazlett** [comment]
Hi , thanks for your efforts and persistence in submitting this driver. We are extremely excited that there is so much interest in Docker Machine and we really appreciate your interest. However, at this time it is proving to be extremely difficult for us to keep up with reviewing and testing each of these drivers for inclusion in the Machine core. We really want to switch to a more pluggable model, as well as polish up a few things about the driver model which need to be changed to ensure a smooth and sustainable future.

Therefore, we will be moving to a plugin model for 0.5 and would love to have you involved in the design and development process. We are closing the outstanding driver PRs at this time, but please keep the code. We will stick closely to the current driver interface and you should be able to re-use a lot (if not all) of the existing driver along with the new plugin model. We will be moving all of the drivers which are merged directly into Machine today to the plugin model when it is available, so there will be no special treatment of those, and there will be documentation outlining the process of developing and using a Docker Machine driver plugin.

With all of that being said, we want to apologize for the lack of feedback on your pull request. As contributors ourselves, we understand that being left in limbo is no fun. We would have liked to address this sooner, and in the future we will be more responsive around these kinds of issues.

Once again, we thank you for the contribution and the tremendous support. Keep hacking strong!

If you want to contribute to the design of the plugin model, we'd love to get your input on this issue where we will be planning it:

https://github.com/docker/machine/issues/1626

@ehazlett & @nathanleclaire

**Comment by phusl** [comment]
@ehazlett
Thank you for your reply.
It makes sense to me and I'm happy to move the driver codes to the coming plugin model.
If any announce about it, please notify me. Thanks again!

**Pull request closed without merging**
