### PR TITLE
Change host restart to use the driver implementation

### PR DESCRIPTION
**Pull request by dgageot**

### CODE REVIEW

**Comment by dgageot** [comment]
That's a follow up to https://github.com/docker/machine/pull/2225

**Comment by jeanlaurent** [comment]
Shouldn't we change restart for most driver then ?

**Comment by dgageot** [comment]
I've tested `virtualbox`, `digitalocean`, `vmwarefusion`, `google` and `generic`. I've reviewed the other drivers and the code seems to make sense.

**Comment by jeanlaurent** [comment]
Yeah did the same, the thing is, before we merge this PR, there is probably no-one beside a few hypothetic integration tests which did run this code. Code looks right but...

**Comment by jeanlaurent** [comment]
LGTM

**Pull request merged**
