### PR TITLE
Add support for Linode driver.

### PR DESCRIPTION
**Pull request by taoh**
Signed-off-by: Tao Huang <taohms@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
@taoh  Please add the `github.com/taoh/linodego` dependency to `Godeps` when you get a chance.  If you need help doing so feel free to ping myself, @ehazlett, or @bfirsh.

**Comment by ehazlett** [comment]
@taoh thanks!  as nathanleclaire said, could you add the dependency to the godeps?  I'll test this soon too.  Thanks again for the contribution!

**Comment by taoh** [comment]
Will do. I'm currently out of country so this will take about 2-3 more weeks.

**Comment by ehazlett** [comment]
np thx!

**Comment by taoh** [comment]
@ehazlett Could you lend me some help with regards to amend commit 924157a with Sign-Off message? I pushed the commit without being properly signed to my forked repo, and now it seems that I cannot change it anymore. Tried `git rebase -i` to no avail. :( Otherwise, the linode driver should be up to date. Thanks in advance!

**Comment by ehazlett** [comment]
@taoh i believe you can `git rebase -i -s`

**Comment by nathanleclaire** [comment]
@taoh You will also need to `git push -f` (be careful!) to your remote once you have everything tidy and signed locally.  You might want to consider squashing those commits into one with `git rebase` before signing as that might make your life easier (just one commit to keep track of and sign).

**Comment by taoh** [comment]
Thanks @ehazlett @nathanleclaire . I managed to squash the extraneous comments and pushed to my repo. Travis failed with coverage tests for the driver though there are no tests at all. Is it because the pull request isn't merged to the main repo?

**Comment by ehazlett** [comment]
@taoh you need to add a `drivers/linode/linode_test.go` for coverage to work - and ideally, some tests ;)

**Comment by ArturSoler** [comment]
What's the current status of this PR?

**Comment by jebenexer** [comment]
bump

**Comment by cmosetick** [comment]
I have an upcoming project that requires a UK presence. `docker-machine` deployment option into Linode would be very helpful. @ehazlett Please leave me some suggestions for how I can help out with testing to get this properly integrated into the next release.

**Comment by kulbida** [comment]
any ETA on when we will have this feature?

**Comment by michaelsbradleyjr** [comment]
bump

**Comment by ehazlett** [comment]
Hi , thanks for your efforts and persistence in submitting this driver. We are extremely excited that there is so much interest in Docker Machine and we really appreciate your interest. However, at this time it is proving to be extremely difficult for us to keep up with reviewing and testing each of these drivers for inclusion in the Machine core. We really want to switch to a more pluggable model, as well as polish up a few things about the driver model which need to be changed to ensure a smooth and sustainable future.

Therefore, we will be moving to a plugin model for 0.5 and would love to have you involved in the design and development process. We are closing the outstanding driver PRs at this time, but please keep the code. We will stick closely to the current driver interface and you should be able to re-use a lot (if not all) of the existing driver along with the new plugin model. We will be moving all of the drivers which are merged directly into Machine today to the plugin model when it is available, so there will be no special treatment of those, and there will be documentation outlining the process of developing and using a Docker Machine driver plugin.

With all of that being said, we want to apologize for the lack of feedback on your pull request. As contributors ourselves, we understand that being left in limbo is no fun. We would have liked to address this sooner, and in the future we will be more responsive around these kinds of issues.

Once again, we thank you for the contribution and the tremendous support. Keep hacking strong!

If you want to contribute to the design of the plugin model, we'd love to get your input on this issue where we will be planning it:

https://github.com/docker/machine/issues/1626

@ehazlett & @nathanleclaire

**Comment by etcook** [comment]
Wow - this is disappointing :(

**Comment by ptxmac** [comment]
Now that the Driver Plugins implementation is complete, are any one working on a linode driver?

**Comment by cameronmalek** [comment]
+1

**Comment by taoh** [comment]
I created an initial implementation of the new linode plugin driver: https://github.com/taoh/docker-machine-linode 

There is still an issue though. I have to **re-install docker-engine manually on the newly-created server before it starts working**. Otherwise docker daemon cannot start with error message: **"Error starting daemon: error initializing graphdriver: driver not supported"**. 

@ehazlett if you can help take a look that'll be great. Thanks!

**Comment by nathanleclaire** [comment]
@taoh I think it's because, AUFS is the default storage driver for Ubuntu, but it's not supported on Linode.  I wonder what the best solution might be, since it's not currently possible for drivers to modify `HostOptions`, which is where such a setting is kept.

**Comment by etcook** [comment]
@nathanleclaire I have AUFS working properly on Linode but admittedly, it does require manually setting the bootloader in the Linode interface. I'm not sure if this can be automated through the API, but I can reach out to Linode if there's interest.

Here's more information: https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm

**Comment by bhhaskin** [comment]
any progress with this?

**Comment by drewcrawford** [comment]
Any progress with this?

**Comment by mtrofimm** [comment]
+1

**Comment by stevesmename** [comment]
looping in @felicianotech

**Comment by vertex-github** [comment]
+1 for this as well - we use Linode and they've been great.

**Comment by andrewmclagan** [comment]
yeah come on... :-)

linode..!

**Comment by taoh** [comment]
@etcook if you can help connect with Linode team regarding bootloader issue, that'll be great to resolve the last issue. Thanks in advance!

**Comment by ilsken** [comment]
@etcook You just need to set the Kernel to Grub2 right? If so, you can definitely do that with our API!

Just follow these steps:
- Get the KernelID you want with [avail.kernels](https://www.linode.com/api/utility/avail.kernels)  (these shouldn't ever change but it's good to use the API to get the ID anyway)
- Either [create a new Configuration Profile](https://www.linode.com/api/linode/linode.config.create) or [update the existing one](https://www.linode.com/api/linode/linode.config.update)
- [Boot the Linode](https://www.linode.com/api/linode/linode.boot) with your new or updated ConfigID 

Hope that helps!

Disclaimer: Linode employee but not speaking on behalf of Linode yada yada

**Comment by ilsken** [comment]
Hmm it looks like GRUB2 is missing from the avail.kernels list but it does work if you pass the ID to `linode.config.update/create`. I will ping the development team and look into that.

**Comment by ilsken** [comment]
Hey guys got an update from the team, GRUB2 shows up with the query: `api_key=<APIKEY>&api_action=avail.kernels&isKVM=1&isXen=0`. You should be all set to get this implemented!

As an aside, I was able to get the Linode driver working by using overlay instead of aufs as a workaround

**Comment by ptxmac** [comment]
Is there any update on this?

**Comment by camflan** [comment]
bump

**Comment by Kannaj** [comment]
+1

**Comment by Bogh** [comment]
+1

**Comment by mdzidic** [comment]
Any news?

**Comment by vyoz** [comment]
+1

**Comment by gandra** [comment]
+1

**Comment by noogen** [comment]
+100 Billion$

**Comment by exocode** [comment]
thumbs up! I count the days

**Comment by nathanleclaire** [comment]
All, looks like you can use the Linode driver @taoh has made here if desired: https://github.com/taoh/docker-machine-linode.  In the interim please stop +1-ing the comments as it creates unneeded noise.  Thanks!

**Comment by displague** [comment]
The @taoh repo was extended and converted to use the [official Linode's APIv4 Go wrapper](https://github.com/linode/linodego).

The [Docker Machine Driver for Linode](https://github.com/linode/docker-machine-driver-linode) is maintained by Linode.

More details available in the [Using the Linode Docker Machine Driver
](https://www.linode.com/community/questions/17797/using-the-linode-docker-machine-driver) guide.

**Pull request closed without merging**
