### PR TITLE
Add correct Swarm port bindings

### PR DESCRIPTION
**Pull request by nathanleclaire**
Closes https://github.com/docker/machine/issues/2840

Seems to be the case that `HostIp` needs to be set in port binding struct, it was getting set to empty string.

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
cc @docker/machine-maintainers FYI

**Comment by gvt** [comment]
I'm hitting this issue (well, #2840). Is this fix released yet?

**Comment by nathanleclaire** [comment]
@gvt Should be -- are you using 0.6.0?

**Comment by gvt** [comment]
My swarm nodes say they are using Docker v1.9.1. Not sure which version of Swarm they use, inspect doesn't appear to give that info. How can I check?

**Comment by nathanleclaire** [comment]
@gvt I mean Docker Machine version.  Are you on 0.6.0?

**Comment by gvt** [comment]
Yes
```
$ docker-machine --version
docker-machine version 0.6.0, build e27fb87
```

**Comment by nathanleclaire** [comment]
And the hosts were created with that Machine version?  What are the logs using `--debug` of creating them?  What is the output of `docker ps -a` for each host?

**Comment by gvt** [comment]
I didn't use the `--debug` flag during the creation of these swarm nodes. But I could re-create them.

the swarm master node:
```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS               NAMES
cc3c568ea0e3        swarm               "/swarm create"          59 minutes ago      Exited (0) 59 minutes ago                           stoic_sinoussi
f5ce45ae4a62        swarm:latest        "/swarm join --advert"   About an hour ago   Restarting (1) 17 minutes ago                       swarm-agent
37e49981c05a        swarm:latest        "/swarm manage --tlsv"   About an hour ago   Restarting (1) 17 minutes ago                       swarm-agent-master
```

swarm member node 1:
```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
36cc1a149701        swarm:latest        "/swarm join --advert"   53 minutes ago      Up 53 minutes                           swarm-agent
```

swarm member node 2:
```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
cb3e2f961269        swarm:latest        "/swarm join --advert"   49 minutes ago      Up 49 minutes                           swarm-agent
```

**Comment by nathanleclaire** [comment]
Yeah, try re-creating please, and post the output of `--debug`.

**Comment by gvt** [comment]
The `--debug` flag does not seem to be available. I am using the openstack driver, and getting:

`$ docker-machine create --debug -d openstack \
  [...a bunch of options...]
Incorrect Usage.

Usage: docker-machine create [OPTIONS] [arg...]

Create a machine

Description:
   Run 'docker-machine create --driver name' to include the create flags for that driver in the help text.

Options:

   --driver, -d "none"											Driver to create machine with.
   --engine-env [--engine-env option --engine-env option]						Specify environment variables to set in the engine
   --engine-insecure-registry [--engine-insecure-registry option --engine-insecure-registry option]	Specify insecure registries to allow with the created engine
   --engine-install-url "https://get.docker.com"							Custom URL to use for engine installation [$MACHINE_DOCKER_INSTALL_URL]
   --engine-label [--engine-label option --engine-label option]						Specify labels for the created engine
   --engine-opt [--engine-opt option --engine-opt option]						Specify arbitrary flags to include with the created engine in the form flag=value
   --engine-registry-mirror [--engine-registry-mirror option --engine-registry-mirror option]		Specify registry mirrors to use
   --engine-storage-driver 										Specify a storage driver to use with the engine
   --openstack-active-timeout "200"									OpenStack active timeout [$OS_ACTIVE_TIMEOUT]
   --openstack-auth-url 										OpenStack authentication URL [$OS_AUTH_URL]
   --openstack-availability-zone 									OpenStack availability zone [$OS_AVAILABILITY_ZONE]
   --openstack-domain-id 										OpenStack domain ID (identity v3 only) [$OS_DOMAIN_ID]
   --openstack-domain-name 										OpenStack domain name (identity v3 only) [$OS_DOMAIN_NAME]
   --openstack-endpoint-type 										OpenStack endpoint type (adminURL, internalURL or publicURL) [$OS_ENDPOINT_TYPE]
   --openstack-flavor-id 										OpenStack flavor id to use for the instance [$OS_FLAVOR_ID]
   --openstack-flavor-name 										OpenStack flavor name to use for the instance [$OS_FLAVOR_NAME]
   --openstack-floatingip-pool 										OpenStack floating IP pool to get an IP from to assign to the instance [$OS_FLOATINGIP_POOL]
   --openstack-image-id 										OpenStack image id to use for the instance [$OS_IMAGE_ID]
   --openstack-image-name 										OpenStack image name to use for the instance [$OS_IMAGE_NAME]
   --openstack-insecure											Disable TLS credential checking. [$OS_INSECURE]
   --openstack-ip-version "4"										OpenStack version of IP address assigned for the machine [$OS_IP_VERSION]
   --openstack-keypair-name 										OpenStack keypair to use to SSH to the instance [$OS_KEYPAIR_NAME]
   --openstack-net-id 											OpenStack network id the machine will be connected on [$OS_NETWORK_ID]
   --openstack-net-name 										OpenStack network name the machine will be connected on [$OS_NETWORK_NAME]
   --openstack-nova-network										Use the nova networking services instead of neutron. [$OS_NOVA_NETWORK]
   --openstack-password 										OpenStack password [$OS_PASSWORD]
   --openstack-private-key-file 									Private keyfile to use for SSH (absolute path) [$OS_PRIVATE_KEY_FILE]
   --openstack-region 											OpenStack region name [$OS_REGION_NAME]
   --openstack-sec-groups 										OpenStack comma separated security groups for the machine [$OS_SECURITY_GROUPS]
   --openstack-ssh-port "22"										OpenStack SSH port [$OS_SSH_PORT]
   --openstack-ssh-user "root"										OpenStack SSH user [$OS_SSH_USER]
   --openstack-tenant-id 										OpenStack tenant id [$OS_TENANT_ID]
   --openstack-tenant-name 										OpenStack tenant name [$OS_TENANT_NAME]
   --openstack-username 										OpenStack username [$OS_USERNAME]
   --swarm												Configure Machine with Swarm
   --swarm-addr 											addr to advertise for Swarm (default: detect and use the machine IP)
   --swarm-discovery 											Discovery service to use with Swarm
   --swarm-host "tcp://0.0.0.0:3376"									ip/socket to listen on for Swarm master
   --swarm-image "swarm:latest"										Specify Docker image to use for Swarm [$MACHINE_SWARM_IMAGE]
   --swarm-master											Configure Machine to be a Swarm master
   --swarm-opt [--swarm-opt option --swarm-opt option]							Define arbitrary flags for swarm
   --swarm-strategy "spread"										Define a default scheduling strategy for Swarm
   --tls-san [--tls-san option --tls-san option]							Support extra SANs for TLS certs
flag provided but not defined: -debug

**Comment by nathanleclaire** [comment]
@gvt `--debug` is flag for `docker-machine`, not subcommand -- so if you move it to immediately after `docker-machine` arg it will work

**Pull request merged**
