### PR TITLE
document how to install registry custom CA

### PR DESCRIPTION
**Pull request by bbodenmiller**
Document how to install custom CA for registry. This is needed to address `x509: certificate signed by unknown authority` error messages.

Related to https://github.com/boot2docker/boot2docker/issues/347, https://github.com/docker/machine/issues/2247, https://github.com/docker/machine/issues/1799, https://github.com/docker/machine/issues/1963, https://github.com/docker/machine/issues/1872

On merge update https://github.com/docker/toolbox/pull/558 and https://github.com/boot2docker/boot2docker/pull/1195.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Thanks @bbodenmiller ... Looks pretty good I think but could you use the appended `ssh` notation to keep it all in one shell session (i.e., `docker-machine ssh default sudo mv ~/ca.crt /etc/docker/certs.d/hostname/ca.crt`)?  Also, would it be sufficient to run `docker-machine ssh default sudo /etc/init.d/docker restart` vs. a whole VM restart? (takes ~3 seconds vs. ~45)

**Comment by bbodenmiller** [comment]
`docker-machine ssh default sudo mv ~/ca.crt /etc/docker/certs.d/hostname/ca.crt` wasnt working for me, seems `sudo` is not allowed in that manner? Also `docker-machine ssh default sudo /etc/init.d/docker restart` did seem to be enough either.

**Comment by nathanleclaire** [comment]
> docker-machine ssh default sudo mv ~/ca.crt /etc/docker/certs.d/hostname/ca.crt wasnt working for me

Hm, sorry, I misled you a bit.  You'd want something like `docker-machine ssh default sudo mv ca.crt /etc/docker/certs.d/hostname/ca.crt` (without the tilde, since otherwise it will use your Mac/Windows computer home directory).

> docker-machine ssh default sudo /etc/init.d/docker restart did seem to be enough either.

To restart the daemon or... It needs to be used in conjunction with the other steps.

**Comment by nathanleclaire** [comment]
@bbodenmiller Any update/do you still want to work on this?

cc @londoncalling Maybe you'd be willing to carry?

**Comment by londoncalling** [comment]
@nathanleclaire I can carry it ...

**Comment by nathanleclaire** [comment]
Nice.  Yeah I think it's relevant info, just needs a little polish.

**Comment by bbodenmiller** [comment]
@nathanleclaire still having trouble with your suggestions (using Docker Toolbox on Windows 7):

image

`docker-machine ssh default sudo /etc/init.d/docker restart` also isn't working... ideas?

**Comment by londoncalling** [comment]
Hi Ben,
Yes I ran into this also today , working on a solution. I'll try and get
back to you tomorrow on this hopefully (along with a docs update soon after
).

Thanks for your patience !

Vicky

**Comment by nathanleclaire** [comment]
@bbodenmiller I think you may be getting hit by the infamous mingw-unix-to-windows-path-translation feature.  Try surrounding UNIX paths in quotes, e.g., `docker-machine ssh default 'sudo /etc/init.d/docker restart'` -- there's an environment variable you can set to turn it off as well (quickstart terminal is intended to have this set by default), though I'm having trouble finding it at the moment, and it's quite specific to a particular unix-on-windows shell (git bash i think).

**Comment by bbodenmiller** [comment]
Hmmm... I'm running these from the quickstart terminal so perhaps that is broken?

**Comment by bbodenmiller** [comment]
Sweet... got it working finally...

```
docker-machine scp certfile default:ca.crt
docker-machine ssh default 'sudo mkdir -p /etc/docker/certs.d/hostname/'
docker-machine ssh default 'sudo mv ca.crt /etc/docker/certs.d/hostname/ca.crt'
```

Doesn't even appear a docker or docker machine restart is needed. I will get the PR updated tonight.

There is definitely something wrong with quickstart terminal however as I cannot get those commands to work without the single quotes on multiple machines even after I uninstalled Docker Toolbox, Git, and VirtualBox and reinstalled all from Docker Toolbox.

**Comment by londoncalling** [comment]
@bbodenmiller awesome! @nathanleclaire thanks! I actually got the node creation working today on Docker for Windows Beta 27 (updating / publishing those new docs soon) but with same instructions, so should be good. I'm testing Swarm mode creation tomorrow, as there were a few things there that aren't totally intuitive. Glad you are up and running though, Ben.

**Comment by londoncalling** [comment]
@nathanleclaire As we discussed, I'm going to merge this so that it makes it into the transition to single docs repo. Then I'll review, update in the new repo. I'm tracking it so I have the URL for this PR and can get back to it later this week.

**Comment by nathanleclaire** [comment]
nice @bbodenmiller .  will have to take a look at the quickstart terminal.  make sure you're using latest version, e.g., i just released 1.12.2-rc1

**Comment by nathanleclaire** [comment]
thanks @bbodenmiller @londoncalling !!!

**Pull request merged**
