### PR TITLE
Implement configurable Swarm options

### PR DESCRIPTION
**Pull request by nathanleclaire**
This allows the user to specify a scheduling strategy, and any arbitrary swarm master flag (e.g. heartbeat) they want, to a created machine.  There aren't many `--join` options so I haven't bothered with configuration of the worker bees.

Still to do : 

~~1. Docs~~
~~2. Integration tests~~

However, I wanted to get the code in ASAP, so PTAL.

:bee: :bee: :bee: :bee: :bee: 

cc @ehazlett @vieux @aluzzardi @hairyhenderson @sthulb 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by sthulb** [comment]
Can we hijack this a bit and remove the swarm options from the drivers? i.e. EC2. 
There's not any real reason for them to know about swarm.

**Comment by nathanleclaire** [comment]
@sthulb Hm, there seems to be some cases where we can take them out e.g. `rackspace`. I think in some cases unfortunately they need to be swarm-aware (e.g. for `amazonec2` we have to open `3376` on the security group if the node is a swarm master), although I would definitely be interested in trying to find a more elegant solution.

**Comment by sthulb** [comment]
The drivers have a mechanism to open ports. We could utilise it from hosts.go maybe.

**Comment by ehazlett** [comment]
I think down the road we could use the `AuthorizePort` functionality to help remove this dependency.

**Comment by nathanleclaire** [comment]
Yeah, at least for the immediate future, `AuthorizePort` seems like the right way to handle this.

**Comment by ehazlett** [comment]
Overall looks good.  I think after docs / tests this will be good.

**Comment by nathanleclaire** [comment]
We should make an issue to track removing swarm logic from providers directly.

**Comment by aluzzardi** [comment]
Minor nit:

I'd call it `--swarm-opt` rather than `--swarm-flag` just to be consistent with Docker:

```
docker -d --storage-opt dm.basesize=20G
```

**Comment by hairyhenderson** [comment]
@aluzzardi `--swarm-flag` is consistent with the existing `--engine-flag` option in Machine (from #1040), but I agree they should be consistent with Docker as much as makes sense.

Maybe `--swarm-flag` should be `--swarm-opt`, and `--engine-flag` should be renamed to `--engine-opt` (in a separate PR, of course)? IMO this is totally doable now since `--engine-flag` will be brand-new in 0.3.0.

/cc @nathanleclaire @ehazlett

**Comment by ehazlett** [comment]
+1 for `--engine-opt` and `--swarm-opt`.

**Comment by nathanleclaire** [comment]
Yes, it will be changed to `--engine-opt` and `--swarm-opt`.

**Comment by nathanleclaire** [comment]
Updated with docs and fixed an issue that I identified where the agent wasn't getting created on master nodes.  Now all that remains for this is some tests.

**Comment by ehazlett** [comment]
Is this ready or are we waiting on more tests?

**Comment by nathanleclaire** [comment]
I'm going to add a few more tests, hopefully today!

**Comment by nathanleclaire** [comment]
Note to self: This should probably check if the swarm containers are running before running them.

**Comment by cpuguy83** [comment]
How come there is a `--swarm-strategy` flag? Based on the docs `--swarm-opt` should work for all `manage` flags.

**Comment by nathanleclaire** [comment]
> How come there is a --swarm-strategy flag? Based on the docs --swarm-opt should work for all manage flags.

It will, some flags we are supporting first class though.  For instance, in the engine options we are supporting `--engine-storage-driver` as its own flag for easy reference.  Now, it's definitely a good question whether or not that's the right approach.  

As far as I can see it, the biggest argument in favor of supporting some flags directly is that they are directly "self-documenting" and available to look at in the CLI help text.  The biggest argument against is uniformity - it makes setting the options slightly inconsistent.

@ehazlett WDYT?

**Comment by nathanleclaire** [comment]
Added an integration test.  I'd say I'm ready to merge this whenever you feel comfortable @ehazlett.

**Comment by ehazlett** [comment]
Swarm isn't starting.  Are we mapping the certs properly for the manager?

```
time="2015-05-21T13:20:47Z" level=fatal msg="Couldn't load X509 key pair (, ): open : no such file or directory. Key encrypted?"
```

**Comment by ehazlett** [comment]
Looks like an issue with the Swarm options.  `tlscacert`, `tlscert` and `tlskey` are all blank when sent to the swarm container:

```
       "Cmd": [
            "manage",
            "--tlsverify",
            "--tlscacert=",
            "--tlscert=",
            "--tlskey=",
            "-H",
            "tcp://0.0.0.0:3376",
            "--strategy",
            "binpacking",
```

**Comment by nathanleclaire** [comment]
Hm, I must have flubbed something.  What's the driver and OS you're testing on @ehazlett ?

**Comment by nathanleclaire** [comment]
It's an Ubuntu issue... I thought I updated a line which I hadn't... I got this

**Comment by nathanleclaire** [comment]
Fixed, PTAL

**Comment by nathanleclaire** [comment]
Rebased

**Comment by nathanleclaire** [comment]
Ah, fixing this issue.

**Comment by ehazlett** [comment]
LGTM

**Comment by vieux** [comment]
:+1:

**Pull request merged**
