### PR TITLE
Update generic.md

### PR DESCRIPTION
**Pull request by zijam**
Parameter for '--generic-ssh-key' should point to users public key

### CODE REVIEW

**Comment by dmp42** [comment]
@zijam can you sign your commits? Thanks

**Comment by zijam** [comment]
Done :wink:

**Comment by dmp42** [comment]
@zijam Sorry, I'm confused - why do you think the doc should be changed here?

**Comment by dmp42** [comment]
@zijam I'm closing this for now since I don't think it's correct, but let me know if I missed something and we can certainly reopen.

**Pull request closed without merging**
