### PR TITLE
amazonec2: add support for additional open ports

### PR DESCRIPTION
**Pull request by andrestc**
This PR adds a flag to the `amazonec2` driver to enable opening custom ports on the host.
This is a step to add this support for every core driver(where applied) as discussed in #3642(the azure driver already support this flag). 

I kept the same behavior as the azure driver, but I was thinking about supporting the format `port/protocol`(eg `8888/tcp`, `9200/udp`), defaulting the protocol to `tcp` if not set by the user. I decided to open the PR like this because I think the behavior should be the same across all core drivers. If we go for this behavior, I can update this PR and them move on to the other drivers.

cc @nathanleclaire, @ahmetalpbalkan 

Signed-off-by: André Carvalho <andre.carvalho@corp.globo.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
> I was thinking about supporting the format port/protocol(eg 8888/tcp, 9200/udp), defaulting the protocol to tcp if not set by the user.

This is how Docker works and I think how I'd like to do it here too.  @ahmetalpbalkan what do you think.  I'd prefer not to just hardcode to TCP.  There are other protos user might want as well BTW.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire hmm in Azure case I guess we just open TCP. It makes sense to add `/tcp`/`/udp` distinction probably in a separate PR.

**Comment by andrestc** [comment]
@nathanleclaire, @ahmetalpbalkan I've updated the PR adding support for the port/protocol format, defaulting the protocol to "tcp". 

After this is good to go, I can change the azure driver to accept the same format. I'll, then, move the function splitPortProtocol to some utility package where it can be used by the other drivers (any suggestion where to place it)? Then, I'll move to add the analogous flag to other core drivers that it fits.

**Comment by ahmetalpbalkan** [comment]
Sounds good. :+1:

**Comment by nathanleclaire** [comment]
@andrestc It's ready for review?

**Comment by andrestc** [comment]
@nathanleclaire yes!

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
