### PR TITLE
add suspend command

### PR DESCRIPTION
**Pull request by wwwjfy**
Other drivers probably have this functionality, too, but I've only implemented for Vmware Fusion and VirtualBox

### CODE REVIEW

**Comment by ehazlett** [comment]
I'm torn on this as a global command since not all drivers support it.

Thoughts @sthulb ?

**Comment by sthulb** [comment]
I'd rather see it implemented as a flag on stop. So you end up with `machine stop --pause`

**Comment by sthulb** [comment]
But I immediately regret it :p

Perhaps a better wording than pause would make more sense.

**Comment by wwwjfy** [comment]
I don't see much a difference a flag on `stop` makes more clear for unsupported drivers. A message/info will be shown anyway. But if you think it's better, what about `matching stop --save`, to be same with the state `Saved`?

**Comment by sthulb** [comment]
--save seems better.

**Comment by Tebro** [comment]
I was hacking at this for VMWare fusion earlier (since boot2docker image was not persistant), my work can be found here: https://github.com/Tebro/machine/tree/feature/vmwarefusion-save, feel free to use it.

**Comment by nathanleclaire** [comment]
I'm -1 on this because it can't be implemented in a uniform way.

**Comment by nathanleclaire** [comment]
Going to close this since there's no way to implement for DigitalOcean, Amazon, etc.

**Pull request closed without merging**
