### PR TITLE
Regression bug fix for pull request #3654

### PR DESCRIPTION
**Pull request by wzymaster**
I found a regression bug in the pull request #3654 and there is a fix to enable 'SOFTLAYER_DOCKER_ON_PRIVATE_IP' environment variable so that docker daemon can be running on the private IP only.

### CODE REVIEW

**Comment by wzymaster** [comment]
when I am doing signing my work and get error like : 

```
Leos-MacBook-Pro-2:somewhere leowu$ git rebase --continue
Stopped at 196d2924ac48075d6e794931d4c5d43947da3b82... azure.md: Add known issue notice
You can amend the commit now, with

	git commit --amend

Once you are satisfied with your changes, run

	git rebase --continue

```

**Comment by wzymaster** [comment]
@GordonTheTurtle @nathanleclaire 
I have successfully run 'gofmt' according to your previous suggestions : 

```
docker run -ti -w /machine -v $(pwd):/machine golang:alpine sh -c 'gofmt -s -w drivers/softlayer/*.go'
```
why do I still get 'fmt' error in the build ?

**Comment by wzymaster** [comment]
what's next after all checks have passed ?

**Comment by nathanleclaire** [comment]
@wzymaster This needs a rebase.  The history is all over the place.

**Comment by wzymaster** [comment]
@nathanleclaire I decide to make a new pull request after rebase and will give up this one then.

**Pull request closed without merging**
