### PR TITLE
FIX #1985 Build with Docker on TravisCI

### LINKED ISSUE #1985: CI should run in container
The project can be built in-container and that's the only way to make sure the developer host has no impact on the build/tests.

Currently, on test is broken in-container but passes on most developer workstations.
Nobody noticed because:

+ Developer tend to not use in-container build because it's slower. That's OK.
+ The CI doesn't run the in-container build. That's **not** OK.

We should update our TravisCI build to do everything in-container. That's ok since Travis supports Docker well http://docs.travis-ci.com/user/docker/

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
ping @dmp42

**Comment by dmp42** [comment]
@dgageot this breaks s*** coveralls.
Can you keep the `coverage-send` target out of container? It doesn't matter at all.

**Comment by dgageot** [comment]
@dmp42 There must be en env variable to set. I'll check that

**Comment by dmp42** [comment]
@dgageot so, goveralls is supposed to detect a travis env somehow.
Check https://github.com/mattn/goveralls

**Comment by dmp42** [comment]
LGTM

**Pull request merged**
