### PR TITLE
correct typos in readme

### PR DESCRIPTION
**Pull request by stefanfoulis**

### CODE REVIEW

**Comment by ehazlett** [comment]
@ggiamarchi +1

@stefanfoulis would you also mind signing your commit?  Thanks!

**Comment by stefanfoulis** [comment]
@ggiamarchi I removed the redundant "if"
@ehazlett I signed and force-pushed the commit.

**Comment by ehazlett** [comment]
@stefanfoulis ok thx.  for some reason it's still not seeing it.  since these are docs only I think it's ok for this one.

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
