### PR TITLE
Support colons in scp paths

### PR DESCRIPTION
**Pull request by dgageot**

### CODE REVIEW

**Comment by dgageot** [comment]
While fixing the #2064 bug, I tried to simplify both code and tests, fix the TODOs...
I created small commits so that it's not too hard to review.

@docker/machine-maintainers Can you take a look please.

**Comment by dmp42** [comment]
LGTM
This is important in making windows a first-class platform.

**Comment by nathanleclaire** [comment]
I'll need some time to review.  We're pretty far into the weeds for 0.5.0, so maybe we can tag it for release in 0.5.1.

**Comment by dgageot** [comment]
I'm ok with that

**Comment by ehazlett** [comment]
LGTM -- please squash the commits before we merge.  Thanks!

**Comment by dgageot** [comment]
Thank you @ehazlett! I think @nathanleclaire wanted to take a look after the 0.5.0 release. Unless we change plan, I'll leave the commits as is until then.

**Comment by dgageot** [comment]
squashed and merged! Thanks @ehazlett and @dmp42 for the feedback

**Comment by nathanleclaire** [comment]
It's probably fine but, I did want to at least take this for a spin before merging.

**Comment by dgageot** [comment]
Sorry @nathanleclaire, I merged since I had 2 LGTMs. Feel free to give your feedback

**Pull request merged**
