### PR TITLE
1150 separate pkgaction into 'pkgaction' and 'serviceaction'

### PR DESCRIPTION
**Pull request by xiaohui**
separate pkgaction #1150

### CODE REVIEW

**Comment by ehazlett** [comment]
@nathanleclaire how does this affect the libmachine refactor?

**Comment by nathanleclaire** [comment]
Shouldn't result in any conflicts.  `provision` was already inside of `libmachine` and not much has been changed there.

:+1: from my end

**Comment by ehazlett** [comment]
Cool.  Would you mind squashing into a single commit?  Thanks.

**Comment by nathanleclaire** [comment]
And yes, in case it wasn't clear, after a squash LGTM

**Comment by xiaohui** [comment]
@ehazlett @nathanleclaire thanks, I will make it clearer in my next PR.

**Comment by nathanleclaire** [comment]
> thanks, I will make it clearer in my next PR.

Hm, I'm not sure what you're referencing, but I was just saying that in case _I_ wasn't clear, this PR LGTM (ready for merge).

**Comment by xiaohui** [comment]
>  Hm, I'm not sure what you're referencing, but I was just saying that in case I wasn't clear, this PR LGTM (ready for merge).

I mean to squash to a single commit for one PR as @ehazlett said.

**Comment by nathanleclaire** [comment]
@xiaohui Evan means to rebase the commits like so:

```console
$ git rebase -i HEAD~3
$ # Editor opens, change "pick" to "squash" for the bottom two and exit
$ git push -f xiaohui 1150-separate-pkgaction  # or whatever your remote is 
```

**Comment by xiaohui** [comment]
image

why ci/circleci is failed？

**Comment by dmp42** [comment]
@xiaohui ignore circle for now. It's not ready yet.

**Comment by xiaohui** [comment]
ping @nathanleclaire  I have squashed these commits.

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
Ah, looks like some conflicts need to be fixed though.  Sorry about that -- please rebase and I'll merge.

**Comment by xiaohui** [comment]
@nathanleclaire would you give me many more details about the conflicts. I have rebased it again, and all tests are passed.

**Comment by nathanleclaire** [comment]
Mergeable now -- LGTM and thanks @xiaohui

**Pull request merged**
