### PR TITLE
Update some driver/plugin-related documentation

### PR DESCRIPTION
**Pull request by nathanleclaire**
The added text should be fairly self-explanatory.  I have been mentioning wanting to add this for a while and I want a way to keep track of which plugins are available in the ecosystem.  I've listed all the driver plugins I know of that seem maintained.

cc @docker/machine-maintainers 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
@yamamoto-febc Want to chime in with your e-mail address?

**Comment by nathanleclaire** [comment]
cc also @londoncalling

**Comment by dgageot** [comment]
LGTM

**Comment by londoncalling** [comment]
Thx for cc'ing me as I get up to speed on these docs.

**Pull request merged**
