### PR TITLE
Updating to Go 1.5

### PR DESCRIPTION
**Pull request by hairyhenderson**
Now that [Go 1.5 is out](http://blog.golang.org/go1.5)...

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by hairyhenderson** [comment]
ugh... rebase gone wrong.

**Comment by ehazlett** [comment]
LGTM

**Comment by nathanleclaire** [comment]
I'm actually against this change.  Go 1.5 kicks up compile times substantially and I don't see what benefit it would buy us (the GC improvements are largely irrelevant to Machine CLI and and we aren't using e.g. the experimental vendoring features).

**Comment by hairyhenderson** [comment]
@nathanleclaire - oh. There was a big improvement in image sizes (1.4GBs vs 663MBs), which (IMO) is a good reason especially for new developers wanting to get started with DM. Also I think it would be interesting to experiment with the experimental vendoring feature. And there's at least one language change (map literals) that could be useful.

That being said, the builds _are_ slower, which is non-awesome. I'm not opposed to reverting this if you want - it's up to you and @ehazlett, as always :)

**Comment by thaJeztah** [comment]
I think @unclejack has some links to issues related to the performance issues with Go 1.5, I read the issues, but don't have the links at hand.

 IIRC, there were some settings that could bring performance and size back a bit to what they were in 1.4

**Comment by hairyhenderson** [comment]
Also, as a point of reference, here are some times from my laptop for Go1.5 builds:

Building for a single arch outside the container is pretty fast:
```console
$ time godep go build
godep go build  20.02s user 2.79s system 415% cpu 5.486 total
```

Single arch inside the container (with 4 CPUs on my VMWare Fusion VM):

```console
$ time GOOS="darwin" GOARCH="amd64" make
rm -f docker-machine_*
rm -rf Godeps/_workspace/pkg
script/build
Number of parallel builds: 4

-->    darwin/amd64: github.com/docker/machine
GOOS="darwin" GOARCH="amd64" make  0.28s user 0.04s system 2% cpu 15.101 total
```

Multiple arches inside container:

```console
$ time make
rm -f docker-machine_*
rm -rf Godeps/_workspace/pkg
script/build
Number of parallel builds: 4

-->   windows/amd64: github.com/docker/machine
-->       linux/386: github.com/docker/machine
-->       linux/arm: github.com/docker/machine
-->      darwin/386: github.com/docker/machine
-->     linux/amd64: github.com/docker/machine
-->     windows/386: github.com/docker/machine
-->    darwin/amd64: github.com/docker/machine
make  0.28s user 0.02s system 0% cpu 1:15.02 total
```

So, the full multi arch build is slow, but personally I almost always only do a single-arch build (outside of the container) while I'm working on stuff, and then only do a multiarch build before issuing a PR (er, _when I remember_ :wink:).

**Pull request merged**
