### PR TITLE
Correct error handling for external SSH client

### PR DESCRIPTION
**Pull request by mmalchuk**
In some cases, (e.g. private key not accessible or has incorrect
permissions) docker-machine failed with error "Something went wrong
running an SSH command!". This commit will add the correct debug
messages and show the correct errors for the bad private keys.

### CODE REVIEW

**Comment by mmalchuk** [comment]
partially fixes https://github.com/docker/toolbox/issues/153

**Comment by mmalchuk** [comment]
partially fixes https://github.com/docker/machine/issues/2240

**Comment by nathanleclaire** [comment]
Looks pretty good, could you add a unit test please?  It should be fairly straightforward to generate a few temporary files with the properties that you're rejecting here.

**Comment by mmalchuk** [comment]
@nathanleclaire unit tests added.

**Comment by nathanleclaire** [comment]
LGTM

Thanks!

**Pull request merged**
