### PR TITLE
Enhanced coverage system

### PR DESCRIPTION
**Pull request by dmp42**
The previous coverage script had a number of drawbacks:

- have to manually maintain a blacklist of directories
- output doesn't show proper navigation dropdown list for all files
- miss coveralls integration

This PR aims at fixing this.

### CODE REVIEW

**Comment by dmp42** [comment]
So, we now have https://coveralls.io/github/docker/machine for nice display / history

+ a second "check" on PRs with the actual overall coverage (12.339%)

@ehazlett @nathanleclaire wdyt?

**Comment by dmp42** [comment]
I'm setting an arbitrary 12% threshold for failing the build (if we fall below that), and an arbitrary coverage decrease of 1% for failing.

**Comment by nathanleclaire** [comment]
SGTM

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
