### PR TITLE
New Driver: Parallels Desktop for Mac

### PR DESCRIPTION
**Pull request by rickard-von-essen**
This driver supports running boot2docker on [Parallels Desktop for Mac](http://www.parallels.com/products/desktop/).

This requires a boot2docker.iso with the _autoformat_ patch applied from:
https://github.com/boot2docker/boot2docker/pull/659. The same requirement as the _VMWare Fusion_ driver.

Next I'll spend some time on trying to get parallels tools in [boot2docker](https://github.com/boot2docker/boot2docker).

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
FYI: @legal90

**Comment by legal90** [comment]
@rickard-von-essen Great job! Thank you!
I'll try to check it as soon as possible.

**Comment by ehazlett** [comment]
Awesome, thank you!

**Comment by sean-brandt** [comment]
When will this be integrated? Really would like this ASAP so I don't have to run multiple virtualization systems on my Mac

**Comment by ehazlett** [comment]
@sean-brandt we are finishing the driver refactor in #756. after that we will start merging the pending drivers.  thanks!

**Comment by sean-brandt** [comment]
Now that it looks like #756 has merged do we have an ETA on this?

**Comment by ehazlett** [comment]
@sean-brandt i'm getting docs finished by next week.  if one wanted to start on rebasing their drivers now that would be fine -- it would help get the docs in  order.

**Comment by legal90** [comment]
@rickard-von-essen I've rebased your branch to the current master state (45f08d9) and added some refactoring:
https://github.com/legal90/machine/tree/parallels-driver
Now it works fine and can be merged to master without conflicts. Should I create a new PR or you will push these commits to your fork?

P.s. Also, I'm going to add some unit and acceptance tests for Parallels driver soon.

**Comment by rickard-von-essen** [comment]
@legal90 Awesome I hadn't have time to do it my self yet. I'll review your rebase in a couple of days and you can open a new PR after that.

**Comment by legal90** [comment]
I've also added integration tests to my branch. They all are passing successfully.

**Comment by ctrlok** [comment]
@legal90 Hi, I have some problem with manual testing your branch. 
```shell 
git:master@parallels[i]> docker-machine create -d parallels par
INFO[0000] Creating SSH key...
INFO[0000] Creating Parallels Desktop VM...
INFO[0004] Waiting for VM to come online...
INFO[0028] "par" has been created and is now the active machine.
INFO[0028] To point your Docker client at it, run this in your shell: eval "$(docker-machine env par)"
git:master@parallels[i]> docker-machine env
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH="/Users/me/.docker/machine/machines/par"
export DOCKER_HOST=tcp://10.211.55.113:2376
git:master@parallels[i]> docker-machine stop par
git:master@parallels[i]> docker-machine start par
INFO[0001] Waiting for VM to start...
git:master@parallels[i]> docker-machine env
docker@10.211.55.113's password:```

**Comment by ctrlok** [comment]
And I have some problem with mounting volumes — just no files in a folder in docker after mount.

**Comment by legal90** [comment]
Yes, it is not ready to use yet. The hard disk is attached to the vm, but there are no partitions and nothing to mount. That's why `.ssh/authorized_key` disappears after restart and b2d asks the password.

I'm working on it.

**Comment by legal90** [comment]
@ctrlok I've implemented an approach for HDD, so now the VD disk is formatted and mounted automatically by boot2docker.
https://github.com/legal90/machine/tree/parallels-driver

**Comment by ctrlok** [comment]
@legal90 Thanks!

**Comment by rickard-von-essen** [comment]
@legal90 I've done some testing and code reviewing, and it looks good to me. Awesome work! If you open a new PR I'll close this with a ref to yours.

**Comment by rickard-von-essen** [comment]
Superceded by #939

**Pull request closed without merging**
