### PR TITLE
Tests fixes / silence build / add unit tests

### PR DESCRIPTION
**Pull request by dmp42**

### CODE REVIEW

**Comment by dmp42** [comment]
Rebased.
cc @nathanleclaire

**Comment by nathanleclaire** [comment]
Thanks @dmp42 !

I think `TestCopyFile` should be in the `mcnutils` directory.

**Comment by nathanleclaire** [comment]
Looks like there are a few other mis-moves as well.  Feel free to message me if you need help understanding the new layout / organization.

**Comment by nathanleclaire** [comment]
Excellent!

**Comment by dmp42** [comment]
Thx! :)

**Pull request merged**
