### PR TITLE
Added generic-ssh-pass and modified sudo commands

### PR DESCRIPTION
**Pull request by pdxjohnny**
I found and fixed an issue I had where there was no way for me to use docker machine as a non root user because I would get an error saying that sudo had no tty or askpass present #1569

I added an option for the generic driver of generic-ssh-pass which is the password of the generic-ssh-user. I modified all the ssh commands that involve sudo (I'm pretty sure I got them all) to pipe the password to sudo -S

I was able to fix my issue and docker compose now works with sudo because I can pass it my password

If you see a bunch of pull requests from me its because I messed up a few times i forgo to run the formatter and stuff but this one should be good.

Signed-off-by: John Andersen <johnandersenpdx@gmail.com>

### CODE REVIEW

**Comment by osuka** [comment]
This is still happening to me, any chance of this getting merged? Otherwise the generic driver is pretty useless...

**Comment by pdxjohnny** [comment]
I agree ^

**Comment by britishbadger** [comment]
It would be nice if this could be merged in, as I still have the same issue with 0.5.0-rc3

**Comment by pdxjohnny** [comment]
I will try to update this to master sometime soonish, within the next two weeks

**Comment by pdxjohnny** [comment]
this is not finished I just had to push my changes up so I can work form home

**Comment by pimpim** [comment]
This is definitely not working in the 1.9.0 release. Seems a major issue as this means that running docker-machine on local linux machines running docker is not possible.

**Comment by pdxjohnny** [comment]
I have not tried to use this so If someone can please build and try to use the pass option let me know if it is working. I don't have time right now and the faster this can get merged the better. I'm not a fan of fixing merge conflicts so please help me test this!

**Comment by jaycyb** [comment]
+1

**Comment by dgageot** [comment]
Hi @pdxjohnny one base principle of docker-machine is that the ssh access should be root. It makes it possible to provision docker ourself and not rely on a docker installed from an unofficial source. This PR seems to go against this behaviour unless I got it wrong. @nathanleclaire @jeanlaurent wdyt?

**Comment by nathanleclaire** [comment]
> Hi @pdxjohnny one base principle of docker-machine is that the ssh access should be root.

More or less -- so far it's been implicitly implied that the user we are SSHing into the machine can use `sudo` privileges without needing to enter a password (which root is a subset of).  For instance the default AMI user is `ubuntu`, not `root`, and can `sudo` without a password.  Likewise for `docker` user in boot2docker.

At any rate, we can't merge this in without at least an API version bump (painful).  It modifies methods on the RPC side which will break existing plugins.

**Comment by pdxjohnny** [comment]
Understandable, Let me know if there is interest in the future otherwise
the fix for this is to use NOPASSWD for the user we are sshing with in the
suders file. But that should be documented, I don't think it is.

**Comment by nathanleclaire** [comment]
I wonder if entering SSH password over and over might be supportable by something like this:

```console
$ yes my-ssh-pass | docker-machine create -d generic --generic-ssh-key /path/to/passwd/protectedkey foobar
```

**Comment by nathanleclaire** [comment]
> the fix for this is to use NOPASSWD for the user we are sshing with in the
suders file. But that should be documented, I don't think it is.

Yes, I definitely think that would be a good addition to the documentation.

**Comment by pdxjohnny** [comment]
I think NOPASSWD is the only way without changes to machine.
The `yes` pipe is essentially the same thing this patch does. It just pipes the password to sudo each time sudo is run.

So ya if there's interest in this as the fix I'll update it to master, otherwise NOPASSWD is the kind of fix.

**Comment by marcellodesales** [comment]
@natemcmaster when will this be merged?

**Comment by dgageot** [comment]
@marcellodesales @pdxjohnny I guess there is no plan to merge it soon since it breaks all existing plugins which is painful. @pdxjohnny are you ok if we only update the documentation for the generic driver?

**Comment by pdxjohnny** [comment]
Ya that sounds good to me.

**Comment by dgageot** [comment]
@pdxjohnny see https://github.com/docker/machine/pull/3085

**Comment by pdxjohnny** [comment]
Closing because the update to documentation (#3085) is a sufficient fix to make the generic driver work.

**Pull request closed without merging**
