### PR TITLE
Simpler code

### PR DESCRIPTION
**Pull request by dgageot**
Simpler code related to the solution we found to https://github.com/docker/machine/issues/2410

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Love the idea, but I think we need to also write a `MarshalJSON` function for `RPCClientDriver` as well first though?

**Comment by nathanleclaire** [comment]
That said, I think we can merge just the removed `SerialDriver` wrapper code safely.

**Comment by dgageot** [comment]
There's one already in `client_driver.go`

**Comment by nathanleclaire** [comment]
Ah, cool.  I'll give this a test drive then.

**Comment by nathanleclaire** [comment]
Tried it and it works well.  Nice job @dgageot !

LGTM

**Pull request merged**
