### PR TITLE
FIX #1974 in-container make test fails

### LINKED ISSUE #1974: Makefile is broken
The Makefile is broken in multiple ways.

I've got multiple failures when trying to test machine on OSX.

+ out-of-container `make test` fails
+ in-container `make test` fails for a different reason
+ out-of-container `make clean` can't clean the binaries created by in-container `make build-x`

Here are the build outputs

```
$ make test
0 adds, 0 deletions; nothing to validate! :)
drivers/openstack/client.go:73: github.com/rackspace/gophercloud/openstack/compute/v2/extensions/keypairs.CreateOptsExt composite literal uses unkeyed fields
exit status 1
make: *** [vet] Error 1
```

```
$ USE_CONTAINER=true make test
Sending build context to Docker daemon 23.38 MB
Step 0 : FROM golang:1.5
 ---> e7bca7669626
Step 1 : RUN go get  github.com/golang/lint/golint             github.com/mattn/goveralls             golang.org/x/tools/cover             github.com/tools/godep             github.com/aktau/github-release
 ---> Using cache
 ---> 0bd0235b559a
Step 2 : WORKDIR /go/src/github.com/docker/machine
 ---> Using cache
 ---> e289a9ca79d0
Step 3 : ADD . /go/src/github.com/docker/machine
 ---> Using cache
 ---> 8b48f84971bc
Successfully built 8b48f84971bc
docker-machine-build-container
Sending build context to Docker daemon 23.38 MB
Step 0 : FROM golang:1.5
 ---> e7bca7669626
Step 1 : RUN go get  github.com/golang/lint/golint             github.com/mattn/goveralls             golang.org/x/tools/cover             github.com/tools/godep             github.com/aktau/github-release
 ---> Using cache
 ---> 0bd0235b559a
Step 2 : WORKDIR /go/src/github.com/docker/machine
 ---> Using cache
 ---> e289a9ca79d0
Step 3 : ADD . /go/src/github.com/docker/machine
 ---> Using cache
 ---> 8b48f84971bc
Successfully built 8b48f84971bc
docker-machine-build-container
0 adds, 0 deletions; nothing to validate! :)
?   	github.com/docker/machine	[no test files]
ok  	github.com/docker/machine/cmd	0.013s
ok  	github.com/docker/machine/commands	0.009s
ok  	github.com/docker/machine/commands/mcndirs	0.003s
ok  	github.com/docker/machine/drivers/amazonec2	0.003s
?   	github.com/docker/machine/drivers/amazonec2/amz	[no test files]
?   	github.com/docker/machine/drivers/azure	[no test files]
?   	github.com/docker/machine/drivers/digitalocean	[no test files]
?   	github.com/docker/machine/drivers/driverfactory	[no test files]
?   	github.com/docker/machine/drivers/exoscale	[no test files]
?   	github.com/docker/machine/drivers/fakedriver	[no test files]
?   	github.com/docker/machine/drivers/generic	[no test files]
?   	github.com/docker/machine/drivers/google	[no test files]
?   	github.com/docker/machine/drivers/hyperv	[no test files]
?   	github.com/docker/machine/drivers/none	[no test files]
?   	github.com/docker/machine/drivers/openstack	[no test files]
?   	github.com/docker/machine/drivers/rackspace	[no test files]
ok  	github.com/docker/machine/drivers/softlayer	0.003s
ok  	github.com/docker/machine/drivers/virtualbox	0.003s
?   	github.com/docker/machine/drivers/vmwarefusion	[no test files]
?   	github.com/docker/machine/drivers/vmwarevcloudair	[no test files]
?   	github.com/docker/machine/drivers/vmwarevsphere	[no test files]
?   	github.com/docker/machine/drivers/vmwarevsphere/errors	[no test files]
?   	github.com/docker/machine/libmachine	[no test files]
?   	github.com/docker/machine/libmachine/auth	[no test files]
ok  	github.com/docker/machine/libmachine/cert	0.624s
ok  	github.com/docker/machine/libmachine/drivers	0.003s
?   	github.com/docker/machine/libmachine/engine	[no test files]
?   	github.com/docker/machine/libmachine/examples	[no test files]
ok  	github.com/docker/machine/libmachine/host	0.004s
?   	github.com/docker/machine/libmachine/hosttest	[no test files]
ok  	github.com/docker/machine/libmachine/log	0.002s
?   	github.com/docker/machine/libmachine/mcnerror	[no test files]
--- FAIL: TestGetUsername (0.00s)
	utils_test.go:67: expected username ; received unknown
FAIL
FAIL	github.com/docker/machine/libmachine/mcnutils	0.005s
ok  	github.com/docker/machine/libmachine/persist	0.006s
?   	github.com/docker/machine/libmachine/persisttest	[no test files]
?   	github.com/docker/machine/libmachine/provider	[no test files]
ok  	github.com/docker/machine/libmachine/provision	0.004s
ok  	github.com/docker/machine/libmachine/provision/pkgaction	0.002s
ok  	github.com/docker/machine/libmachine/provision/serviceaction	0.002s
ok  	github.com/docker/machine/libmachine/ssh	0.433s
ok  	github.com/docker/machine/libmachine/state	0.002s
?   	github.com/docker/machine/libmachine/swarm	[no test files]
?   	github.com/docker/machine/libmachine/version	[no test files]
?   	github.com/docker/machine/version	[no test files]
mk/test.mk:3: recipe for target 'test-short' failed
make: *** [test-short] Error 1
make: *** [test] Error 2
```

```
$ USE_CONTAINER=true make build-x
Sending build context to Docker daemon 23.38 MB
Step 0 : FROM golang:1.5
 ---> e7bca7669626
Step 1 : RUN go get  github.com/golang/lint/golint             github.com/mattn/goveralls             golang.org/x/tools/cover             github.com/tools/godep             github.com/aktau/github-release
 ---> Using cache
 ---> 0bd0235b559a
Step 2 : WORKDIR /go/src/github.com/docker/machine
 ---> Using cache
 ---> e289a9ca79d0
Step 3 : ADD . /go/src/github.com/docker/machine
 ---> Using cache
 ---> 8b48f84971bc
Successfully built 8b48f84971bc
docker-machine-build-container

$make clean
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/darwin-386: is a directory
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/darwin-amd64: is a directory
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/linux-386: is a directory
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/linux-amd64: is a directory
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/windows-386: is a directory
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/windows-amd64: is a directory
make: *** [build-clean] Error 1
```

### PR DESCRIPTION
**Pull request by dgageot**

### CODE REVIEW

**Comment by dgageot** [comment]
@dmp42 @nathanleclaire Can you merge that one please?

**Comment by dmp42** [comment]
@dgageot sorry, I know we have been all over the place with this.

So:

 * machine *can* work properly in environments where there is no username - it will just fallback to using "unknown" as a username
 * we have a test that fails when there is no username

I really think we should fix the test, which to me is non-sensical - instead of ignoring the condition when there is no username.

wdyt?

**Comment by dgageot** [comment]
@dmp42 Il was decided with @nathanleclaire to just add the user in the Dockerfile.
This fixes the build.

We can talk about fixing the root cause in a second step. @nathanleclaire was not too  motivated about it. I agree that we have bigger fish to fry

**Comment by nathanleclaire** [comment]
:+1:

**Pull request merged**
