### PR TITLE
add qcloud driver

### PR DESCRIPTION
**Pull request by wangnan8791**
add qcloud driver to docker machine.
refer to www.qcloud.com for more information about our cloud.

### CODE REVIEW

**Comment by ehazlett** [comment]
@wangnan8791 thanks for the contribution!  we are working on stability for machine and want to get integration tests for the various drivers.  once we have integration tests (and test accounts, etc) setup we will work on getting this merged.  thanks!

**Comment by wangnan8791** [comment]
@ehazlett ,thanks for your reply, I send an email to you(ejhazlett<ejhazlett@gmail.com>), give you a test acount of qcloud. If you have any question about our qcloud, please send me email. Thanks!

**Comment by wangnan8791** [comment]
@ehazlett , hi, How is your progress of the integration tests?  If there is any problem of qcloud tests, please let us know.

**Comment by ehazlett** [comment]
@wangnan8791 we are currently working to get the existing driver set stable.  we should be able to get this fully tested soon.  thanks!

**Comment by ehazlett** [comment]
Hi , thanks for your efforts and persistence in submitting this driver. We are extremely excited that there is so much interest in Docker Machine and we really appreciate your interest. However, at this time it is proving to be extremely difficult for us to keep up with reviewing and testing each of these drivers for inclusion in the Machine core. We really want to switch to a more pluggable model, as well as polish up a few things about the driver model which need to be changed to ensure a smooth and sustainable future.

Therefore, we will be moving to a plugin model for 0.5 and would love to have you involved in the design and development process. We are closing the outstanding driver PRs at this time, but please keep the code. We will stick closely to the current driver interface and you should be able to re-use a lot (if not all) of the existing driver along with the new plugin model. We will be moving all of the drivers which are merged directly into Machine today to the plugin model when it is available, so there will be no special treatment of those, and there will be documentation outlining the process of developing and using a Docker Machine driver plugin.

With all of that being said, we want to apologize for the lack of feedback on your pull request. As contributors ourselves, we understand that being left in limbo is no fun. We would have liked to address this sooner, and in the future we will be more responsive around these kinds of issues.

Once again, we thank you for the contribution and the tremendous support. Keep hacking strong!

If you want to contribute to the design of the plugin model, we'd love to get your input on this issue where we will be planning it:

https://github.com/docker/machine/issues/1626

@ehazlett & @nathanleclaire

**Pull request closed without merging**
