### PR TITLE
Update rackspace/gophercloud dep.

### PR DESCRIPTION
**Pull request by robertjustjones**
Signed-off-by: Robert Jones <rjones@opdots.com>

### CODE REVIEW

**Comment by hairyhenderson** [comment]
Thanks @robertjustjones!

**Comment by nathanleclaire** [comment]
What is the specific motivation for the change?

Also, cc @ggiamarchi

**Comment by ehazlett** [comment]
Closing as this has stagnated.  Please open a new PR for this change.  Thanks!

**Pull request closed without merging**
