### PR TITLE
WIP: VMWare Workstation Driver

### PR DESCRIPTION
**Pull request by pecigonzalo**
Add this as placeholder and collaboration point to add a vmware workstation driver.
This is reusing part of the code from the fusion driver as both have the same executable and adding some code from packer vmware driver to detect the location of the files on windows.

As the title says this is still WIP.

TODO:

* ~~drivers/vmwareworkstation/workstation.go: Rework file for vmware workstation~~
* ~~add windows support~~
* ~~add cmd/machine-driver-vmwareworkstation.go~~
* add linux support
* add dhcplease discovery on windows
* ensure testing works as expected
* ensure build works as expected
* add docs/drivers/vm-workstation.md

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Thanks for the contribution (and great to see the interest as several folks have asked for a plugin of this variety), but please build and distribute the plugin in your own repo similar to the excellent work @legal90 has done here: https://github.com/Parallels/docker-machine-parallels

**Comment by pecigonzalo** [comment]
@nathanleclaire i understand, but could you elaborate on why you dont want to mainstream them? from reading the wiki it is my understanding that you accept driver pull requests as long as im willing to maintain it. Am i missing something?

Thanks

**Comment by nathanleclaire** [comment]
@pecigonzalo Simply put, accepting all submitted driver PRs doesn't scale (the wiki is slightly outdated).  It put the responsibility of ensuring driver quality on the core Machine maintainers, who are much better off working on the core and a small subset of plugins than trying to actively corral plugin maintainers into fixing reported issues.

With the plugin model, anyone willing to take on the maintenance burden of having their own driver repo can distribute such a plugin through a simple binary download.  So, there's no need to have them in the core.

**Comment by pecigonzalo** [comment]
Ok, for future reference ill be supporting this driver under:
https://github.com/pecigonzalo/docker-machine-vmwareworkstation

**Comment by nathanleclaire** [comment]
OK great. I want to add a `DRIVERS.md` type file where people can link to their drivers to our repo, so stay tuned on that.

**Pull request closed without merging**
