### PR TITLE
Rackspace/Openstack - Add/enhance --*-net-* create switches.

### PR DESCRIPTION
**Pull request by robertjustjones**
This is a rebase/reopen for #1451 so see relevant history there please. This addresses issues #1440 and #1444.

### CODE REVIEW

**Comment by dgageot** [comment]
Hi @robertjustjones What about the compatibility with existing machines? Changing the fields of Driver will make it incompatible with existing config.json files. Can you try?

**Comment by dgageot** [comment]
ping @fsoppelsa

**Comment by fsoppelsa** [comment]
Sorry for the delay, tried it (without looking at code):

```
$ neutron net-list
+--------------------------------------+---------+-------------------------------------------------------+
| id                                   | name    | subnets                                               |
+--------------------------------------+---------+-------------------------------------------------------+
| 095f43ed-65ba-48ce-8185-d4080e430a88 | public  | 2e7a11f5-4c2b-4aa8-8d8e-d43bafe0e175                  |
|                                      |         | b487d80b-9356-4855-b57b-9fbf9bf13503                  |
| 0cd5eef9-523e-48cd-8a95-5dbc39bc1aa2 | net04   | eff99d5a-c2ce-4ca2-89fb-eb23718f686a 172.16.0.0/24    |
| 44ead515-da4b-443b-85cc-a5d13e06ddc8 | mynet05 | 14466141-3a5e-4355-b75f-a3c957abe9a3 192.168.111.0/24 |
+--------------------------------------+---------+-------------------------------------------------------+
```
Is this incompatible with floating pools?

```
$ ./bin/docker-machine-Darwin-x86_64 --debug create \
> --driver openstack \
> --openstack-image-id 98011e9a-fc46-45b6-ab2c-cf6c43263a22 \
> --openstack-flavor-id 3 \
> --openstack-floatingip-pool public \
> --openstack-net-id 44ead515-da4b-443b-85cc-a5d13e06ddc85 \
> --openstack-sec-groups machine \
> --openstack-ssh-user ubuntu \
> u1
Docker Machine Version:  0.6.0-dev, build 
...
Error setting machine configuration from flags provided: Either Network names or Network ids must be specified, not both
```

With `openstack-net-id ID` I can't make it work while it goes smoothly with `openstack-net-name mynet05`:

```
 ./bin/docker-machine-Darwin-x86_64 --debug create \
> --driver openstack \
> --openstack-image-id 98011e9a-fc46-45b6-ab2c-cf6c43263a22 \
> --openstack-flavor-id 3 \
> --openstack-net-id 44ead515-da4b-443b-85cc-a5d13e06ddc85 \
> --openstack-sec-groups machine \
> --openstack-ssh-user ubuntu \
> u1
Docker Machine Version:  0.6.0-dev, build
...
Error setting machine configuration from flags provided: Either Network name or Network id must be specified, not both
```

```
$ ./bin/docker-machine-Darwin-x86_64 --debug create \
> --driver openstack \
> --openstack-image-id 98011e9a-fc46-45b6-ab2c-cf6c43263a22 \
> --openstack-flavor-id 3 \
> --openstack-net-name mynet05 \
> --openstack-sec-groups machine \
> --openstack-ssh-user ubuntu \
> u1
Docker Machine Version:  0.6.0-dev, build 
...
Creating machine...
(u1) Calling .Create
(u1) DBG | Authenticating... map[AuthUrl:http://172.18.184.20:5000/v2.0 Insecure:true DomainID: DomainName: Username:fsoppelsa TenantName:fsoppelsa TenantID:f6659e8899e24eeaa717c8f8fbbe0e50]
(u1) DBG | Found network id using its name map[Name:mynet05 ID:44ead515-da4b-443b-85cc-a5d13e06ddc8]
(u1) DBG | Found floating IP pool id using its name map[Name:public ID:095f43ed-65ba-48ce-8185-d4080e430a88]
(u1) DBG | Creating Key Pair... map[Name:u1-a6dfb9dd0729523b1eb28caf0037c16518c494f4e2e5435a91602db4cdc50b12]
(u1) DBG | Creating OpenStack instance... map[FlavorId:3 ImageId:98011e9a-fc46-45b6-ab2c-cf6c43263a22]
(u1) Creating machine...
```

Multiple networks separated by comma:

```
$ ./bin/docker-machine-Darwin-x86_64 --debug create \
> --driver openstack \
> --openstack-image-id 98011e9a-fc46-45b6-ab2c-cf6c43263a22 \
> --openstack-flavor-id 3 \
> --openstack-net-id 44ead515-da4b-443b-85cc-a5d13e06ddc85,0cd5eef9-523e-48cd-8a95-5dbc39bc1aa2 \
> --openstack-sec-groups machine \
> --openstack-ssh-user ubuntu \
> u1
Docker Machine Version:  0.6.0-dev, build 
...
Error setting machine configuration from flags provided: Either Network names or Network ids must be specified, not both
```

**Comment by robertjustjones** [comment]
Please see the related comments in #1444.

**Comment by fsoppelsa** [comment]
Yes this is GO for me.

**Comment by nathanleclaire** [comment]
LGTM thanks all

**Comment by dgageot** [comment]
@robertjustjones, @nathanleclaire, @fsoppelsa Did you test the compatibility with previously created machines? As I said to @robertjustjones, changing field names/types in `Driver` struct can have random effects.

**Comment by fsoppelsa** [comment]
@dgageot I just tried to remove an old machine created with 0.5.2 and it worked. How could this new feature (adding more networks in creation) impact old machines?

**Comment by robertjustjones** [comment]
@dgageot I see now what you're referring to. I thought only the switches were public, but I see now that filestore.go is json-ifying the Driver. I'll see if I can break it. LMK if you suspect a particular sequence that might fail.

**Comment by nathanleclaire** [comment]
Ah, @dgageot is right -- My fault, I think we will need to revert this PR and revisit the changes to the Driver struct.  In its current form it _will_ break existing machines.

The main problematic bit is changing the name and type of `NetworkNames` and `NetworkIds` fields.  When the client goes to send over the existing JSON to this new driver, the payload will deliver a `NetworkName` and `NetworkId` field which don't have any analogue in the new driver.  Consequently that information will be lost and any operations which rely on these fields will fail.

**Comment by nathanleclaire** [comment]
We should probably have automated tests that break when changing values in the Driver structs, but I'm not sure how that would be possible.

**Comment by nathanleclaire** [comment]
Alright, here's the plan:

- I'm going to revert this commit in master
- @robertjustjones I ask that you please open a new PR and we'll figure out how to integrate these changes in a non-breaking way.

Thanks!

**Comment by robertjustjones** [comment]
Sounds good @nathanleclaire.  Thanks.

**Comment by rvion** [comment]
Does anyone knows the state of this ?

Is it now possible to create an OpenStack machine with either multiple --openstack-net-id switches or one --openstack-net-id param with coma-separated list of networks ?

**Comment by fsoppelsa** [comment]
@robertjustjones did you open a new PR?

**Comment by FlorianLudwig** [comment]
@robertjustjones I guess this PR is dead?

**Comment by sagar-chandarana** [comment]
is this functional?

Currently I am getting an error. No interface found with name 'vlan,Ext-Net'

docker-machine v0.13.0, build 9ba6da9.
driver/hosts: Openstack Nova on OVH

**Pull request merged**
