### PR TITLE
exoscale: fix driver hanging on failed VM operation

### PR DESCRIPTION
**Pull request by janeczku**
Fixes the following issue:   
The exoscale driver does not evaluate correctly the job status of API commands. 
If any job has failed on exoscale's side (e.g. creating new instance) it will not raise the error and instead continue polling the status for the next 2 minutes until `d.waitForVM()` times out.

/cc @pyr

### CODE REVIEW

**Comment by ehazlett** [comment]
@janeczku this needs a rebase.  thanks!

**Comment by vincentbernat** [comment]
The change is quite invasive just to raise an error if `resp.JobStatus == 2`. If you want to cleanup the code style, maybe use separate commits?

**Comment by janeczku** [comment]
@vincentbernat it was just to tempting seeing we could reduce API queries by a factor of 2 (beware the rate limit) ;) Seeing you are uncomfortable with it, i will revert the refactoring and just push the job status eval.

**Comment by vincentbernat** [comment]
Oh, I didn't realize that the number of API queries was divided by 2. My point was only that the original commits contained many changes: logging changes, refactoring and the bug fix. I was just wishing to have a separate commit for the bug fix. Feel free to resubmit the remaining bits in another PR.

@ehazlett LGTM

**Comment by janeczku** [comment]
@vincentbernat :+1:

**Pull request merged**
