### PR TITLE
Golint cleanup

### PR DESCRIPTION
**Pull request by knarz**
repeat of #862

Hey,

I just spent a rather boring train ride reading through the code and doing some cleanup with golint. This first PR is just getting all the low hanging fruit, i.e. fixing variable names and a first effort towards closing #847 .
The bigger task is most likely going to be writing all the comments to make golint happy.

Signed-off-by: Sascha Hanse <shanse@gmail.com>

### CODE REVIEW

**Comment by ehazlett** [comment]
Thanks for going through this!  Would you mind rebasing?

**Comment by knarz** [comment]
Should be fine now.

**Comment by ehazlett** [comment]
These LGTM.  Since it touches quite a bit of code, could we get a few more sets of eyes on this?

/cc @sthulb @nathanleclaire

**Comment by ehazlett** [comment]
@nathanleclaire would you mind taking a look at this as well.  it's a large refactor and I don't want to be the only one that reviews it.  thx

**Comment by nathanleclaire** [comment]
- [ ] amazonec2/
- [ ] azure/
- [ ] digitalocean/
- [ ] fakedriver/
- [ ] google/
- [ ] hyperv/
- [ ] none/
- [ ] openstack/
- [ ] rackspace/
- [ ] softlayer/
- [ ] virtualbox/
- [ ] vmwarefusion/
- [ ] vmwarevcloudair/
- [ ] vmwarevsphere/

**Comment by nathanleclaire** [comment]
Alright the above list has been updated to the best of my ability to indicate which drivers still wait for SSH vs. which drivers don't.

**Comment by nathanleclaire** [comment]
Dang it, wrong issue, sorry.

**Comment by nathanleclaire** [comment]
What's the justification for the change?  i.e. How is this going to make the code more maintainable?  Since it is touching almost every part of the code, it most assuredly will mean that any existing PRs (if they managed to survive the recent `libmachine` changes) will be that much more difficult to rebase and update to the latest.

I appreciate the contribution @knarz, and I actually would rather have most of these changes than not, but I have to say the potential downsides seem to outweigh the positive for me.

Maybe we could start smaller, like on a per-driver basis?  For instance, I'd really like those VMware changes as naming Go variables `LIKE_THIS` is a pretty flagrant style violation.

**Comment by ehazlett** [comment]
@knarz this is probably the best route as @nathanleclaire mentioned.  this is quite a bit of changes and would be best to split up since it touches so many pieces.  the changes looked good -- we just would be better to do in small chunks.  thanks again for the work and contribution!

**Pull request closed without merging**
