### PR TITLE
Fixes for on-premise EC2 endpoints

### PR DESCRIPTION
**Pull request by bgokden**
Signed-off-by: Berk Gokden <berk.gokden@gmail.com>

### CODE REVIEW

**Comment by jeanlaurent** [comment]
@bgokden The aws driver has been significantly changed by #2684, would you mind rebasing your work on it ?

**Comment by bgokden** [comment]
Sorry I am abondon'ing it since some of this functionality moved to aws-sdk-go.

**Comment by bgokden** [comment]
I will fix the git sign-off and test issue. Sorry when I first did this I did not know amending updates the existing PR.

**Comment by jeanlaurent** [comment]
@bgokden It seems you changed your mind, is this ready for review ?

**Comment by bgokden** [comment]
Yes, I have changed my mind to give it a try. I have realized aws-sdk-go has options to change endpoint and disabling SSL. So I have added options to pass variables to this settings. Also disabled the region checking when custom endpoint used since this endpoint could have a custom region. I have tested this with the internal company cloud. I was able to connect to the endpoint.

**Comment by dgageot** [comment]
Hi @bgokden, can you please rebase your PR?

**Comment by dgageot** [comment]
Hi @bgokden Did you get time to rebase?

**Comment by bgokden** [comment]
@dgageot I have rebased at Jan 5 after you told me to rebase. I hope there is no conflict now.

**Comment by dgageot** [comment]
@bgokden Sorry there are... The amazon driver got some attention lately and each merge is likely to break other PRs. So if you could do the rebase once again that would make it possible for us to test and merge.

**Comment by dgageot** [comment]
Hey @bgokden did you get a change to rebase the PR?

**Comment by nathanleclaire** [comment]
Going to close this due to inactivity. @bgokden thanks for your contributions and please feel free to submit a new PR or re-open this one if you get some time to rebase it.

**Comment by eyal-stratoscale** [comment]
+1
Would like those flags in the command line.
Couldn't find how to configure it otherwise.
Thanks

**Comment by bgokden** [comment]
@eyal-stratoscale I created a new pull request after rebase 
https://github.com/docker/machine/pull/3675

**Pull request closed without merging**
