### PR TITLE
Fix network timeout preventing machine creation

### PR DESCRIPTION
**Pull request by nathanleclaire**
On an airplane, I attempted to create a machine using the VBox driver,
forgetting that we actually presume that network is available for a call
to Github to get the latest boot2docker release.

Users should not need to have access to the Internet in order to use
local drivers.  This fixes the issue and makes creation of a VM without
network connectivity possible :thumbsup:

cc @ehazlett @bfirsh @sthulb 

(To test this try disabling WiFi and running through `machine create -d virtualbox dev` before and after the patch)

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by ehazlett** [comment]
Related to https://github.com/docker/machine/pull/437 and https://github.com/docker/machine/pull/441.

I'm up for closing mine but I'm not sure grep'g the error is the way to go.

**Comment by sthulb** [comment]
I prefer this over #435 (--ignoreISOUpdate).

**Comment by nathanleclaire** [comment]
@ehazlett Ah, I didn't see that.  Actually I like yours better in general (it's cleaner and covers other drivers) - but let's make sure to add some code to bail in the case that no local `.iso` exists and the network times out.  Otherwise we try to careen into an ISO download that won't work.

**Comment by sthulb** [comment]
#437 seems nicer still.

**Comment by ehazlett** [comment]
Ah thanks :)  Good idea -- I'll update for that.

**Comment by ehazlett** [comment]
Closing.  Will track this fix in #437.

**Pull request closed without merging**
