### PR TITLE
Simplify introduction to docs

### PR DESCRIPTION
**Pull request by bfirsh**
This is going to be the landing page for people finding out about Machine, so it needs to be to the point. I don't think this is the right place to explain *why* you need a Docker daemon.

Saying that - this is a start. Perhaps a bit more information could go in this introduction. @ehazlett @fredlf - thoughts?

### CODE REVIEW

**Comment by fredlf** [comment]
LGTM ping @spf13 @moxiegirl

**Comment by spf13** [comment]
@bfirsh I made a couple comments. Looks good overall.

**Comment by ehazlett** [comment]
@bfirsh +1 for simplifying docs :)

also +1 to @spf13 comments.

**Comment by SvenDowideit** [comment]
sorry @bfirsh I renamed the userguide to index.md so it becomes the `http://docs/machine/` link.

**Comment by bfirsh** [comment]
Updated with @spf13's feedback.

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
