### PR TITLE
Handle bad netmask returned by virtualbox after hostonlyif creation. Fixes #1843

### LINKED ISSUE #1843: Duplicate host only adapters created when creating a VM with virtualbox, VM creation hangs
##### Description of problem:
I'm running the latest Docker Toolbox (1.8.2) on Windows 10
When creating my first VM docker-machine creates 2 network adapters, the 2nd one gets assigned to the vm with garbage settings and create process hangs.

##### The culprit
It appears that there is significant latency from when a `hostonlyif` is created to being able to accurately query `hostonlyifs`. When docker-machine checks to see if there is an already created `hostonlyif` the netmask returned from `list hostonlyifs` doesn't match the expected netmask, instead we see a value of 15.0.0.0. This causes docker-machine to create a 2nd `hostonlyif`.

I'm not sure if this a bug in virtualbox or just a quirk we'll have to deal with.

##### Environment details (AWS, VirtualBox, physical, etc.):
Windows 10. Docker Toolbox 1.8.2

##### How reproducible:
Very reproducible

##### Steps to Reproduce:
1. Start with a fresh Docker Toolbox install. 
2. Remove all VM's and orphaned host only adpaters in VirtualBox
3. Attempt to create the default vm with docker quickstart,kitematic, or docker-machine

##### Actual Results:
VM creation hangs and two host only network adapters are created
here's the docker-machine create with debug
http://pastebin.com/raw.php?i=i868Tt7c

##### Expected Results:
VM creation to succeed with only one host only adapter

### PR DESCRIPTION
**Pull request by rwilliams**

### CODE REVIEW

**Comment by nathanleclaire** [comment]
If you rebase to master the grumpy CircleCI build should be fixed.

**Comment by rwilliams** [comment]
Thanks

**Comment by nathanleclaire** [comment]
Could I get you to write a unit test for the condition that this change is testing for?

**Comment by rwilliams** [comment]
I'm pretty sure if I could get the integration tests to run on my Windows 10 machine we'd see some failures. What this change is testing for is the following bug in Virtualbox

```
vboxmanage hostonlyif create && vboxmanage list hostonlyifs
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interface 'VirtualBox Host-Only Ethernet Adapter #3' was successfully created
Name:            VirtualBox Host-Only Ethernet Adapter #3
GUID:            336f5edf-a838-43a1-a55f-7955e605ee59
DHCP:            Enabled
IPAddress:       192.168.56.1
NetworkMask:     15.0.0.0
IPV6Address:     fe80:0000:0000:0000:384b:5e06:3257:bdb1
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3
```

The network mask on a newly created host only adapter if always returns 15.0.0.0, if list `hostonlyifs` is called right away, which leads to docker-machine creating a 2nd host only adapter and breaking the vm creation process

**Comment by nathanleclaire** [comment]
Mm, rough.  So this fixes the issue by allowing Machine to correctly detect the created host only network?

**Comment by rwilliams** [comment]
Correct.

**Comment by nathanleclaire** [comment]
OK great, I have written some tests for this and the surrounding code and I'm going to make a PR to your repo that you should merge in for this PR.

**Comment by nathanleclaire** [comment]
Please merge: https://github.com/rwilliams/machine/pull/1/files

After that, LGTM

**Comment by rwilliams** [comment]
Awesome

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
