### PR TITLE
Add ENGINE_REGISTRY_MIRROR env var support.

### PR DESCRIPTION
**Pull request by davemkirk**
#3025 - $ENGINE_REGISTRY_MIRROR environment variable?

Signed-off-by: David Kirk <davemkirk@gmail.com>

### CODE REVIEW

**Comment by davemkirk** [comment]
It looks like my pull request is failing the build/tests because of a change I made to `/docs/reference/create.md` and I have no idea why :-/  

What am I missing here?

**Comment by jeanlaurent** [comment]
It could be a markdown linting related error, or just the docs buils, who goes kaboom more often that we would admit.

retest this please

**Comment by jeanlaurent** [comment]
test this please

**Comment by jeanlaurent** [comment]
Sounds like the build failed again, even after a trigger.
I'll investigate if this is a markdown lint error.

**Comment by jeanlaurent** [comment]
@SvenDowideit the docs build is failing, can you help us pinpoint the issue ?
It's not a markdown linting, and re-triggering the build does not help.

**Comment by jeanlaurent** [comment]
test this please

**Comment by jeanlaurent** [comment]
test this please

**Comment by dmp42** [comment]
LGTM

**Comment by SvenDowideit** [comment]
docs were failing due to the docker/tutorials repo going private - a rebase after fixing that should have resolved it.

**Pull request merged**
