### PR TITLE
Refactor out common logic in UbuntuProvisioner

### PR DESCRIPTION
**Pull request by ibuildthecloud**
This change create GenericProvisioner which is the boilplate or generic Linux functionality that was previously in the UbuntuProvisioner.  This work was done to make it easier to add and maintain RancherOS support.  #1096 was created for RancherOS support that uses this PR.

### CODE REVIEW

**Comment by ehazlett** [comment]
LGTM

also, tested with Ubuntu (DO, EC2) - works as expected

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
:tada: :confetti_ball: :tada:

**Pull request merged**
