### PR TITLE
FIX #3056 ls timeout when instance is stopped

### LINKED ISSUE #3056: docker-machine ls: Timeout error when instance has been stopped
> $ docker-machine ls

```
NAME              ACTIVE   DRIVER       STATE     URL                        SWARM   DOCKER    ERRORS
node01            -        openstack    Running   tcp://92.XXX.XXX.204:2376           v1.9.1
```

> $ docker-machine stop node01

```
Stopping "node01"...
Machine "node01" was stopped.
```

> $ docker-machine ls

```
NAME              ACTIVE   DRIVER       STATE     URL                        SWARM   DOCKER    ERRORS
node01            -        openstack    Timeout  
```

This is obviously doomed to fail, with commit 670c4808ed8abdc80d4a71444b10df5360bed62b assuming incorrectly that when the driver returns the URL it means that the machine is running.

https://github.com/docker/machine/blob/master/commands/ls.go#L343-L347

/cc @dgageot 

**Version Info:**
docker-machine version 0.6.0, build e27fb87

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
@jeanlaurent I extracted the duplicated code

**Comment by nathanleclaire** [comment]
LGTM -- Travis is stalled and I'm not sure why

**Comment by nathanleclaire** [comment]
```
Bad response status from coveralls: 500 - {"message":"Coveralls is in Read Only mode while we work on updating the system. Sorry for the inconvenience.Check Status: http://status.coveralls.io/","error":true,"url":""}
```

Ugh, Coveralls.

**Comment by nathanleclaire** [comment]
I'm testing and I don't see any issues.  I'm willing to give it a shot, will probably carry this in another PR due to the Travis failure (not sure how to re-run the Travis build)

**Pull request merged**
