### PR TITLE
#3191 add zsh completion

### LINKED ISSUE #3191: Needs zsh autocompletion
This project has bash completions, but not zsh completions. Zsh completions would be greatly appreciated. :)

### PR DESCRIPTION
**Pull request by leonhartX**
fix #3191 
Add zsh completion for docker-machine.
Although there is an docker-machine zsh completion here: https://github.com/zsh-users/zsh-completions/blob/master/src%2F_docker-machine
it seems to be bit out-of-date, and not so convenience as the _docker and _docker-compose completion. 
I wrote this one to support more completion function like pick up the `swarm master`, find `swarm-discovery`, automated add driver options like `--amazonec2-ami` after set `--driver|-d` option( `-d amazonec2`)

But I haven't test all driver options, since i don't have all these cloud environment. If there is anything wrong, please feel free to tell. thanks.

Hope this will be helpful :)

Signed-off-by: Ke Xu <leonhartx.k@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Thanks!  Will test this out when I get a chance.

Have you given any thought to doing something like grepping the help text per-driver instead, so that we wouldn't have to update this when new flags are added and (inevitably) forget?

**Comment by leonhartX** [comment]
@nathanleclaire Thanks for the advise.
It's a bit difficult since I have specified which option can be multiple, and which option must have a argument manually.
But maybe this feature is not so important to keep so I will give a try.

**Comment by leonhartX** [comment]
@nathanleclaire I have made a change to grep text for driver options. this should work with new new flags and even new drivers I think.

**Comment by nathanleclaire** [comment]
Will you please add some installation docs like there are for the Bash autocompletion scripts?

**Comment by nathanleclaire** [comment]
`docs/completion.md` is the file I think

**Comment by leonhartX** [comment]
Add the installation docs for it.(just using the comment out contents and fix some path).

**Comment by SvenDowideit** [comment]
docs LGTM - @thaJeztah ?

**Comment by thaJeztah** [comment]
docs LGTM, thanks!

**Comment by nathanleclaire** [comment]
LGTM

Thanks @leonhartX !

**Pull request merged**
