### PR TITLE
More docs validation fixes

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

@nathanleclaire @sfsmithcha 

there should only be one remaining error report for a file in registry/distribution - which only happens due to GH's svn stuff failing when hub builds `docs/base:oss` (so ignore for now)

### CODE REVIEW

**Comment by nathanleclaire** [comment]
FIX YOUR BUILD PLZ SVEN

**Comment by SvenDowideit** [comment]
retest this please

**Comment by londoncalling** [comment]
LGTM

**Comment by londoncalling** [comment]
LGTM

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
