### PR TITLE
Add support for Ohio (us-east-2)

### PR DESCRIPTION
**Pull request by jloisel**
I've added the new Ohio (us-east-2) zone and updated all AMIs to latest 16.04.1LTS (20161013).

> ap-northeast-1	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-31892c50	hvm
ap-southeast-1	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-18e7417b	hvm
eu-central-1	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-597c8236	hvm
eu-west-1	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-c593deb6	hvm
sa-east-1	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-909b06fc	hvm
us-east-1	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-fd6e3bea	hvm
us-west-1	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-73531b13	hvm
cn-north-1	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-d7c511ba	hvm
us-gov-west-1	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-8df24aec	hvm
ap-southeast-2	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-7be4d618	hvm
us-west-2	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-f1ca1091	hvm
us-east-2	xenial	16.04 LTS	amd64	hvm:ebs-ssd	20161013	ami-0a104a6f	hvm

Signed-off-by: Jerome Loisel <loisel.jerome@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
looks good just re-running travis due to upstream error

**Comment by jloisel** [comment]
Please double check i've not made a mistake when taking AMIs from Ubuntu's page. It's easy to make an error when copy / pasting the AMI id.

**Comment by nathanleclaire** [comment]
K.

PR needs `gofmt`.

**Comment by jloisel** [comment]
gofmt ?

**Comment by nathanleclaire** [comment]
Travis complain about `fmt`:

```
make: *** [fmt] Error 1
mk/validate.mk:12: recipe for target 'fmt' failed
make: *** [build validate] Error 2
```

**Comment by jloisel** [comment]
Is it a formatting issue? Sorry i'm not a Go expert :)

**Comment by nathanleclaire** [comment]
You need to run [`gofmt`](https://golang.org/cmd/gofmt/) on the code.  I'm not sure why (whitespace maybe) but it's failing validation for that in our CI.

**Comment by jloisel** [comment]
Ran gofmt on the modified file, no change:
> ubuntu@desktop:~/git/machine$ gofmt -d -w drivers/amazonec2/region.go

This outputs nothing.

**Comment by jloisel** [comment]
Fixed in latest commit :)

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
Thanks!

**Pull request merged**
