### PR TITLE
fix debian provisioning bug with systemd

### LINKED ISSUE #1705: Provisioning fails on Debian
The following is occurring with Debian (tested on DigitalOcean):

```
ejh-x1:ehazlett ~> docker-machine create -d digitalocean --digitalocean-image debian-8-x64 mcn-test
Creating SSH key...
Creating Digital Ocean droplet...
Error creating machine: Something unexpected went wrong running an SSH command!
command : sudo systemctl enable docker
err     : exit status 1
output  : Synchronizing state for docker.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d docker defaults
Executing /usr/sbin/update-rc.d docker enable
Failed to execute operation: File exists


You will want to check the provider to make sure the machine and associated resources were properly removed.
```

The provisioning actually works and Docker is accessible.  There is just an error because it appears Docker is enabled.

### PR DESCRIPTION
**Pull request by ehazlett**
This fixes the systemd provisioning issue with Debian.

Fixes #1705

### CODE REVIEW

**Comment by nathanleclaire** [comment]
LGTM

**Comment by anthonydahanne** [comment]
Hello, still experiencing the issue with latest docker-machine : 

    docker-machine -v
    docker-machine version 0.4.1 (e2c88d6)

In which release this fix will be available ?
thanks a lot !

**Comment by zedtux** [comment]
Same as @anthonydahanne, I'm encountering the same issue with the same version `version 0.4.1 (e2c88d6)`

**Comment by dgageot** [comment]
@anthonydahanne @zedtux Can you try with 0.5.1?

**Comment by zedtux** [comment]
@dgageot it's working fine with version 0.5.1. :+1:

**Comment by dgageot** [comment]
Thanks!

**Pull request merged**
