### PR TITLE
VMware host drivers for Fusion, vSphere and vCloud Air

### PR DESCRIPTION
**Pull request by frapposelli**
Hello! this is a porting of what was bfirsh/docker#20 

I added support for identity auth all across the board and the previous notes are still valid:

- vSphere driver depends on vmware/govmomi/govc (must be in path) and works with vmware/govmomi@c8486300bfe19427e4f3226e3b3eac067717ef17 
- vCloud Air driver introduces a dependency on vmware/govcloudair@1df64d51cbbac795bdeeab8b4030cdf2e0471ccd (updated Godeps for this)

Thanks!

### CODE REVIEW

**Comment by pandrew** [comment]
An ESXi hypervisor and vsphere server running on the hypervisor should be sufficient to test both right?

**Comment by vovimayhem** [comment]
+1 :)
(*If you're interested in following the PR upstream (and give us a +1)*)

**Comment by frapposelli** [comment]
@bfirsh I will rebase next week when I'm back from the winter break, as for the testing, you'll need an ESXi box at the very least (even the free license should do the trick).

**Comment by sthulb** [comment]
This probably will need to be updated to reflect changes I made in #219

**Comment by frapposelli** [comment]
@sthulb I'm rebasing the drivers against the most recent master commit right now, once #219 is merged I will update the drivers to reflect the change (should be pretty straightforward).

**Comment by frapposelli** [comment]
@bfirsh rebase done, quick changelog:

- Switched provider names to `vmware<drivername>`, now we have `vmwarefusion` `vmwarevsphere` and `vmwarevcloudair`
- Moved the providers to the new `codegansta/cli` package, cli flags follow the `--vmware<driver>-<option>` convention, env vars are shorter with just `<DRIVER>_<OPTION>` (mimicked the AWS behavior for that)
- Rewrote history for correct attribution to the original authors of the drivers.

Tested with `script/run-integration-tests` succesfully:

```shell
MACHINE_TESTS="vmwarefusion vmwarevsphere vmwarevcloudair" ./script/run-integration-tests
=== RUN TestMachineCreate
 - testing create for vmwarefusion (machine-integration-test-vmwarefusion)
 - testing create for vmwarevsphere (machine-integration-test-vmwarevsphere)
 - testing create for vmwarevcloudair (machine-integration-test-vmwarevcloudair)
--- PASS: TestMachineCreate (278.62 seconds)
=== RUN TestMachineStop
 - testing stop for vmwarefusion (machine-integration-test-vmwarefusion)
 - testing stop for vmwarevsphere (machine-integration-test-vmwarevsphere)
 - testing stop for vmwarevcloudair (machine-integration-test-vmwarevcloudair)
--- PASS: TestMachineStop (19.09 seconds)
=== RUN TestMachineStart
 - testing start for vmwarefusion (machine-integration-test-vmwarefusion)
 - testing start for vmwarevsphere (machine-integration-test-vmwarevsphere)
 - testing start for vmwarevcloudair (machine-integration-test-vmwarevcloudair)
--- PASS: TestMachineStart (27.68 seconds)
=== RUN TestMachineKill
 - testing kill for vmwarefusion (machine-integration-test-vmwarefusion)
 - testing kill for vmwarevsphere (machine-integration-test-vmwarevsphere)
 - testing kill for vmwarevcloudair (machine-integration-test-vmwarevcloudair)
--- PASS: TestMachineKill (9.29 seconds)
=== RUN TestMachineRemove
 - testing rm for vmwarefusion (machine-integration-test-vmwarefusion)
 - testing rm for vmwarevsphere (machine-integration-test-vmwarevsphere)
 - testing rm for vmwarevcloudair (machine-integration-test-vmwarevcloudair)
--- PASS: TestMachineRemove (70.13 seconds)
PASS
ok      github.com/cloudnativeapps/machine/_integration-test    404.824s
```

**Comment by sthulb** [comment]
@frapposelli certainly. I don't care about the order of the PRs being accepted, it was more of a heads up

**Comment by frapposelli** [comment]
@sthulb thanks! :+1:

**Comment by ehazlett** [comment]
@frapposelli awesome!  huge thanks!  i'm testing this today.

**Comment by ehazlett** [comment]
@frapposelli this is awesome.  do you think you could include a rough outline of what you are doing to create the custom b2d iso with vmtools?

**Comment by frapposelli** [comment]
@ehazlett the b2d iso is built from cloudnativeapps/boot2docker@8ff8eb3fedd262012a857d32a13746e750188c35

Main differences from the master b2d branch are:

- Docker with identity auth
- VMware tools installed (see: boot2docker/boot2docker#638)
- A patch to do `mkfs` on the first empty block device found regardless of the magic string (see: boot2docker/boot2docker#659)

That's pretty much it, for the third point, I'm currently working on a Go package to write raw content into a VMDK, this should give us a way to port the same seeding technique used with virtualbox.

**Comment by ehazlett** [comment]
awesome.  thanks!

**Comment by ehazlett** [comment]
LGTM

**Comment by pandrew** [comment]
Nice!!! Thnx

**Comment by sthulb** [comment]
:tada: Thanks to everyone involved!

**Pull request merged**
