### PR TITLE
Remove completely broken vmware fusion driver

### PR DESCRIPTION
**Pull request by geek**
Bugs are one thing, being completely broken is another.  See https://github.com/docker/machine/labels/driver%2Fvmwarefusion and https://github.com/docker/machine/issues/1671

Does the vmware fusion driver work for anyone on El Capitan with fusion 8 other than someone from the vmware or docker team?

### CODE REVIEW

**Comment by MSch** [comment]
I got it to work after various trials and errors and trying random stuff from the issue comments  `¯\_(ツ)_/¯`

**Comment by geek** [comment]
@MSch thanks, so it didn't work out of the box for you either.

**Comment by dgageot** [comment]
Hey, I'm part of docker team and yes, the driver works for me out of the box. Fusion 8, El Capitan. 
Let me some time tomorrow CET to analyze your feedback and let's try fixing what needs to be fixed

**Comment by mikew** [comment]
It didn't work for me out of the box, but it was only permissions. I've been using [this bash function](https://gist.github.com/mikew/66e15a8be8eaf7d6043c) and it has worked on 3 machines and many installs.

**Comment by geek** [comment]
@dgageot appreciate it... I purchased fusion for the sole purpose of using it for docker... has never worked for me without some additional hacking of permissions and scripts...even then it doesn't work consistently.

I first tried with fusion 7 pro on yosemite, no luck.  Then I tried with fusion 8 pro on yosemite, no luck.  Then I tried with fusion 8 pro on el capitan, no luck.  Docker machine with the VirtualBox driver works great on all of those environments... seeing that just about everyone else and their parents are having issues using the vmware fusion driver led me to open this PR.  /cc @frapposelli

**Comment by dmp42** [comment]
+ cc @docker/machine-maintainers

**Comment by frapposelli** [comment]
@geek the driver has been in the tree for 11+ months, and countless people are using it daily (including myself and my team) out of the box.

I understand your frustration and I'm trying to help, I'm positive that the issue you're facing is not related to the `docker-machine` driver at all, that's why I suggested people in #1671 to open up an SR against Fusion to track the problem.

**Comment by geek** [comment]
@frapposelli even if the issue isn't in the driver itself, the driver doesn't work when the accompanying software doesn't work.  Until that part is resolved, docker-machine shouldn't advertise that it supports vmware fusion.... otherwise the docker team will end up maintaining and supporting broken software that they had no part in.  Its just a giant lose-lose situation for users of docker-machine and maintainers of docker-machine to keep fusion in.

**Comment by nathanleclaire** [comment]
The VMware Fusion driver, as @frapposelli noted, has worked perfectly well for a long time and Fabio has gone above and beyond the call of duty to maintain it.  Submitting a pull request to remove a driver completely because it isn't working for you is emphatically inappropriate and unproductive.  Please file and/or comment on issues to help debug the problem instead in a productive manner in the future.

**Comment by geek** [comment]
@nathanleclaire not just me, many many other people as well.  I also submitted workarounds for the issue, trying to help others as well... If you look at the issue I linked to you can see that I have been working on this issue for months, trying to get it resolved, this isn't a knee jerk PR.  

That being said, your closing this PR is fine... but do not accompany it with accusatory language... I am trying to help and to make docker-machine a more useful tool... sometimes that can involve removing broken features.

**Pull request closed without merging**
