### PR TITLE
Support Static IPs and Preemptible instances on Google Compute Engine

### PR DESCRIPTION
**Pull request by dgageot**

### CODE REVIEW

**Comment by dgageot** [comment]
@jeffmendoza do you find this PR useful? Are there things I can improve?

**Comment by jeffmendoza** [comment]
Preemptable worked. Static IP worked only if I provided the IP and not the "name" of the IP, which is what I'm used to with gcloud:

     --address ADDRESS
        Assigns the given external address to the instance that is created. The
        address may be an IP address or the name or URI of an address resource.
        This option can only be used when creating a single instance.

Would be nice, but not a must have.

**Comment by dgageot** [comment]
I must admit I was lazy on this one. It does the job so...
I'll try to improve it if you think it's worth it

**Comment by jeffmendoza** [comment]
Up to you

**Comment by dgageot** [comment]
@jeffmendoza I've rebased the commits

**Comment by dgageot** [comment]
@jeffmendoza I've added resolving static address by name

**Comment by jeffmendoza** [comment]
nice!

**Comment by dgageot** [comment]
@jeffmendoza Can I improve something to make the PR more likely to be merged?

**Comment by jeffmendoza** [comment]
Looks good to me, let's ping @ehazlett or @nathanleclaire

**Comment by ehazlett** [comment]
LGTM

**Comment by dgageot** [comment]
Thank you. Where can I update the documentation?

**Comment by nathanleclaire** [comment]
@dgageot I think the doc relevant for you here is `docs/drivers/gce.md`

**Comment by dgageot** [comment]
Indeed. PR in progress

**Comment by dgageot** [comment]
see #1623

**Pull request merged**
