### PR TITLE
fix IPV6NetworkMaskPrefixLength value parsing

### PR DESCRIPTION
**Pull request by gmacario**
Adapted from https://github.com/boot2docker/boot2docker-cli/commit/941c70cb0137acccd36c2f8ef9426a12ddc58ef0

Signed-off-by: Gianpaolo Macario <gmacario@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Is there an issue referencing what this is fixing?  And would it be possible to persuade you to add a test for it?

**Comment by gmacario** [comment]
Hi @nathanleclaire,

> Is there an issue referencing what this is fixing?

Yes, this is https://github.com/docker/machine/issues/1692 (it was mentioned in the PR header and related commit)

> And would it be possible to persuade you to add a test for it?

I would love to but not sure if/how I can make an automatic test.
Is there any guidance for writing tests on https://github.com/docker/machine

Otherwise if manual tests are OK, this is already documented inside https://github.com/docker/machine/issues/1692

just do `docker-machine start default` on a host where `VBoxManager list hostonlyifs` returns something like

```
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            4144ae2b-c3dd-4d35-b342-5802587c30d9
DHCP:            Disabled
IPAddress:       172.17.8.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:f8aa:323e:9bc0:9cc4
IPV6NetworkMaskPrefixLength: 128
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
```

(the key point is `128` in line `IPV6NetworkMaskPrefixLength: 128`)

**Comment by gmacario** [comment]
Hello @nathanleclaire,

Any chances to have this PR reviewed/merged?

Thanks in advance!

Gianpaolo

**Comment by nathanleclaire** [comment]
I'm inclined to merge it and then write a test later when the VirtualBox mocking is improved.  LGTM

**Comment by gmacario** [comment]
Excellent, thanks!

**Pull request merged**
