### PR TITLE
New Feature: #1342 Get an internal IP of cloud hosted machine 

### PR DESCRIPTION
**Pull request by aperepel**
Functional implementation for GCE, placeholders for the rest at the moment, as discussed.

### CODE REVIEW

**Comment by aperepel** [comment]
Squashed the commits, I heard you guys like them

**Comment by aperepel** [comment]
Hi, the PR has been sitting green for over a month, now has a merge conflict. I am happy to resolve the conflict once again, but please let me know if there's a reason the PR wasn't merged (so I can address).

**Comment by dmp42** [comment]
@nathanleclaire ping

**Comment by nathanleclaire** [comment]
It's too much stuff.  Sorry @aperepel, I appreciate the effort, but features of this size and scope need to be discussed in an issue / proposal first before they will get merged in.

**Comment by nathanleclaire** [comment]
Also would like to say sorry for the lack of responsiveness prior to this!

**Comment by schickling** [comment]
This feature would be really useful. Is there any work going on in order to make this happen @nathanleclaire? :+1:

**Comment by nathanleclaire** [comment]
@schickling No current development efforts but I agree it'd be a really useful feature to have and something we will consider strongly for machine v2.

**Comment by schickling** [comment]
@nathanleclaire Is there an official roadmap for v2?

**Comment by nathanleclaire** [comment]
@schickling Nothing official so far, it's just been something I've been thinking about.

**Pull request closed without merging**
