### PR TITLE
Driver: hyper-v

### PR DESCRIPTION
**Pull request by ehazlett**
This is the rebase of @jeffmendoza PR for hyper-v.

### CODE REVIEW

**Comment by ehazlett** [comment]
@jeffmendoza can you review and comment?  thanks!

**Comment by ehazlett** [comment]
Also, tested on a server 2012 hyper-v instance and works as expected.

**Comment by jeffmendoza** [comment]
Looks great :+1:

**Comment by ehazlett** [comment]
LGTM

**Comment by jeffmendoza** [comment]
:tada:

**Comment by bfirsh** [comment]
yay \o/

**Pull request merged**
