### PR TITLE
azure: update docs with updated default param

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
Update `--azure-image` param documented that changed in

Signed-off-by: Ahmet Alp Balkan <ahmetalpbalkan@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
this `documentation` check fails very often. :)

**Comment by nathanleclaire** [comment]
Yes I can't discern real failures from false alarms in that any more

**Comment by nathanleclaire** [comment]
let's try the magic incantation...

**Comment by nathanleclaire** [comment]
test this please

**Comment by nathanleclaire** [comment]
yay the magic worked 🐰 🎩

**Pull request merged**
