### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Fangfenghua**
Signed-off-by: Fang fenghua <449171342@qq.com>

### CODE REVIEW

**Comment by Fangfenghua** [comment]
@ggiamarchi  @ehazlett  I can't find a way the fix the ci failed!  Please give me some hint.TKS

**Comment by ggiamarchi** [comment]
@Fangfenghua The signature in your commit 4725fef547d80a4575f55106bdfd6e66e4eacdd9 is wrong

You have
```
Signed-off-by: Fang fenghua 449171342@qq.com
```

It should be
```
Signed-off-by: Fang fenghua <449171342@qq.com>
```

**Comment by Fangfenghua** [comment]
@ggiamarchi  Now how can i fix it?

**Comment by ggiamarchi** [comment]
@Fangfenghua You should do an interactive rebase to rewrite the history of your branch. IMO, here the best thing you can do is to squash your 4 commits to get a single commit in your branch.

Run `git rebase -i HEAD~4`

It will open your editor and you will see the following content 

```
pick cb54e71 Update index.md
pick 4725fef Update index.md
pick ec82b26 Update index.md
pick f04c482 Update index.md

# Rebase 1ae0aac..f04c482 onto 1ae0aac
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# If you remove a line here THAT COMMIT WILL BE LOST.
# However, if you remove everything, the rebase will be aborted.
#
```

Then, edit the 4 first lines to tell to git what you want to do
```
pick cb54e71 Update index.md
f 4725fef Update index.md
f ec82b26 Update index.md
f f04c482 Update index.md
```

Save and quit. Now the rebase is done. You will see now you have only one commit corresponding to all your changes. The message commit will be the message cb54e71og which already contains a good signature.

To finish, you just have to push force the branch
```
git push --force
```

**Comment by Fangfenghua** [comment]
@ggiamarchi  I have modify the index.md on master branch, How can i rebase in this case?

**Comment by ggiamarchi** [comment]
@Fangfenghua I don't understand your last point about the master branch. Your master branch is not involved in this pull request. You just have to go on your branch `patch-6` and do the interactive rebase.

Looking at your master branch, i don't really understand what exactly you did. By the way you should just discard all you changes on this branch.

**Comment by Fangfenghua** [comment]
@ggiamarchi  I have squash the commit  as you suggestion, thanks for your guide.

**Comment by ggiamarchi** [comment]
Yes, content is right. LGTM.

**Pull request merged**
