### PR TITLE
azure: add link to Azure.com for Azure Examples

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
Linking to our docs website for Azure examples.

### CODE REVIEW

**Comment by squillace** [comment]
+1: that's a good idea, since we have that as a straightforward walkthrough already, and it points back to more docker goodness.

**Comment by ahmetalpbalkan** [comment]
and our website is more pretty 💁

**Comment by nathanleclaire** [comment]
I think we might have a policy on this to only link to docs.docker.com links.

@moxiegirl @londoncalling what do you think?

**Comment by londoncalling** [comment]
@nathanleclaire @moxiegirl we did get a specific request from @shykes to link to our own examples and tutorials in our docs. We spent some time in recent releases adding new examples, including the AWS and Digital Ocean ones in these docs. If you guys, together, come to a different decision, I'm fine with it, but right now the Azure example does break the current model, given the re-write of the Machine docs.

(also looping in @dmp42 )

**Comment by nathanleclaire** [comment]
Mm, for consistency, I think we should only link to the Docker website (we can actually take responsibility for it, for one -- we've had external links die on us before).  Feel free to write a guide for our docs though.  Thanks

**Comment by londoncalling** [comment]
Hey Nathan, I can write one too if you like. I can base it on this one or
some other , and I'll send it to you guys for review .--Vicky

**Pull request closed without merging**
