### PR TITLE
Fix for on-premise EC2 endpoints

### PR DESCRIPTION
**Pull request by bgokden**
Added option to select amazonec2-endpoint and amazonec2-insecure-endpoint.

- Disabled region checking when custom endpoint used.

Signed-off-by: Berk Gokden <berkgokden@gmail.com>

This is re based version of pull request 2535 : 
Fixes for on-premise EC2 endpoints #2535 https://github.com/docker/machine/pull/2535

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Insecure endpoint should never be set without the other option to specify the endpoint, right?  Can you please add a check and error out if user attempts to set the insecure endpoint flag without also specifying an alternative endpoint to connect o?

**Comment by jgallucci32** [comment]
A few recommendations:
* Rename the `--amazonec2-insecure-endpoint` flag to `--amazonec2-disable-ssl` to match the aws-sdk-go function WithDisableSSL. It makes it more obvious that it is a bool and not a string (endpoint implies string)
* Improve list of valid regions by adding a "custom-endpoint" region in the list with a blank ami ID rather than return any value
 * Some third-party apps like Rancher use the list to populate the region field
 * If region and endpoint are both defined, region is ignored by aws-sdk-go

**Comment by nathanleclaire** [comment]
> Rename the --amazonec2-insecure-endpoint flag to --amazonec2-disable-ssl to match the aws-sdk-go function WithDisableSSL. It makes it more obvious that it is a bool and not a string (endpoint implies string)

If the concern is around conflating bool and string, maybe we can call it something like `--amazonec2-insecure-transport`, but I feel strongly that since it is insecure it should be called out as such

**Comment by bgokden** [comment]
@nathanleclaire I have chosen amazonec2-disable-ssl. Also made some adjustments since region is ignored by aws-sdk-go when endpoint is used. I also realized there is a regionzone variable which is actually just available  zone when custom endpoint is used, so I set region to "" when endpoint is set.

**Comment by nathanleclaire** [comment]
Let's please go with `--amazon-insecure-transport`

**Comment by bgokden** [comment]
@nathanleclaire I changed it to --amazonec2-insecure-transport

**Comment by nathanleclaire** [comment]
LGTM 👍

**Comment by nathanleclaire** [comment]
Thanks for your contribution @bgokden

**Comment by bgokden** [comment]
@nathanleclaire Thank you.

**Pull request merged**
