### PR TITLE
Add SSH key generation

### PR DESCRIPTION
**Pull request by sthulb**
This should help with #852. We no longer would need to shell out to ssh-keygen.

### CODE REVIEW

**Comment by ehazlett** [comment]
Nice!

This needs a `godep save` followed by a `git add Godeps` to update and vendor the `crypto/ssh` depends.  

I'm getting prompted for `docker@localhost` and `root@xxx.xxx.xxx.xxx` passwords when creating virtualbox and DO machines.

**Comment by sthulb** [comment]
@ehazlett Done.

**Comment by nathanleclaire** [comment]
Rockin' -- definitely want to test this out when I get a chance

**Comment by ehazlett** [comment]
I will test this again as soon as I get back and have access to my windows machine as well :)  Thanks!

**Comment by sthulb** [comment]
@ehazlett can we merge this? :)

**Comment by ehazlett** [comment]
@sthulb testing today :)

**Comment by nathanleclaire** [comment]
Code looks pretty good.

I've been testing this today (tried VirtualBox and EC2) and it's working seamlessly so far.

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
