### PR TITLE
Add CommandLine interface for commands

### PR DESCRIPTION
**Pull request by dgageot**
Introduce an interface for the commands' command line.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Hm, how about let's start with just transitioning the existing `cli.Context` struct into an interface and getting some tests for those?  I don't think that injecting hosts directly into the commands is the correct solution, since you might want to parse some information from the context (e.g. arguments are machine names) in order to get hosts.  The libmachine interface I mentioned would allow you to query the store to do so instead of having each command create their own.

**Comment by dgageot** [comment]
@nathanleclaire I think your are right. I wanted to try in this direction but was not happy with how it turned out.

**Comment by nathanleclaire** [comment]
@dgageot Are you going to follow up in another PR or just force push in this one?

**Comment by dgageot** [comment]
@nathanleclaire I'm going to force push tomorrow

**Comment by nathanleclaire** [comment]
Excellent thx

**Comment by dgageot** [comment]
@nathanleclaire PTAL

**Comment by nathanleclaire** [comment]
Nice!  Will work on getting this in after the release.

**Comment by dmp42** [comment]
@dgageot @nathanleclaire this needs a rebase. Otherwise, good to go?

**Comment by nathanleclaire** [comment]
It LGTM after a rebase

**Pull request merged**
