### PR TITLE
clean up the vmware drivers

### PR DESCRIPTION
**Pull request by knarz**
Same deal as before, this time just the vmware drivers, though.

Signed-off-by: Sascha Hanse <shanse@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
This LGTM

**Comment by ehazlett** [comment]
@frapposelli this look good to you?

**Comment by frapposelli** [comment]
LGTM

**Comment by ehazlett** [comment]
@knarz would you mind rebasing?  thanks!

**Comment by knarz** [comment]
@ehazlett done

**Comment by ehazlett** [comment]
thanks!

**Comment by nathanleclaire** [comment]
:+1:

**Comment by knarz** [comment]
@ehazlett just realized that the darwin build is broken after the rebase, submitted a new PR for it, sorry.

**Comment by ehazlett** [comment]
@knarz reviewed and merged.  thanks!

**Pull request merged**
