### PR TITLE
Remove lxc-docker to docker-engine migration code

### PR DESCRIPTION
**Pull request by nathanleclaire**
The `rm /etc/apt/sources.list.d/docker.list || true` bit totally hosed upgrade.

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
@tianon It's probably safe to just remove this wholesale like this, right?

**Comment by nathanleclaire** [comment]
It was just intended to provide a migration step which is now long gone.

**Comment by tianon** [comment]
SGTM :+1:

**Comment by nathanleclaire** [comment]
Cool

**Pull request merged**
