### PR TITLE
add better docs to command help

### LINKED ISSUE #583: Command usage should explain what arguments mean
```
$ docker-machine start --help                                                                                                                                                
NAME:
   start - Start a machine

USAGE:
   command start [arguments...]
```

This should explain that the arguments are machine names, and that if no machine is provided the active one will be used.

### PR DESCRIPTION
**Pull request by ehazlett**
title says it all

fixes #583

### CODE REVIEW

**Comment by bfirsh** [comment]
Does this show up in `docker-machine --help`?

**Comment by ehazlett** [comment]
@bfirsh yes looks like:

```
COMMANDS:
   active       Get or set the active machine
   create       Create a machine
   config       Print the connection config for machine. Argument is a machine name. Will use the active machine if none is provided.
   inspect      Inspect information about a machine. Argument is a machine name. Will use the active machine if none is provided.
   ip           Get the IP address of a machine. Argument is a machine name. Will use the active machine if none is provided.
   kill         Kill a machine. Argument is a machine name. Will use the active machine if none is provided.
   ls           List machines
   restart      Restart a machine. Argument is a machine name. Will use the active machine if none is provided.
   rm           Remove a machine. Argument is a machine name. Will use the active machine if none is provided.
   env          Display the commands to set up the environment for the Docker client
   ssh          Log into or run a command on a machine with SSH. Arguments are [machine-name] command. Will use the active machine if none is provided.
   start        Start a machine. Argument is a machine name. Will use the active machine if none is provided.
   stop         Stop a machine. Argument is a machine name. Will use the active machine if none is provided.
   upgrade      Upgrade a machine to the latest version of Docker. Argument is a machine name. Will use the active machine if none is provided.
   url          Get the URL of a machine. Argument is a machine name.  Will use the active machine if none is provided.
   help, h      Shows a list of commands or help for one command
```

**Comment by sthulb** [comment]
Commands also have a `Description` which would show more in-depth detail about a command.

**Comment by ehazlett** [comment]
ah ok i'll use that then

**Comment by ehazlett** [comment]
i misunderstood the original question.  updating.

**Comment by ehazlett** [comment]
@bfirsh this now looks like:

```
NAME:
   start - Start a machine

USAGE:
   command start [arguments...]

DESCRIPTION:
   Argument is a machine name. Will use the active machine if none is provided.
```

`docker-machine --help` is as before (no extended help)

**Comment by ehazlett** [comment]
@bfirsh ^

**Comment by bfirsh** [comment]
Nice. LGTM.

It seems odd that some commands take single arguments and it still says `[arguments ...]`. Also, some commands take multiple arguments too, don't they?

Anyway, we can tie loose ends in a future PR. This is miles better than nothing.

**Comment by maounis** [comment]
Very nice!

**Comment by ehazlett** [comment]
@bfirsh yeah unfortunately that's a `codegangsta/cli` thing -- it appears to say "arguments" regardless.  #563 should fix the single/multiple issue for most commands.

**Pull request merged**
