### PR TITLE
removed the yum repo setup code

### PR DESCRIPTION
**Pull request by tronicum**
it duplicates code logic now within install.sh of
get.docker.com @ https://github.com/docker/docker/blob/master/hack/install.sh
and is currently not called anymore, too.
requested in #3602 and explained further in #13680

### CODE REVIEW

**Comment by tronicum** [comment]
@nathanleclaire could you have a look please why the windows build breaks?

**Comment by nathanleclaire** [comment]
hm, i wonder if we can re-trigger it somehow

@StefanScherer do you know how?

**Comment by tronicum** [comment]
i could add an dummy commit to my branch and commit again

**Comment by StefanScherer** [comment]
AppVeyor is complaining about unmergable pull request. I haven't seen this before, so only way seems to fix the merge conflict and push the PR again which triggers a new build.

**Comment by tronicum** [comment]
seemed to be a git branching/merging issue from my side somehow. what i wonder is last time travis was not called with no notice, does it not start if other tests fail before?

**Comment by tronicum** [comment]
I removed the centos_test.go oraclelinux_test.go and files as the only function to be tested. I am not sure why this 41d403d19fe6dd162691587fa251d39fd02fa8b4 commit is needed. i thought to merge upstream/master and than apply my change (go get my branch to a recent state). seems it includes the changes between my inital commit and now (like Dockerfile update to golang 1.7.0).

**Comment by tronicum** [comment]
maybe i should make a totally new PR once i got my code running to avoid ugly git history

**Comment by nathanleclaire** [comment]
Sure feel free to close and submit new PR, sometimes this kind of stuff happens.  Thanks

**Comment by tronicum** [comment]
don't know how to fix this test problem:
libmachine/provision/redhat.go uses a regex (majorVersionRE = regexp.MustCompile(`^(\d+)(\..*)?`) ) but because it is only included as a variable, it complains about including it unused. if I remove it it complains about a missing import to compile the variable.
the old code used a regexp at a other line so it got out of this loop. don't know hot to fix this (dummy use of regexp would look quite silly.)

**Comment by tronicum** [comment]
looks ok for me now...

**Comment by nathanleclaire** [comment]
@tronicum Could you rebase these 8 commits down to one please?  Thanks

**Comment by tronicum** [comment]
gonna create new pull request

**Pull request closed without merging**
