### PR TITLE
Fusion driver fixes

### PR DESCRIPTION
**Pull request by frapposelli**
Several fixes and enhancements to the Fusion driver.

Integration test:
```shell
frapposelli > ~/Develop../goworks../src/github.../docker/machine > fusion-driver-fixes > MACHINE_TESTS="vmwarefusion" ./script/run-integration-tests
=== RUN TestMachineCreate
 - testing create for vmwarefusion (machine-test-1425042146699457520-vmwarefusion)
--- PASS: TestMachineCreate (82.23s)
=== RUN TestMachineStop
 - testing stop for vmwarefusion (machine-test-1425042146699457520-vmwarefusion)
--- PASS: TestMachineStop (30.41s)
=== RUN TestMachineStart
 - testing start for vmwarefusion (machine-test-1425042146699457520-vmwarefusion)
--- PASS: TestMachineStart (30.69s)
=== RUN TestMachineKill
 - testing kill for vmwarefusion (machine-test-1425042146699457520-vmwarefusion)
--- PASS: TestMachineKill (30.57s)
=== RUN TestMachineRemove
 - testing rm for vmwarefusion (machine-test-1425042146699457520-vmwarefusion)
--- PASS: TestMachineRemove (30.40s)
PASS
ok      github.com/docker/machine/_integration-test     204.324s
```

### CODE REVIEW

**Comment by ehazlett** [comment]
Any chance we could get `numvcpus` to match the host?  I was going to add it but wanted to ask you first :)

**Comment by frapposelli** [comment]
Sure, that would be an easy add :+1:

**Comment by frapposelli** [comment]
Here it is, just used the same behaviour as virtual box, could be worth making it a unable parameter but I guess it's ok for now.

**Comment by ehazlett** [comment]
LGTM

**Comment by ehazlett** [comment]
Thanks!

**Pull request merged**
