### PR TITLE
use custom vmware b2d iso for fusion and vsphere

### PR DESCRIPTION
**Pull request by ehazlett**
This enables external disks and the ability to stop/restart the vm using VMware Fusion and vSphere.

### CODE REVIEW

**Comment by ehazlett** [comment]
@frapposelli this works however we do not have shared folders for fusion.  Is this something misconfigured or just not in the driver?

**Comment by frapposelli** [comment]
AFAIK the shared folder driver is not there. Will discuss this matter this
week as I believe it should be there.

**Comment by md5** [comment]
@frapposelli so it sounds like that ISO just has the changes discussed in https://github.com/boot2docker/boot2docker/pull/638, right?

**Comment by frapposelli** [comment]
Has two patches applied:

boot2docker/boot2docker#638
boot2docker/boot2docker#659

**Comment by ehazlett** [comment]
@frapposelli is there anyway we can get shared folders with this?

**Comment by ehazlett** [comment]
Merging to get the correct ISO so we can at least restart.  Will approach the shared folders in another issue.

**Pull request merged**
