### PR TITLE
libmachine: Filestore#GetActive() should return an error if DOCKER_HOST is empty

### PR DESCRIPTION
**Pull request by skatsuta**
Currently `docker-machine active` returns a stopped machine name randomly if `DOCKER_HOST` is not set, because both `DOCKER_HOST` and `item.URL` are empty and `dockerHost == item.URL` is satisfied.

I think this behavior is very confusing so I suggest the command should return an error in that case.
(Please give me comments on the error message.)

Signed-off-by: Soshi Katsuta <soshi.katsuta@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Seems reasonable to me.

I'd change the error message to `No active host found: DOCKER_HOST not set`.

**Comment by nathanleclaire** [comment]
cc @ehazlett

**Comment by skatsuta** [comment]
@nathanleclaire Thanks for your comment!
The message is better and more descriptive. I modified it.

**Comment by ehazlett** [comment]
LGTM

**Comment by nathanleclaire** [comment]
This would make a great test too ;D

**Pull request merged**
