### PR TITLE
Add SSH config, SOCKS proxy per-machine config options

### PR DESCRIPTION
**Pull request by brettdh**
This adds three flags to `docker-machine create`:

    --generic-ssh-config-file <path/to/config>

        Use the provided config file with the external SSH client (-F)

    --generic-use-user-ssh-config

        Use ~/.ssh/config as the config file

(The flags are mutually exclusive in order to avoid ambiguity.)
    
    --use-socks-proxy <host:port>
    
        Use the provided address as a SOCKS5 proxy when making HTTP
        connections to the new machine. Also include
        `ALL_PROXY=socks5://<host:port>` in the output of `docker-machine env`.

This depends on a few other PRs (and one non-PR branch):

* #3209 (included here for context)
* #3319
* https://github.com/docker/machine/compare/master...dduportal:master
  * Included here for context (but a lot of it is reworked/removed)
  * Also discussed in #2383

...so it's going to look a little messy. Sorry about that.

I'm happy to do some history cleanup before this is merged, but I
wanted to get the discussion going, as I've landed on this as something
that at least works for my current use case. If it needs to be split into
multiple PRs, I'm happy to do that first. I also wanted to ping @dduportal
again to see whether he has an alternative implementation existing somewhere,
or if it's ok for me to take this over.

Ideal situation after cleanup, I think:

* #3209 (after cleanup by @nathanleclaire) is merged first
* SSH config file option is untangled from this branch and merged next
* SOCKS proxy option (being the only thing left in this branch) is merged last

### CODE REVIEW

**Comment by brettdh** [comment]
FWIW, the only test that failed was the same one that failed on #3209.

**Comment by nathanleclaire** [comment]
Why bundle SSH configuration file and SOCKS proxy support into one PR?  They are generally unrelated features, right?

**Comment by brettdh** [comment]
@nathanleclaire I agree, as I mentioned in my first comment. :smile: Happy to unbundle them tomorrow. 

They do both depend on #3209, though, so I wasn't sure of the best way to do PRs that depend on other PRs. Does github handle this nicely? i.e. if I have branch B that starts atop branch A, is it smart enough to know that the PR for branch B shouldn't include the commits from branch A? I've never tried that.

**Comment by dduportal** [comment]
Hello ! Happy to let you implement the Socks idea, I added a comment here : https://github.com/docker/machine/issues/2383#issuecomment-214625282 .

You strongly should split in 2 PRs :)

**Comment by brettdh** [comment]
@nathanleclaire I tested this out a bit in a toy repo. I made three PRs:

                  --- o feature-2
                 /
      o ------- o  feature-1
    master       \
                  --- o feature-3

I set `feature-1` as the base for `feature-2` and `feature-3`, which worked as expected; the child PRs didn't contain the changes from their parent.

I then merged `feature-1`. I hoped that `feature-2` and `feature-3` would now be updated to have `master` as their base, but they didn't; they were still going to be merged into the `feature-1` branch, which was already merged to `master`. Also, there was no way for me to edit the base of the child PRs. Even if I rebase their branch on `master` and force-push, they are still set to merge into `feature-1` - and in fact, they then also contain the merge commit from `feature-1` that landed on `master`, since the `feature-1` branch doesn't have it.

Since the `feature-1` branch was still hanging around in Github, and since open PRs depended on it, I wasn't able to delete it after the PR was merged. I tried deleting it via `git push origin :feature-1`, hoping that this would force Github to let me manually edit the base (Gitlab works like this, in my experience, but then, it also allows you to edit the base (target) branch at any time). Instead, Github just closed all the PRs that depended on `feature-1` without merging them.

As a relative noob to contribution to large projects on Github, I welcome your advice on how to best handle this. :smile: I've already untangled the commits so that these features can be reviewed separately; I'm now just unsure as to how to handle their PRs. As I mentioned, the SOCKS feature changes currently depend on the SSH config changes - though they are now (in my local repo) untangled change sets - and both depend on some version of #3209. So, it makes sense to me for them to be a sequence of PRs.

There's also the wrinkle that the SSH config changes currently depend on brettdh/machine@8669e071 (just your commit rebased on master a few days ago).

My initial thought is to just post new PRs with the dependent branches such that the PRs only contain the new changes. Then, as each PR's dependent gets merged, branch deleted, the child PR will be closed, and I'll open a new one with the same changes, rebased on master. Then that one can be merged later, and we can continue discussing implementation details and such independently of when each PR gets merged. What do you think?

And now I'm off to make a Github feature request for the ability to edit a PR's base branch. :smile:

**Comment by brettdh** [comment]
Closing in favor of brettdh/machine#1.

**Pull request closed without merging**
