### PR TITLE
Fix ec2 ebs optimized integration test

### PR DESCRIPTION
**Pull request by jeanlaurent**
Fix the ec2 IT test from #2750

### CODE REVIEW

**Comment by jeffellin** [comment]
If I am reading this correctly, doesn't now not assert that the EBSOptimized = true?  Also, do you want to continue using the docker image or one that you control?

**Comment by jeanlaurent** [comment]
Hmm it does, in the second "testcase". Bats is a bit tricky when your run multiple commands and one fails. By putting in one test the run ( and ensure it works) and putting the assertion in a second one, it's easier to read/write and more robust (in a bats way...)

I think this is fine for now. We have yet to have comprehensive and structured IT test for other driver than `none` and `virtualbox`.

This is a good start.

Thx for your help on this one @jeffellin

**Comment by dgageot** [comment]
LGTM

**Comment by jeffellin** [comment]
ok I see what you are doing now,  its just a little confusing because your second test label is check that its up, I probably would have done "check that its up and an ebs instance."

**Comment by jeffellin** [comment]
Thanks @jeanlaurent for the help gettting this merged.

**Comment by jeanlaurent** [comment]
Yep correct. Needs a rename.

**Pull request merged**
