### PR TITLE
[Azure] Support for spinning up Windows server 2016 Docker hosts

### PR DESCRIPTION
**Pull request by ppadala**
Issue link: #2907.

Quick description of what I have done

- Add support for spinning up Windows image.
- Use Windows server 2016 TP4 image using  on Azure
- Spin it up. I am using the library https://github.com/Azure/azure-sdk-for-go instead of the vendored code in https://github.com/docker/machine/tree/master/vendor/github.com/MSOpenTech/azure-sdk-for-go, which seems like an older version.
- Use WinRM to connect to the instance

TBD: 
- Remove hard-coding of passwords
- Remove the storage-service hard-coding, need to query

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
`azure` note: We already have an azure driver rewrite work going on for a while that is almost ready to be sent as PR. It's entirely breaking as it uses Azure Resource Manager REST APIs and not the old Service Management APIs (what the current driver and this PR does). 

We probably shouldn't merge anything to azure driver until the new azure driver is in.

**Comment by nathanleclaire** [comment]
Yes, keep an eye on @ahmetalpbalkan branch, everything will be changing pretty shortly.

**Comment by ahmetalpbalkan** [comment]
@ppadala new azure driver PR: https://github.com/docker/machine/pull/3159

**Comment by friism** [comment]
@ppadala this is really cool - do you have time to look at porting this to use the new Azure driver?

**Comment by nathanleclaire** [comment]
@ppadala New Azure driver is merged in now, feel free to ping us if/when you update this (no rush though).

**Comment by ppadala** [comment]
> @ppadala this is really cool - do you have time to look at porting this to use the new Azure driver?
> @ppadala New Azure driver is merged in now, feel free to ping us if/when you update this (no rush though).

I will rebase and start working with the new driver. Will update soon.

**Comment by enderb-ms** [comment]
@ppadala I have a few questions:
- Are you having an option to set up Hyper-V? If so, how are you dealing with that?
- Does this support Server Core and Nano?

**Comment by friism** [comment]
@ppadala what's the provenance of the `cx-win-2016-2` image? Is that the default current Azure Windows Server 2016 image?

**Comment by ppadala** [comment]
> @ppadala what's the provenance of the cx-win-2016-2 image? Is that the default current Azure Windows Server 2016 image?

This is derived from the Windows Server 2016 TP4 official image. This already has docker installed and WinRM setup. That image is a test image and I don't think we should make that as a base image for Azure Windows Docker hosts. We have to discuss what should be enabled in the official image for the azure driver for Windows to work.

@enderb-ms talked about installing SSH server in the images. Let me know what you think. We can start with WinRM (assuming the official images can have it enabled) and then move to SSH, if that's deemed better.

**Comment by ppadala** [comment]
> Are you having an option to set up Hyper-V? If so, how are you dealing with that?

The code doesn't really assume that Hyper-V needs to be setup. But, I was using the script at https://github.com/Microsoft/Virtualization-Documentation/blob/master/windows-server-container-tools/Update-ContainerHost/Update-ContainerHost.ps1 to install Windows docker-engine, which also tries to setup Hyper-V but fails in the TP4 image. Though that's not a problem, if you just want to run native containers.

> Does this support Server Core and Nano?

Supports Server Core. I haven't tested with Nano yet, but the code doesn't assume anything specific.

**Comment by ppadala** [comment]
Folks, I am closing this pull request, will submit a new one when it's ready. Let's continue our discussion at https://github.com/docker/machine/issues/2907

**Pull request closed without merging**
