### PR TITLE
Update Godeps.

### PR DESCRIPTION
**Pull request by jsirois**
This was a mechanical change:
```
make dep-restore
godep update -goversion
make dep-save
```

Signed-off-by: John Sirois <john.sirois@gmail.com>

### CODE REVIEW

**Comment by jsirois** [comment]
NB: This is part 1 of 2 for #3109.  Let me know ig the `-goversion` update to `1.6` is inappropriate.

**Comment by nathanleclaire** [comment]
Hmm... Looks reasonable, although it's a bit nerve-wracking bumping so many deps.  What do you think @dgageot @jeanlaurent

**Comment by jsirois** [comment]
@nathanleclaire fwict no existing deps were bumped, only new deps added, unused deps removed.
IIUC that's all that can ever happen running make `dep-restore/make dep-save` with no other changes except the underlying local code.

**Comment by nathanleclaire** [comment]
Gotcha thanks @jsirois

**Comment by nathanleclaire** [comment]
Moving Go version to 1.6 is fine BTW

**Comment by nathanleclaire** [comment]
LGTM -- thanks for this

**Pull request merged**
