### PR TITLE
#1289 Env swarm parameter lost on the eval help message

### PR DESCRIPTION
**Pull request by aperepel**
A clean version of PR1326 - I've since redid the branch from CLI, the tool messed up the origin tracking.

### CODE REVIEW

**Comment by ehazlett** [comment]
LGTM

**Comment by ehazlett** [comment]
Would you mind squashing these commits?  Thanks!

**Comment by aperepel** [comment]
Done and done :+1:

**Comment by ehazlett** [comment]
LGTM

**Comment by aperepel** [comment]
Hi, giving this PR a bump, it's been over a month, and all checks are green - anything else one should do to get it in?

**Comment by nathanleclaire** [comment]
I'm sorry to be so late to say this, but I'm pretty hesitant about this.  I'd prefer to keep the logic around this section as simple as possible since it's already kind of hairy and needs to work on several different platforms.  Do you feel like it's confusing for users who want to activate their swarms that they need to remember `--swarm` flag?

**Comment by nathanleclaire** [comment]
Also note that with this PR, you have to use `--swarm` flag with env to get the hint in that text, which naturally implies that you already know about it.

I think that if the concern is around notifying users how to connect to a newly created swarm master (which is what `--swarm` option for env is used for), we might be better off simply adding a new comment line to a created master, which says something like:

```console
$ docker-machine env kitematic
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:2376"
export DOCKER_CERT_PATH="/Users/nathanleclaire/.docker/machine/machines/kitematic"
export DOCKER_MACHINE_NAME="kitematic"
# Run this command to configure your shell:
# eval "$(docker-machine env kitematic)"
# If you want to talk to the Swarm master, remember to use the --swarm flag with env.
```

**Comment by dgageot** [comment]
An updated PR can be found [here](https://github.com/docker/machine/pull/2027). It fixes the problem with `--swarm` and `--no-proxy` and fixes the hint printed for fish shell.

**Comment by nathanleclaire** [comment]
I think this is fixed in master with a @dgageot PR.  Please re-open if that is not correct.

**Pull request closed without merging**
