### PR TITLE
function GetActive should return real error when file doesn't exist

### PR DESCRIPTION
**Pull request by TrumanLing**
fix issue #771

### CODE REVIEW

**Comment by TrumanLing** [comment]
@ehazlett and @bfirsh ,as for issue #771, I made this PR, please help review, thanks!

**Comment by ehazlett** [comment]
@TrumanLing i'll review this today.  sorry for the delay!

**Comment by ehazlett** [comment]
+1 for fixing the #771 issue.  however, I'm not sure on the error messages.  i think it's confusing to the user to just respond with "cannot find file".  perhaps instead we catch that specific error and use a custom error saying "no active host specified"?  if it's any other error, we could just return it?

**Comment by TrumanLing** [comment]
@ehazlett done,please review again.

**Comment by ehazlett** [comment]
LGTM

**Comment by ehazlett** [comment]
This has caused a regression.  The `rm` command is no longer to remove machines when there is no active host.  Reverting commit.

**Pull request merged**
