### PR TITLE
Added overlay networking port for AWS security profile

### PR DESCRIPTION
**Pull request by kacole2**
This is based on a request for #3506. Added in port 4789/udp for the security profile on AWS and fixed the tests so they all pass.

Signed-off-by: Kendrick Coleman <kendrickcoleman@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Nice @kacole2 .  I think it needs `7946` for Serf as well though.

How will this be enabled?

Additionally, I think it should only be open to instances in same VPC, not publicly to the world, right?

**Comment by kacole2** [comment]
@nathanleclaire adding in 7946 can be done on the security profile pretty easily. 

As a counter to not be public... what about the idea of cross-cloud Swarms? I might be mistaken, but I thought you could use overlay networking to have hosts on AWS & Digital Ocean all in the same Swarm. No?

**Comment by nathanleclaire** [comment]
> As a counter to not be public... what about the idea of cross-cloud Swarms? I might be mistaken, but I thought you could use overlay networking to have hosts on AWS & Digital Ocean all in the same Swarm. No?

Well, it's security issue.  Not really safe to allow inbound VXLan from basically anywhere.

**Comment by kacole2** [comment]
Security puts the "no" in innovation. 

I see your point. I'll close this out because it's not going to go anywhere. 

This convo can continue in #3506

**Comment by nathanleclaire** [comment]
Thanks @kacole2

**Pull request closed without merging**
