### PR TITLE
fix repo install on redhat provisioner

### PR DESCRIPTION
**Pull request by tronicum**
redhat provisioner
* added repo config (found in older version)
* try to install redhat/fedora rpm from docker
before generic get.docker.com tries to config & install (and fails at the moment)

Signed-off-by: Stefan Sels <tronicum@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
I think upstream `get.docker.com` is supposed to work with RHEL now?  We should probably switch to that instead.

**Comment by tronicum** [comment]
This fixes a setup where fedora 24 will result into get.docker.com to point to a non existing repo instead of using 23 which works fine with 24. 
I can not look at the code right now for RHEL. 

If we point to get.docker.com always, everytime fedora is newer than dockers repo it fails or installs older fedora packages (without notice).

**Comment by nathanleclaire** [comment]
> If we point to get.docker.com always, everytime fedora is newer than dockers repo it fails or installs older fedora packages (without notice).

Then that issue should be fixed in docker/docker upstream, no?  Won't Machine attempting to work around this be counter-productive?

**Comment by tronicum** [comment]
> > If we point to get.docker.com always, everytime fedora is newer than dockers repo it fails or installs older fedora packages (without notice). 

> Then that issue should be fixed in docker/docker upstream, no? Won't Machine attempting to work around this be counter-productive?

Yes, it should be covered by docker/docker. But I guess it wont. The official policy at docker/docker is, if its not released at time of a docker release, it is not supported.

Also, if you don't even try to install via a docker-machine configured repo, close #3627 too and we can remove all the repository setup code as if we always use get.docker.com to setup those, we do not need them.

**Comment by nathanleclaire** [comment]
Hey @tronicum, what's the status on this?  Do you think it's still needed?

**Comment by tronicum** [comment]
> Hey @tronicum, what's the status on this? Do you think it's still needed?
> 
If get.docker.com is the choice to setup repos it's not needed. 

But then I would suggest to remove all that platform specific code to setup repos because it would be never be used.

**Comment by nathanleclaire** [comment]
> If get.docker.com is the choice to setup repos it's not needed. 

OK. It is so I will close this issue

> But then I would suggest to remove all that platform specific code to setup repos because it would be never be used.

Which code do you refer to?

Thanks @tronicum

**Comment by tronicum** [comment]
ConfigurePackageList, which sets the official yum repositories. This task is performed by get.docker.com ( https://github.com/docker/docker/blob/master/hack/install.sh around line 458). 
I opened this PR initially, because to my surprise, ConfigurePackageList was never used in latest code.

In my opinion it can be removed because it is never called. If you want I could write a PR to remove it and its tests.

**Comment by nathanleclaire** [comment]
> In my opinion it can be removed because it is never called. If you want I could write a PR to remove it and its tests.

Yeah that'd be great, thanks!

**Pull request closed without merging**
