### PR TITLE
fix regression with command rm and function GetActive should return real...

### PR DESCRIPTION
**Pull request by TrumanLing**
Enforce PR #772 and revert #802

### CODE REVIEW

**Comment by TrumanLing** [comment]
@ehazlett please help review,thx.

**Comment by TrumanLing** [comment]
@ehazlett sorry, machine's directory structure has changed, I will rebase it and re-submit

**Comment by TrumanLing** [comment]
@ehazlett done, please help review, thx.

**Comment by ehazlett** [comment]
Those other issues have been merged.  What issue is this solving?  Could you give a little more description?

**Pull request closed without merging**
