### PR TITLE
Use SDK to Validate VpcID with SubnetId

### PR DESCRIPTION
**Pull request by feelobot**

### CODE REVIEW

**Comment by ehazlett** [comment]
Would you mind signing your commit?  https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by dmp42** [comment]
@dgageot can you own this one? Thanks!

**Comment by dgageot** [comment]
Hi @feelobot, can you squash your commits and rebase on master? That would be great!

**Comment by dgageot** [comment]
LGTM
ping @docker/machine-maintainers

**Comment by dmp42** [comment]
Thanks for the review @dgageot

**Pull request merged**
