### PR TITLE
VMware Fusion: static ip addresses (dhcp) are evaluated

### PR DESCRIPTION
**Pull request by mrbuk**
docker-machine seem only to use dynamic dhcp leases from a file like
```
// DHCP lease table for NAT vmnet interface
var dhcpfile = "/var/db/vmware/vmnet-dhcpd-vmnet8.leases"
```

Fusion allows to configure static leases, so that the IP always remains the same in a file like

    /Library/Preferences/VMware\ Fusion/vmnet8/dhcpd.conf

The functionality to check both static leases and dynamic leases is implmented in attached code.

`getMacAddressFromVmx()` -> extracts MAC from vmx file
`getIPfromVmnetConfiguration()` -> searches vmnet config for ip/mac addresses
`GetIP()` -> tries first to find the static config through `getIPfromVmnetConfiguration()` and if that doesn't work falls back to `getIPfromDHCPLease()`

### CODE REVIEW

**Comment by mrbuk** [comment]
Added description of functionality to https://github.com/docker/machine/issues/2137

**Comment by nathanleclaire** [comment]
cc @frapposelli

**Comment by frapposelli** [comment]
:shipit:

**Comment by nathanleclaire** [comment]
I guess ship it squirrel is the new LGTM for @frapposelli ??? 😛

**Comment by frapposelli** [comment]
@nathanleclaire haha yes, sorry, we've been using https://lgtm.co with default on :shipit: to approve PRs and now I have it wired to my brain 😄

**Comment by nathanleclaire** [comment]
😛 LGTM

**Pull request merged**
