### PR TITLE
Additional SSH tests

### PR DESCRIPTION
**Pull request by nathanleclaire**
Depends on: https://github.com/docker/machine/pull/2491

A few additional tests on top of those for the `docker-machine ssh` command.

cc @docker/machine-maintainers

### CODE REVIEW

**Comment by jeanlaurent** [comment]
Tests aren't passing either on circle travis and on my local workstation.

Sounds like it needs some update.

**Comment by nathanleclaire** [comment]
Forgot to push a module :disappointed:

**Comment by dgageot** [comment]
@nathanleclaire do you plan to rebase/fix this one?

**Comment by nathanleclaire** [comment]
Yes I'd like to rebase and get this merged just have been neglecting it.  I'll work on it on Monday.

**Comment by nathanleclaire** [comment]
It does break the marshaling of a host.  Might have to use a different approach.

**Comment by nathanleclaire** [comment]
@dgageot @jeanlaurent Rebased and revised it for feedback.  It no longer breaks marshal / unmarshal of hosts and the errors have been re-named.  PTAL

**Comment by dgageot** [comment]
LGTM

**Pull request merged**
