### PR TITLE
Don't create the VM if no hardware virtualization

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
Fixes #2619

**Comment by jeanlaurent** [comment]
A shorter name for the flag is better, a part from that, LGTM, a much needed feature.

**Comment by dgageot** [comment]
@jeanlaurent fixed

**Comment by jeanlaurent** [comment]
LGTM

**Comment by dgageot** [comment]
@docker/compose-maintainers We might want to hold on this one until we test this behaviour: https://www.virtualbox.org/ticket/12350
It looks like a windows machine with Hyper-v installed will break the VT-X support in VirtualBox. There's nothing we can do but we could at least detect hyperv and tell the user that maybe it should be deactivated.

**Comment by nathanleclaire** [comment]
The `hyper-v` interference has been brought up before.  I do agree a check for `hyper-v` would be awesome, but why would merging this PR be blocked on that?  It seems to just add an additional flag which users can use to skip the VTX check.  To me that falls into the "I really know what I'm doing" class of users.

**Pull request merged**
