### PR TITLE
[WIP] Update `oauth2` interaction and library

### PR DESCRIPTION
**Pull request by timfallmk**
Reference to #1628 
Signed-off-by: Tim <timfall@gmail.com>

### CODE REVIEW

**Comment by timfallmk** [comment]
Anyone have more familiarity with the current `golang.org/x/oauth2/google` functions? I'm learning as I go.

**Comment by mattjmcnaughton** [comment]
Thanks for doing this - great idea to get a jump on this ahead of Google code going read only.

I was just looking through the code and noticed the `digital_ocean` driver also uses `"code.google.com/p/goauth2/oauth"`, so it may make sense to switch it over to `golang.org/x/oauth2` as well.

**Comment by mattjmcnaughton** [comment]
Also I don't have a ton of experience with the oauth, but it looks to me like `Transport` is not used as heavily in `golang.org/x/oauth2`. So instead of creating a `Transport` and then returning

**Comment by timfallmk** [comment]
@mattjmcnaughton You're right on both counts. `Transport` is now a low level convention, used by `client` to construct an exchange. Changing this is what's taking most of my time, since I don't want to necessarily change the way the current code works.

As for the DO driver, I've submitted a patch here, which is now merged. https://github.com/digitalocean/godo/pull/62

I think the vendored version used here just needs to be updated.

**Comment by mattjmcnaughton** [comment]
:+1: re `digitalocea/godo` update. Would this [line](https://github.com/docker/machine/blob/master/drivers/digitalocean/digitalocean.go#L8) in the Digital Ocean driver still need to be updated? Or is the `godo` patch you submitted taking care of that?

**Comment by timfallmk** [comment]
@mattjmcnaughton This project uses `Godeps` to "vendorize" dependencies (freeze them at a specific version and include them with the code). When the maintainers update their included version of `godo` here, it will pull in the newest code. That would include the right import lines for *that* dependency as well.

**Comment by dgageot** [comment]
Fixed by https://github.com/docker/machine/pull/2087

**Pull request closed without merging**
