### PR TITLE
driver: exoscale driver

### PR DESCRIPTION
**Pull request by pyr**
Add support for exoscale, a Swiss cloud provider. This pull [egoscale](https://github.com/pyr/egoscale),
a Go binding for exoscale, in godeps which has no additional dependencies.

## Configuration

The main configuration options are:

- `--exoscale-api-key`: exoscale API key, also looked in the `EXOSCALE_API_KEY` environment variable
- `--exoscale-api-secret-key`: exoscale API secret, also looked in the `EXOSCALE_API_SECRET` environment variable
- `--exoscale-instance-profile`: name of exoscale profile to use, defaults to `small` and must be one of: `tiny`, `micro`, `small`, `medium`, `large`, `extra-large`, `huge`
- `--exoscale-disk-size`: disk size to use, in GB. one of: 10, 50, 200, 400

## Default Behavior
By default, an SSH keypair will be created for each new machine and a security group will be created authorizing TCP ports 22 and 2376 as well as ICMP echo.

The `--exoscale-keypair` and `--exoscale-security-group` options may be used to modify this behavior.
The default image used is a 64-bit Ubuntu 14.04 image and may be changed with the `--exoscale-image` option.
The only valid image types to use for now are: "ubuntu-14.04" and "ubuntu-14.10"

## Docker machine support

The following docker machine commands work as expected:

- `ls`
- `ssh`
- `start`, `stop`, `restart`, `kill` and `rm`
- `create`
- `inspect`

The only command which provides no behavior is the `upgrade` command.

## Testing out

Testers wishing to validate docker-machine's behavior on exoscale may use the following coupon code (first come, first served): DOCKERMACHINEROCKS on https://portal.exoscale.ch

### CODE REVIEW

**Comment by vincentbernat** [comment]
Pull request updated with recent changes.

**Comment by vincentbernat** [comment]
Updated again. @brfish, maybe you can tell me if there is something wrong or what is your policy for drivers...

**Comment by ehazlett** [comment]
@vincentbernat thanks for the contribution!  right now we are working on stability and getting the drivers integrated with our test suite.  could you reach me in irc (ehazlett) to see if we can get a test account setup for exoscale?  this would help get it merged seeing the integration tests pass :)

**Comment by vincentbernat** [comment]
Updated to correctly use the machine name provided by the driver framework.

**Comment by vincentbernat** [comment]
I just updated the PR to make it merge again. Some other changes:

 - Don't wait for Docker to be ready on start/restart (like other drivers). I think this could be nice to be done outside drivers so that it's easier to use in scripts (docker machin start XXX && docker pull YYY). I can do a PR for that if needed.
 - Grab Docker using `curl | sh` (like other drivers) instead of using cloud-init (which was nice but this makes postconfiguration more difficult because we can't know when cloud-init is done remotely since docker doesn't listen anymore on 2376 upon first installation).

**Comment by pyr** [comment]
hi @bfirsh @ehazlett anything holding up the integration of this PR, were you able to integrate your account in the test-suite ? We'd be happy to see this moving forward, cheers!

**Comment by ehazlett** [comment]
@pyr thanks for your patience :)  the "theme" for the next sprint is refactoring the core to be more friendly towards the drivers and driver integration testing.  there *shouldn't* be too many things that you will need to update.  my goal is to make it so the driver handles only the provider operations and we don't have the widespread updates when we make a change.  out of the refactor i want to get a driver spec making it easier to develop and maintain drivers.  i appreciate your patience and hopefully we will get all of the pending drivers in by the next release.

**Comment by runseb** [comment]
I am an exoscale user and I really need this. It's been pending since dec 5th. Other drivers have been merged that don't quite work. So it would be really nice to see this being merged soon.

**Comment by ehazlett** [comment]
@runseb yes we are getting the docs updated for the latest driver revisions and then this can be rebased and merged.  we chose a selection of drivers to get an initial set and get usage for.  now that we have the driver refactor done, these can be rebased.

thanks!

**Comment by runseb** [comment]
@ehazlett ok cool, just let us know and we will get this rebased.

**Comment by ehazlett** [comment]
@runseb awesome -- will do.  the docs will be by the end of this week.  If you want to check the existing interface you can as well.

@pyr do you think yourself (and/or others at exoscale) would be willing to be maintainer of this driver?

**Comment by pyr** [comment]
@ehazlett yes, I hope the many refactors to keep up to date with machine from day 1 speaks to our willingness to maintain this as well as our activity in other open source projects.

**Comment by ehazlett** [comment]
@pyr absolutely.  we appreciate it and look forward to getting this in!

**Comment by vincentbernat** [comment]
I have refactored the driver to be up-to-date with the new driver interface. I didn't use `WaitForTCP()` like many other drivers because it is my understanding this is done automatically in `libmachine/host.go`. If that's correct, I can do a PR for other drivers to remove the call.

Moreover, I didn't implement `AuthorizePort()` and `DeauthorizePort()`. While we support security groups, they currently are shared accross several hosts. What could be done is to create a security group dedicated to each host and hence be able to modify it. cc @pyr

**Comment by ehazlett** [comment]
@vincentbernat thanks!  correct, the WaitForTCP should happen in host.go.

No problem about AuthorizePort / DeauthorizePort.  It's not implemented anywhere and was meant for a future feature anyway.

Thanks!

**Comment by runseb** [comment]
@ehazlett what else is needed to get this merged ? seems you are in agreement with @vincentbernat comments.

**Comment by ehazlett** [comment]
@runseb thanks for the follow up.  we are getting the housekeeping done as far as documentation around driver contributor maintenance (official points of contact, testing infrastructure responsibilities, repo responsibilities, etc).  Thank you for your patience -- we are very close!

**Comment by nathanleclaire** [comment]
Tested and it looks pretty good... I have just a few things and then I will be ready to merge:

1. Please update `Start`, `Stop`, and `Restart` to set the IP address accordingly to : https://github.com/docker/machine/pull/1043
2. Who _specifically_ is going to be the maintainer?  Can you please reach out to nathan@docker.com or evan.hazlett@docker.com to give us your contact information?  And do you hereby solemnly swear to be a good steward of the driver, the project, and continue to contribute after this gets merged in?  We would like to see you around relatively often, ideally helping out on the core as well as your specific driver, and fix issues with the driver in a timely fashion if/when they come up.

**Comment by nathanleclaire** [comment]
Also, that cloud init file does not do any actual installation of docker etc. right?  We are trying to centralize all of that common logic.

**Comment by vincentbernat** [comment]
The cloud-init stuff doesn't install anything. It just registers the FQDN, ensure that the rootfs has the right size and put what is needed in `/etc/hosts` for the host to know its name. Docker is installed through the common framework.

As for the IP address, `IPAddress` is already used in the struct and the IP address is kept during the whole life of the host, so it doesn't need to be updated when the machine is restarted.

We'll send you contact information shortly.

**Comment by ehazlett** [comment]
awesome -- this needs a final rebase to work with the new logging stuff just merged today.  thanks!

**Comment by nathanleclaire** [comment]
LGTM

**Comment by vincentbernat** [comment]
Rebased on top of master. Integration tests are running fine.

**Comment by ehazlett** [comment]
tested - works as expected.  LGTM

**Pull request merged**
