### PR TITLE
fix zsh-completion syntax error

### LINKED ISSUE #3583: zsh autocompletion error
`invalid argument` error occurs when I type `docker-machine start` and then press tab key:
```
$ docker-machine start
_arguments:comparguments:313: invalid argument: (- :){-h,--help}[Print usage]
```

### PR DESCRIPTION
**Pull request by leonhartX**
fix #3583 , change opts_help's definition to avoid syntax error.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Can you rebase to get rid of the merge commit please?

**Comment by leonhartX** [comment]
@nathanleclaire Sorry but I don't know what is the best way to do that. Could you please tell how to do? 
Do I need to open another PR and just close this one?

**Comment by nathanleclaire** [comment]
I might be able to just squash on merge... Hang on

**Comment by nathanleclaire** [comment]
LGTM 👍

**Pull request merged**
