### PR TITLE
Enhancing `docker-machine ip` to support multiple host arguments

### LINKED ISSUE #999: `machine ip` chained arguments
## What I do

I use the `ip` command to get the ip list of my two servers :

```bash
~$ docker-machine ls
NAME    ACTIVE   DRIVER         STATE     URL                         SWARM
nodeA            digitalocean   Running   tcp://x.x.x.x:2376   
nodeB   *        digitalocean   Running   tcp://y.y.y.y:2376   

~$ 
```

## What I get

I only get the first IP of the list :

```bash
~$ docker-machine ip $(docker-machine ls -q)
x.x.x.x

~$ 
```

## What I expected

I expected to have the same behaviour as the `rm` command.
So I expected to see the following ouput :

```bash
~$ docker-machine ip $(docker-machine ls -q)
x.x.x.x
y.y.y.y

~$ 
```

### PR DESCRIPTION
**Pull request by hairyhenderson**
Fixes #999

Signed-off-by: Dave Henderson <Dave.Henderson@ca.ibm.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Why not use  `runActionWithContext` like `start` and `stop` commands do?  This logic is already implemented there.

**Comment by hairyhenderson** [comment]
@nathanleclaire - that's exactly why this is still a WIP ;)

I looked at `runActionWithContext` for inspiration, but there was some reason I thought I couldn't use it. I'll give it another shot with that :)

**Comment by hairyhenderson** [comment]
Oh yeah, I remember now... `runActionWithContext` is geared towards methods that don't return anything  other than an error. But I think I might be able to work around that by wrapping the GetIP() call...

**Comment by hairyhenderson** [comment]
@nathanleclaire - PTAL - have I done this sanely? :)

**Comment by nathanleclaire** [comment]
Looks like you've definitely got the right idea - how about adding a `GetIP` method to `Host` like the way the others are done?  You should be able to take the closure that you have almost verbatim for this.

**Comment by nathanleclaire** [comment]
Oh, and also, let's just call the action "ip" for consistency's sake - unless I'm mistaken, they map directly to the commands that you invoke on the CLI.

**Comment by hairyhenderson** [comment]
Yeah, ok that sounds better... :)

**Comment by hairyhenderson** [comment]
Ok, this time I think I like it. I'm going to work on some tests, and get some documentation worked out now.

**Comment by nathanleclaire** [comment]
Nice.  Code LGTM

**Comment by hairyhenderson** [comment]
@nathanleclaire - ok, I've added some tests and docs, and squashed. I think this is done now - PTAL :)

**Comment by nathanleclaire** [comment]
LGTM!  Appreciate you taking the initiative on the test and doc.

**Comment by nathanleclaire** [comment]
cc @ehazlett for review

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
