### PR TITLE
Ref PR #1336: Include AWS driver usage & docker cli +x in documentation

### PR DESCRIPTION
**Pull request by kacole2**
Reference PR #1336
detailed AWS deployment documentation
Signed-off-by: Kendrick Coleman <kendrickcoleman@gmail.com>
Documented making docker client executable
Signed-off-by: Kendrick Coleman <kendrickcoleman@gmail.com>

Added chmod +x after using curl for the Docker CLI to make it
executable in the documentation.
Added an example for using the AWS EC2 driver in the documentation.

### CODE REVIEW

**Comment by ehazlett** [comment]
@moxiegirl PTAL

**Comment by moxiegirl** [comment]
LGTM
 
ping @thaJeztah

**Comment by thaJeztah** [comment]
Thanks! writing LGTM (haven't checked the procedure)

**Comment by moxiegirl** [comment]
@kacole2 apologies we are pausing on merging this because of #1490 ...when that one merges, you'll need to rebase.   I realize this is extra work for you so if you are not willing to wait, I'm happy to carry this for you.

**Comment by kacole2** [comment]
@moxiegirl no problem. I'll rebase once it's merged.

**Comment by kacole2** [comment]
@moxiegirl any update here?

**Comment by moxiegirl** [comment]
@kacole2 #1490 split out each of the commands into separate files in machine...you actually need to do that to your content as it assumes the old, unified `index.md` it will merge on a rebase but it is destroying the split.

**Comment by dmp42** [comment]
@moxiegirl is it still necessary?
Can we carry this given @kacole2 has already been through a lot to get there (from #1336)?

Thanks.

**Comment by moxiegirl** [comment]
@dmp42 I'll carry this.  @kacole2 Thank you.

**Pull request closed without merging**
