### PR TITLE
Wait for state before return on start, stop, restart, kill

### LINKED ISSUE #757: docker-machine should wait for proper state to be fulfilled before returning from stop, start, etc. commands
When we do a command like `docker-machine stop`, not all drivers wait for the machine to be down before returning.  Some fire off an API request and immediately return.  We should wait for the machine to be in the desired state before returning from the command.

This is needed for:

- start
- stop
- restart
- kill

### PR DESCRIPTION
**Pull request by nathanleclaire**
Fixes #757 

cc @ehazlett @sthulb 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by sthulb** [comment]
Should we start refactoring things out to match @bfirsh's issue #727? So instead of calling things machines, we call them hosts?

**Comment by sthulb** [comment]
I like it.

**Comment by ehazlett** [comment]
@sthulb i believe most of the internals are actually `host` but we should probably line them up.  I don't think @nathanleclaire has to do that for this -- those actually came from me I believe ;)

**Comment by sthulb** [comment]
That's fair enough, I just thought we should start at some point :)

**Comment by ehazlett** [comment]
@nathanleclaire this needs a rebase.  i would like to get this in -- helps tremendously especially with integration tests :)

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
