### PR TITLE
[PR for 1.7.0] Move VMware Fusion driver to the official boot2docker release.

### PR DESCRIPTION
**Pull request by frapposelli**
This PR brings `vmwarefusion` on the official boot2docker release train, this PR is to be merged for the 1.7.0 release of Docker / Boot2Docker.

### CODE REVIEW

**Comment by ehazlett** [comment]
Nice! LGTM

**Comment by nathanleclaire** [comment]
LGTM - let's make sure to add a caveat about this feature to the RC notes

**Comment by frapposelli** [comment]
Note that this will break the shared folders functionality if used with a current b2d iso.

**Comment by nathanleclaire** [comment]
@frapposelli Yep, we're aware - we want to get it in for testing by manually specifying the ISO URL ASAP

**Pull request merged**
