### PR TITLE
Read active host from DOCKER_HOST instead of from file

### PR DESCRIPTION
**Pull request by nathanleclaire**
This is a re-worked version of #777.  For a feel of the motivations and issues related to it, see that proposal.

THIS DEPRECATES THE "SHORT FORM" MACHINE COMMANDS WHICH AUTOMAGICALLY RUN AGAINST THE ACTIVE HOST, e.g. `docker-machine start`, `docker-machine stop` without any arguments.

This is quite near completion, but I still need to update the integration tests.

cc @ehazlett @sthulb @hairyhenderson @tiborvass @SvenDowideit @fredlf 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by ehazlett** [comment]
When trying to reset the environment I get the following:

```
$> eval "$(docker-machine env -u)"
Error: Expected one machine name as an argument.
```

**Comment by fredlf** [comment]
Docs LGTM, but you might want to scan through existing docs to make sure we don't have any examples doing things the old way.

**Comment by nathanleclaire** [comment]
> When trying to reset the environment I get the following:

Ah, right, forgot about that usage.  I'll update the "validation" to fix.

**Comment by nathanleclaire** [comment]
@ehazlett Ha, I fixed and I just discovered a bug.  If the IP of the machine is `""` because it is stopped, we will mistakenly think it is the active host.  I will update to check this case too.

**Comment by nathanleclaire** [comment]
OK, should be fixed now.

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
