### PR TITLE
Full rewrite of the vSphere driver

### PR DESCRIPTION
**Pull request by frapposelli**
This is a complete rewrite of the vSphere driver, this drops the `govc` requirement by using the `govmomi` library directly.

Also enhances auto detection of resources and general performance improvement.

Passes bats test:

```shell
machine · vspheredriver-with-govmomi ⟩ env DRIVER=vmwarevsphere \
                                       VSPHERE_DATASTORE="nfs_fas2020_15k_01" \
                                       VSPHERE_VCENTER="monster.ad.lab.gosddc.com" \
                                       VSPHERE_NETWORK="VM Network" \
                                       VSPHERE_USERNAME="root" \
                                       VSPHERE_PASSWORD="xxxxxxxxxxxx" \
                                       ./test/integration/run-bats.sh ./test/integration/core/core-commands.bats
=> ./test/integration/core/core-commands.bats
 ✓ vmwarevsphere: machine should not exist
 ✓ vmwarevsphere: create
 ✓ vmwarevsphere: ls
 ✓ vmwarevsphere: run busybox container
 ✓ vmwarevsphere: url
 ✓ vmwarevsphere: ip
 ✓ vmwarevsphere: ssh
 ✓ vmwarevsphere: docker commands with the socket should work
 ✓ vmwarevsphere: stop
 ✓ vmwarevsphere: machine should show stopped after stop
 ✓ vmwarevsphere: url should show an error when machine is stopped
 ✓ vmwarevsphere: env should show an error when machine is stopped
 ✓ vmwarevsphere: machine should not allow upgrade when stopped
 ✓ vmwarevsphere: start
 ✓ vmwarevsphere: machine should show running after start
 ✓ vmwarevsphere: kill
 ✓ vmwarevsphere: machine should show stopped after kill
 ✓ vmwarevsphere: restart
 ✓ vmwarevsphere: machine should show running after restart

19 tests, 0 failures
```

### CODE REVIEW

**Comment by ehazlett** [comment]
2015-07-14-182626_164x27_scrot

holy cow :)

**Comment by frapposelli** [comment]
@ehazlett that's the hard work of @pietern and @dougm for govmomi :smile:

**Comment by ehazlett** [comment]
We are planning plugins for 0.5.  I think this would be a prime candidate as this will remove the need for us vendoring all of the driver dependencies for the godeps.

**Comment by doxxx** [comment]
@frapposelli I'm trying out your rewritten driver and I'm having a problem creating machine in a cluster. Our vSphere environment has one DataCenter which contains a cluster of 4 ESXi hosts.

When I don't specify the `VSPHERE_HOSTSYSTEM` env var, I get this:

    Error creating machine: default host resolves to multiple instances, please specify

When I set `VSPHERE_HOSTSYSTEM=MyCluster/*`, I get this:

    Error creating machine: path 'MyCluster/*' resolves to multiple hosts

Previously with the govc-based driver, I was able to create a machine in the cluster on a randomly? selected host without specifying the compute host IP option.

**Comment by doxxx** [comment]
I'm also having a separate problem (after working around the previous problem by specifying one of the cluster's hosts explicitly) when it's trying to upload the ISO:
```
Uploading Boot2docker ISO ...
Error creating machine: 401 Unauthorized
```

I am able to upload files to the corresponding datastore folder using the vSphere client. On a related note, if I upload the boot2docker.iso from my local cache to the target folder, and then try to create the VM again the driver still tries to upload the ISO even though it already exists.

**Comment by doxxx** [comment]
When removing a VM, if the ISO doesn't exist, it doesn't try to remove the actual VM itself. Since the VM is created in vSphere before it attempts to upload the ISO, it should do the reverse when removing.

**Comment by doxxx** [comment]
So it turns out that to upload the boot2docker ISO using the current mechanism requires that my user be granted "low level operation" at the root of the vCenter, otherwise I get 401 Unauthorized responses when trying to access the the datastore files via the HTTP URL. My vCenter admin is not willing to grant these permissions since it allows a misconfigured or buggy tool to damage files owned by other users of the vCenter.

Quite frankly, I regard this as a flaw in vCenter's security model for this access method. Since the vSphere client is able to avoid this problem, there must be an alternative method of uploading the ISO file. Is it possible to use this instead?

**Comment by frapposelli** [comment]
@doxxx I'll look into it

**Comment by pandrew** [comment]
Great work! Hopefully this will be merged soon.

**Comment by dgageot** [comment]
@frapposelli plugins have changed quite a bit since 0.5.0-rc1. Can you rebase and check that it's still working? Thank you for the contribution!

**Comment by frapposelli** [comment]
@dgageot yes, will take a look at it this week.

**Comment by dgageot** [comment]
@frapposelli Did you have any chance to look at it?

**Comment by nathanleclaire** [comment]
Also, @frapposelli, this might be a good chance to start transitioning the `vmware*` plugins to their own external repositories.  Feel free to reach out to me at nathan@docker.com and we'll discuss how the transition should go.

**Comment by dgageot** [comment]
ping @frapposelli Any chance you could review this PR?

**Comment by frapposelli** [comment]
@dgageot are you guys still ok with keeping this part of core? I can definitely rebase it quickly if so.

**Comment by dgageot** [comment]
yes, no driver was extracted yet. No plan to do it before 0.6.0 at least

**Comment by frapposelli** [comment]
@dgageot just finished and pushed the rebase, ran an integration tests on my local environment, everything seems to be working just fine.

**Comment by dgageot** [comment]
LGTM

**Comment by jeanlaurent** [comment]
LGTM

**Comment by pandrew** [comment]
Yay!

**Pull request merged**
