### PR TITLE
Add shared folder and virtualization check for Linux.

### LINKED ISSUE #2110: support b2d on linux host
b2d install just fine on a Linux host, but the homedir is not mounted preventing from mounting volume in the container.
I have a patch for both b2d and docker-machine that would add support.

The issue is alrady logged in https://github.com/boot2docker/boot2docker/issues/1085 . Opening it here for visibility.

### PR DESCRIPTION
**Pull request by chantra**
Fixes #2110

### CODE REVIEW

**Comment by bascht** [comment]
<3

**Comment by dgageot** [comment]
LGTM. ping @jeanlaurent

**Comment by jeanlaurent** [comment]
@chantra Sounds like the VT-X detection by checking for `vmx` detects virtualization flags for intel cpu only. It sounds like we should also check for amd cpu with something like : `grep -E "vmx|smd" /proc/cpuinfo` and reflecting this change in https://github.com/chantra/machine/commit/42f1dbb9643dd681a1de9c58b49c2dc1056a450e#diff-37ee164f06f8f15faa89761d08488d4dR19

Note that I tested the `/proc/cpuinfo` trick on 3 differents linux host up to now, with no success. Although virtualization was on, as stated in `lscpu` see [1]. But `lscpu`is not as widely available as `/proc/cpuinfo` so we should stick with it for now.

Ca you make the necessary change to the code to detect amd virtualization flag ?


[1]
```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 70
Stepping:              1
CPU MHz:               2294.688
BogoMIPS:              4589.37
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
L4 cache:              131072K
```

**Comment by chantra** [comment]
Hi Jean-Laurent,
Yeah `lspcu` may not be available on every host so I would not rely on it.
When you mentioned you tested the `/proc/cpuinfo` trick to no avail on 3
hosts, was it because it did not check for `smd` flag?
If not. Can you gist the output of /proc/cpuinfo?
Also alternatively I wonder if /sys would expose the feature in some more
uniform way.

**Comment by jeanlaurent** [comment]
Yeah my bad this wasn't clear.
This was not linked to the `smd` flag.

Here are the cpuinfo of the 3 machines, two of which are running docker with no issue.

`cat /proc/cpuinfo` on an unbuntu host on a local vbox which runs docker flawlessly :
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 70
model name	: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
stepping	: 1
microcode	: 0x19
cpu MHz		: 2294.688
cache size	: 6144 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm
bugs		:
bogomips	: 4589.37
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

A low-end box, not running docker. But should be...
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 54
model name	: Intel(R) Atom(TM) CPU N2800   @ 1.86GHz
stepping	: 1
microcode	: 0x10d
cpu MHz		: 798.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm arat dtherm
bogomips	: 3733.28
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

A google cloud instance, running docker flawlessly
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU @ 2.50GHz
stepping        : 4
microcode       : 0x1
cpuid level     : 13
cpu MHz         : 2499.998
cache size      : 30720 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes xsave avx f16c rdrand hypervisor lahf_lm xsaveopt fsgsbase smep
bogomips        : 4999.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

**Comment by chantra** [comment]
So the issue is not that you cannot run docker, it is that if virtualization cpu flags are not enabled, it will make running docker in a VM dead slow. This is being handled in `drivers/virtualbox/virtualbox.go`

**Comment by nathanleclaire** [comment]
The shared folder bit looks good.  I'm not sure if checking `/proc` directly is really the best strategy, but I guess it might do the trick.  @tianon does it seem safe to you?

**Comment by jeanlaurent** [comment]
thx @chantra for adding the smd detection

LGTM

**Comment by dgageot** [comment]
LGTM

**Pull request merged**
