### PR TITLE
Add option parameter availability_zone for openstack

### PR DESCRIPTION
**Pull request by TrumanLing**
Add option parameter availability_zone for openstack

### CODE REVIEW

**Comment by nathanleclaire** [comment]
@TrumanLing please sign your commits with `git commit -s` and re-push.  Thanks!

**Comment by TrumanLing** [comment]
@nathanleclaire thx for your reminding. Done, please help to review.

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
@TrumanLing Can you please submit a follow-up PR adding this option to the documentation?  Thank you.

**Comment by ggiamarchi** [comment]
LGTM

**Comment by ehazlett** [comment]
@ggiamarchi thanks!

**Pull request merged**
