### PR TITLE
Driver flags

### PR DESCRIPTION
**Pull request by timfallmk**
Working PR for issue #1560 .

### CODE REVIEW

**Comment by timfallmk** [comment]
Anyone have a neat trick for accessing nested values in the `[]cli.Flags` interface? I need to get `cli.StringFlag{Name}`.

**Comment by cpuguy83** [comment]
Is this necessary with #1391 ?

**Comment by timfallmk** [comment]
@cpuguy83 Hadn't seen you PR, would have saved me a lot of swearing at `create.go` for the way `[]cli.Flags` was used :hurtrealbad: .

Can I make a request that there be an option for non-pretty-print output? Something that's more API consumable, like `-q`?

If you'd like I'll blow this all away and rebase off you're PR to add it to that.

**Comment by ehazlett** [comment]
Thanks for the contribution but I think we would go with #1391 in favor of this one.  Please feel free to comment on that one if you would like to see something in it.  Thanks!

**Comment by timfallmk** [comment]
@ehazlett That's fine. I don't think they're necessarily conflicting, this was just to add an APIs consumable way to get flags for drivers. That would still be necessary given #1391 .

FYI, this is necessary for ongoing work with kitematic. Right now we have to distributed our own forked `machine` binary.

**Pull request closed without merging**
