### PR TITLE
Add --amazonec2-block-duration-minutes flag

### PR DESCRIPTION
**Pull request by cifkao**
Add the --amazonec2-block-duration-minutes flag, analogous to
--block-duration-minutes from the AWS CLI.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Wow, looks popular :D

**Comment by nathanleclaire** [comment]
Code looks pretty reasonable, you need to run `gofmt` on it though

**Comment by cifkao** [comment]
The `gofmt` error seems to be unrelated to this PR since it doesn't modify `ls.go`:

```
commands/ls.go:452:6: expected operand, found 'range'
commands/ls.go:458:2: expected '{', found 'for'
commands/ls.go:463:2: expected ';', found 'return'
commands/ls.go:466:6: expected '(', found 'IDENT' newHostListItemInError
commands/ls.go:475:6: expected '(', found 'IDENT' sortHostListItemsByName
```

**Comment by nathanleclaire** [comment]
@cifkao Not sure where you're getting that, but in the [Travis log](https://travis-ci.org/docker/machine/jobs/163982243), you can see that the issue is with `drivers/amazonec2/amazonec2.go`:

```
drivers/amazonec2/amazonec2.go
make: *** [fmt] Error 1
mk/validate.mk:12: recipe for target 'fmt' failed
make: *** [build validate] Error 2
```

and I can see quite clearly that `defaultBlockDurationMinutes` equals sign is not aligned with the others, so the file clearly does need `gofmt`.  Thanks.

**Comment by cifkao** [comment]
Oh, I see. I'm getting the `ls.go` error when I run `make test`. I didn't see any specific message for `drivers/amazonec2/amazonec2.go` so I assumed it was fine.

**Comment by nathanleclaire** [comment]
LGTM... I'm going to squash these to one commit

**Comment by nathanleclaire** [comment]
Can you submit docs change to `https://github.com/docker/docker.github.io/tree/master/machine` please?  `vnext-machine` branch

**Pull request merged**
