### PR TITLE
Suggest clean up of usage for #1410

### PR DESCRIPTION
**Pull request by ericsage**
Signed-off-by: Eric Sage <eric.david.sage@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Why not include some sample output?  It would save time in reviewing the PR.  Generally I'm kind of skittish about changing the help text.

**Comment by ericsage** [comment]
Sure, I will post some sample output. Looking through the current descriptions, they seem to augment Usage, as the use of Usage doesn't really provide much in the way of useful information. By interpreting Usage as the unix style sample usage, and the description as describing what the command does, they have a better separation of concerns in my eyes. I think it would be even better to have an additional field in the template, but I wanted to go ahead and throw this out there. It seems to be difficult to add fields to the struct that gets applied to the templates without making some changes to codegansta/cli.

```bash
./machine

Commands:
  active		Print the active machine.
  config		Print the specified machine's connection configuration.
  create		Create a machine with the specified name.
  env			Display the commands to setup up the environment for the Docker client.
  inspect		Inspect information about a machine..
  ip			Get the ip(s) of one or more machines.
  kill			Kill one or more machines.
  ls			List machines.
  regenerate-certs	Regenerate TLS Certificates for a machine.
  restart		Restart one or more machines.
  rm			Remove one or more machines.
  ssh			Establish a secure connection to the machine, optionally supply a command to run on the target.
  scp			Copy files securely from host to the target machine, or vice-versa.
  start			Start one or more machines.
  stop			Stop one or more machines.
  upgrade		Upgrade one or more machines to the latest version of Docker.
  url			Get the url of a machine.
  help, h
```

```bash
./machine help ssh

Usage: docker-machine ssh <machine-name> [command]

Description:
   Establish a secure connection to the machine, optionally supply a command to run on the target.
```

**Comment by nathanleclaire** [comment]
Cool, thanks.

@hairyhenderson Having done some work on the help text before, WDYT?

**Comment by hairyhenderson** [comment]
Hmm... This is good _in principle_, but the whole `Usage` vs. `Description` thing is a little weird. The way the code stands right now, the auto-generated `help` command is missing its description, which looks a little odd.

Maybe if there's a way to get the help command's `Description` field populated, it would work...

It does seem that there's some use cases that aren't fully supported in `codegansta/cli`, so probably would be good to issue some PRs there too.

**Comment by ehazlett** [comment]
@ericsage would you be willing to look at `codegangsta/cli` to see if we can address there instead of this way as @hairyhenderson suggested?

**Comment by nathanleclaire** [comment]
I'm going to close this -- IMO it deviates too much from the prescribed `codegangsta/cli` style.  Please feel free to open an issue to discuss if you are adamant.

**Pull request closed without merging**
