### PR TITLE
Update AWS Credentials lookup to use AWS default provider chain.

### LINKED ISSUE #533: EC2 credentials could expire
Under certain situations, credentials could expire for the EC2 driver, i.e. when using roles.

We could perhaps mitigate it by checking credentials and then either asking for more or using env vars.

### LINKED ISSUE #3748: AWS Driver: Does not retrieve credentials from metadata service
docker-machine with AWS driver does not work well when actually run _from_ an ec2 instance with an IAM role assigned - in that case, even if credentials are not present in ~/.aws/credentials, the proper behavior is to retrieve them from `http://169.254.169.254/latest/meta-data/iam/security-credentials/...` which is what e.g. aws cli or the sdks do but for some reason docker-machine doesn't do that.

### PR DESCRIPTION
**Pull request by mrburrito**
This PR replaces #3763 and builds on the AWS SDK library update in #3772.

Fixes #3748 
Fixes #533 

This change adds support for automatic configuration of AWS credentials from Instance Roles when running `docker-machine` from an EC2 server or ECS container. It replaces the original credential lookup code with an Amazon ChainProvider that retrieves credentials from the first valid source in this list:

1. Static credentials from the `--amazonec2-access-key`, `--amazonec2-secret-key`, and `--amazonec2-session-token`command line options

1. Amazon's default credential chain: (at time of submission)
    a.  Environment Variables (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`)
    b.  Default profile in `~/.aws/credentials`
    b.  IAM Role (on supported AWS infrastructure)

### CODE REVIEW

**Comment by mjiderhamn** [comment]
Does anyone understand why the `vendor/github.com/aws/aws-sdk-go/` files still show up in [the diff](https://github.com/docker/machine/pull/3790/files) even though PR #3772 has been merged?

**Comment by mrburrito** [comment]
I opened this PR before that one was merged, building on those changes. I'll try to rebase and see if that clears things up. I'll re-open the PR if it doesn't.

**Comment by mrburrito** [comment]
Reopening.

**Comment by mrburrito** [comment]
Replaced by #3799

**Pull request closed without merging**
