### PR TITLE
Add environment varibles for OpenStack flags

### PR DESCRIPTION
**Pull request by ggiamarchi**
Some flags for the OpenStack driver did not have a corresponding environment variable. Among others, this is needed to run bats core tests with the OpenStack driver.

### CODE REVIEW

**Comment by dmp42** [comment]
@ggiamarchi can you rebase against master? Thanks

Other than that, LGTM.

@nathanleclaire wdyt?

**Comment by ggiamarchi** [comment]
@dmp42 @nathanleclaire Rebase done.

**Comment by dmp42** [comment]
@ggiamarchi LGTM

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
