### PR TITLE
Replace - with _ in bash completion documentation

### LINKED ISSUE #2529: Installing bash completion scripts documentation
Hi,
documentation for (https://docs.docker.com/machine/install-machine/) for centos7 seems to be wrong.
bash_completion is not installed by default , so it's has to be specifiied.
stiil have error -bash: __docker-machine-ps1: command not found 
Regards

### PR DESCRIPTION
**Pull request by Akasurde**
Fixes #2529 

Signed-off-by: Abhijeet Kasurde \<akasurde@redhat.com\>

### CODE REVIEW

**Comment by dgageot** [comment]
LGTM

**Comment by jeanlaurent** [comment]
LGTM

@Akasurde We have conflicting change on this documentation, can you rebase ?

**Comment by Akasurde** [comment]
OK, I will rebase this branch and send PR update.

**Comment by Akasurde** [comment]
Closing PR in favor of #2731

**Pull request closed without merging**
