### PR TITLE
Enable syncing time for VMWare Fusion guests

### PR DESCRIPTION
**Pull request by synfinatic**
By default, VMWare Fusion does not sync the guest OS's time to the host
and when running Fusion+docker-machine on a laptop the guest clock will
drift and not resync which can create a variety of problems (such as
authentication issues with AWS, etc)

### CODE REVIEW

**Comment by dgageot** [comment]
ping @frapposelli

**Comment by dgageot** [comment]
LGTM

**Comment by frapposelli** [comment]
Isn't boot2docker using `ntpd` to keep time in sync? using VMware tools to sync time is ok but it will lead to sudden time jumps (as it doesn't drift time).

**Comment by frapposelli** [comment]
Besides that comment, LGTM

**Comment by synfinatic** [comment]
The problem is when I suspend my laptop, the clock falls behind so far ntp won't resync in a reasonable amount of time.  In my case I'm seeing > 5min skew just by taking my laptop home after work which leads to AWS API auth failures. In my case, I'd definitely choose clock jumping to waiting hours for ntp to slew the clock.

**Comment by frapposelli** [comment]
@synfinatic fair enough, to be honest, we do have scripts to handle that scenario, but they're not included in boot2docker (I'll make it a todo item :) ).

@dgageot proper LGTM

**Pull request merged**
