### PR TITLE
Linting 1

### PR DESCRIPTION
**Pull request by dmp42**
This is only cleanup:

 * dead code removal
 * linting variable names
 * harmonizing return values on NewDriver
 * harmonize a couple of inline code comments

Now, linter passes except:

 * code documentation inline on exported stuff
 * amazon driver, which is erf

### CODE REVIEW

**Comment by dmp42** [comment]
This if a first step to fix #1887

These changes are innocuous, since they are really just renaming symbols.

Still it's important that we get this right before the drivers get out of the tree (since for example the dependency graph on libmachine is not clear).

**Comment by dgageot** [comment]
LGTM

**Comment by dgageot** [comment]
@dmp42 Can you rebase please?

**Comment by nathanleclaire** [comment]
Mmm might want to hold off until after the release to rebase these, so that it only has to be done once.

**Comment by nathanleclaire** [comment]
I think most of the changes probably will be OK, but we need to make sure not to change anything other than casing in the exported struct field names for Drivers (just a note for self and others) as it could cause issues with `json.Marshal`.

**Comment by nathanleclaire** [comment]
Oh yes, also, don't change anything in `cli/` -- it's essentially a vendored directory and progress on getting the PR merged in looks good, so hopefully soon I can re-add it to Godeps.

**Comment by dmp42** [comment]
Ok, thanks.
Since all this moved a lot, I'll close and resubmit soon.

**Pull request closed without merging**
