### PR TITLE
vbox: fix race with getting a tcp port

### PR DESCRIPTION
**Pull request by ehazlett**
This fixes the Bad Port: 0 error.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
This is pretty much what I had envisioned as well.

@SvenDowideit can you comment on if this seems tenable?

**Comment by SvenDowideit** [comment]
oh wow - did you really just code a permissions based infinite loop?

yes, users _can_ be forbidden from listening to a socket - this is the kind of UX reason i printed dots and o's - to give the user the idea that boot2docker had not hung.

mind you, the real problem used to be that machine didn't serialise this port number once it had used it for the vm, and that the port number assigned to any one of your vm's isn't actually being listened to unless the vm is up and running - so you can ask for an unused port, but tomorrow, it might be used.

I didn't find docs for `:0` in the golang `net` docs, so I don't know what ports it tries - but I presume you know what that is :)

**Comment by ehazlett** [comment]
@SvenDowideit so i was assuming vbox would give out an IP.  Are you saying there is a chance that vbox will not give any IP out and that it would loop forever?  If so, then we probably should leave this as the way it is and just error.  I would rather error then loop infinitely.

**Comment by SvenDowideit** [comment]
I have seen the vm creation fail in such a way that the vm has no network - its rare, but then yes, you'll get no IP

but - thats not what this code reads like (or is this running inside the vm?)

the way I read the code here, you're setting up to listen to a random port on the client box, and even that could loop forever (the eg I know about would be an selinux secure box where the user is denied listening on sockets)

**Comment by ehazlett** [comment]
Thanks @SvenDowideit.  I added a maximum retry for the allocation.  PTAL /cc @nathanleclaire

**Comment by nathanleclaire** [comment]
This LGTM.

@SvenDowideit any more thoughts?  Does a maximum retry count seem like an acceptable compromise to you?  And is there a more elegant solution we should be angling towards in the future?

**Comment by SvenDowideit** [comment]
I don't think you have a choice - you need to have a retry count, because at some point, you can't control what fails.

LGTM :)

**Comment by nathanleclaire** [comment]
Thanks Sven - think we're in a least of all evils situation here - LGTM

**Comment by ehazlett** [comment]
Thanks @SvenDowideit !

**Pull request merged**
