### PR TITLE
Add section on how to get help to docs

### PR DESCRIPTION
**Pull request by nathanleclaire**
Closes https://github.com/docker/machine/issues/976

cc @ehazlett @fredlf @ehazlett 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by fredlf** [comment]
Since I would like to use this as boiler-plate for the other projects as well, I wrote a revision to tighten it up and clarify it a little:

## Getting help

Docker Machine is still in its infancy and under active development. If you need help, would like to contribute, or simply want to talk about to the project with like-minded individuals, we have a number of open channels for communication.

* To report bugs or file feature requests: please use the [issue tracker on
  Github](https://github.com/docker/machine/issues).
* To talk about the project with people in real time: please join the `#docker-machine`
  channel on IRC.
* To contribute code or documentation changes: please submit a [pull request on
  Github](https://github.com/docker/machine/pulls).

For more information and resources, please visit
[https://docs.docker.com/project/get-help/](https://docs.docker.com/project/get-help/).

**Comment by ehazlett** [comment]
@fredlf +1 SGTM

**Comment by bfirsh** [comment]
@fredlf Nice! Here are relevant issues on the other projects: https://github.com/docker/swarm/issues/590 https://github.com/docker/compose/issues/1266

**Comment by ehazlett** [comment]
@nathanleclaire i think if we can get these updates we could get this into the 0.2.0 release.

**Comment by nathanleclaire** [comment]
@ehazlett Most definitely, I'll be putting @fredlf's suggestions in this PR today

**Comment by nathanleclaire** [comment]
Updated!

**Comment by fredlf** [comment]
LGTM, natch.

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
