### PR TITLE
add ap-south-1 (mumbai) to aws driver/docs

### PR DESCRIPTION
**Pull request by gauravarora**
@nathanleclaire I need this region for a project I am working on so I just made the changes that @jrupp sent in pr https://github.com/docker/machine/pull/3558 on the master branch using 16.04 images.

Signed-off-by: Gaurav Arora <gaurav@custvantage.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
We can't bump / change just a small subsection of the `vendor/`ed dependency.  What is the commit that you would like to change to in the SDK.  It needs to be referenced in Godeps.

**Comment by gauravarora** [comment]
I don't think we need to change `vendor` dependency at all. A change to `region.go` should allow new machines to be created, no?

I made the change based on https://github.com/docker/machine/pull/3558 because I thought it LGTM.

**Comment by nathanleclaire** [comment]
> I don't think we need to change vendor dependency at all. A change to region.go should allow new machines to be created, no?

Then why did https://github.com/docker/machine/pull/3558/files have changes to the vendored AWS SDK for Go?  Just adding this is not necessarily sufficient.  Have you successfully created `docker-machine`s in this region with this patch?

**Comment by gauravarora** [comment]
Apologies @nathanleclaire I had not tested this before opening the PR. I have done so now and am able to create a `docker-machine` successfully in ap-south-1.

I am not sure why #3558 had the vendored files but I looked at https://github.com/docker/machine/commit/c0d03b928eea4fb6cc5110753d5744e5a635fd6d and noticed that the new region, ap-northeast-2 was added without a change to vendor dependencies. I assume that means my PR is correct. If that is not the case please let me know and I will make any changes necessary.

**Comment by nathanleclaire** [comment]
I just don't understand why the original patch included the changes to the vendored files.  But you can confirm that this works for you without those changes?  i.e., with only the changes in this final PR?  If so please rebase / squash the changes into one commit and ping me to merge.

**Comment by gauravarora** [comment]
@nathanleclaire yes, I can confirm that I can create a docker-machine in ap-south-1 with these changes. I have squashed and rebased the changes.

**Comment by nathanleclaire** [comment]
Cool.

LGTM

**Pull request merged**
