### PR TITLE
vbox: use dns pass through

### PR DESCRIPTION
**Pull request by ehazlett**
This configures VirtualBox to use DNS pass through.

Closes: #1069 
Refs: boot2docker/boot2docker-cli#320

### CODE REVIEW

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
:+1:

**Comment by ehazlett** [comment]
Actual fix was in #1069 -- I accidentally implemented it here -- credit to @jfieber :+1:

**Pull request merged**
