### PR TITLE
Update Google Driver dependencies

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
ping @docker/machine-maintainers

**Comment by nathanleclaire** [comment]
Probably minor issue, but does `metaDataValue` need to pass an address instead of just the string value?

Other than that, LGTM

**Comment by dgageot** [comment]
Yes it does!

**Comment by nathanleclaire** [comment]
Seems kind on add API but OK.  LGTM

**Comment by dgageot** [comment]
Yes, their API is odd but de can't do anything about it. Don't you think so?

**Comment by nathanleclaire** [comment]
Yeah there's nothing we can do.  I'm sure there's a reason it's that way.  Doesn't bother me too much was just curious.

**Pull request merged**
