### PR TITLE
redhat: fix tty provision bug

### LINKED ISSUE #1245: RedHat Provisioning tty allocation
As part of #1242 the general `-t` was removed from the base args for the external SSH client.  This breaks provisioning on RedHat.

### PR DESCRIPTION
**Pull request by ehazlett**
This fixes #1245.

### CODE REVIEW

**Comment by ehazlett** [comment]
@nathanleclaire this fixes the bug.  there is some duplication as we need to use the RedHat provisioner in the `SetHostname` func.  For now, it works.  PTAL

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
Would be good to get test(s) in for this somehow, not exactly sure how though.  Maybe a test specifically using `amazon` driver with a custom AMI.

**Comment by ehazlett** [comment]
Yeah good idea.  I will do that in a follow up (#1250).

**Pull request merged**
