### PR TITLE
Change binary name to docker-machine

### PR DESCRIPTION
**Pull request by sthulb**
In an effort to complete #2!

- [x] Change readme
- [x] Update build script
- [x] `machine config` directive (#388)
- [x] Update release script
- [x] Update Docs

Signed-off-by: Simon Thulbourn <simon+github@thulbourn.com>

### CODE REVIEW

**Comment by sthulb** [comment]
This is complete, although, please check the release script to make sure :)

**Comment by nathanleclaire** [comment]
Mostly looks great - there are a few things you missed that I noticed, I'll make a PR

**Comment by nathanleclaire** [comment]
@sthulb  https://github.com/sthulb/machine/pull/1 

Thanks a lot for doing this.  It looks like a real pain and now it's one less thing to worry about for the release so it is very appreciated.

**Comment by sthulb** [comment]
Thanks @nathanleclaire

**Comment by ehazlett** [comment]
Thanks @nathanleclaire @sthulb !

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
