### PR TITLE
FIX #2171 issue with amazonec2-private-address-only

### LINKED ISSUE #2171: EC2 issue with version .5 amazonec2-private-address-only
I am having an issue with the new version of docker machine.

Running the following command

docker-machine --debug create --driver amazonec2 --amazonec2-subnet-id subnet-24abec0f --amazonec2-zone b --amazonec2-private-address-only swarm-demo2

the result is 
Error: No machine name specified

If I remove amazonec2-private-address-only option, it works, but I can't connect to it since the machine isn't accessible using the public ip.

Running in debug shows this

(swarm-demo2) Calling RpcServerDriver.GetSSHPort
(swarm-demo2) Calling RpcServerDriver.GetSSHKeyPath
(swarm-demo2) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
About to run SSH command:
exit 0
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
command : exit 0
err     : exit status 255
output  :

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
@docker/machine-maintainers PTAL

**Comment by nathanleclaire** [comment]
There's some tests and stuff for other drivers in here.  Why not split them out to a separate PR?

**Comment by dgageot** [comment]
@nathan I wrote a test to show the pb, then fixed, then applied the test for all the drivers to make sure we didn't have other bugs. So that's really a whole.

**Comment by nathanleclaire** [comment]
OK -- in this case I don't think it's particularly problematic but I'm trying to move towards smaller PRs in general, so splitting this into 2 would have been nice.

Could you please change the commit message to something like `Fix faulty flag and add tests for GetConfigFromFlags` since it's more general than the original message?  After that, LGTM

**Comment by nathanleclaire** [comment]
Cool thx

**Comment by dmp42** [comment]
LGTM

**Pull request merged**
