### PR TITLE
Add mutex and test for safe concurrent VBoxManage access

### PR DESCRIPTION
**Pull request by nathanleclaire**
Closes https://github.com/docker/machine/issues/2154

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Like I said I think it may allow us to also remove the serial bit in `runActionForeachMachine` as well.  We'll see.

**Comment by nathanleclaire** [comment]
@docker/machine-maintainers PTAL

**Comment by dmp42** [comment]
This is tripping a race condition apparently.

**Comment by nathanleclaire** [comment]
Yeah, I noticed that.  I'm actually not sure how much good the test is doing in this case (since essentially it's elaborate test of mutex itself), so I might just take it out.

**Comment by nathanleclaire** [comment]
Alright, how about this:  I've turned off running this test on `go test -race` using build tag exclusion.  I want to still have the test run in CI, however, so I also added a line to `test-long` target in Makefile to also run `go test` _without_ -race.  The overhead is not really substantial as far as I can tell (a few extra seconds).  This seems to be a reasonable compromise to me.

**Comment by nathanleclaire** [comment]
To be clear, it's intentional that the test races.

**Comment by dmp42** [comment]
> however, so I also added a line to test-long target in Makefile to also run go test without -race

Ah - I don't think you need this actually - `test-short` will already run your test (unless your test is specifically meant to run only on `long`?).

@docker/machine-maintainers PTAL

**Comment by nathanleclaire** [comment]
Right, I see.  I'll take the Makefile change out then.  Should be good to go since you have to intentionally mark tests which will get skipped with short, which I haven't done here.

**Comment by dgageot** [comment]
@nathanleclaire I've tested the code with #2154 and it does not solve the issue.

Also, adding a mutex is a way to not serialize actions in `runActionForeachMachine()`. Could you please simplify this function?

Regarding the test, it's well known that using `time.sleep` leads to unreliable and slow tests. Could we find another implementation for that test?

Also, FYI, reopening https://github.com/docker/machine/pull/2172 which actually fixes the #2154 issue. When the mutex is fully functional, it'll be a pleasure to simplify the code for `runActionForeachMachine()` and `ls.go`

**Comment by dgageot** [comment]
@nathanleclaire shall we close this PR? Clearly, the mutex has no effect since each `virtualbox` driver is running in its own process.

**Comment by nathanleclaire** [comment]
@dgageot Yep

**Pull request closed without merging**
