### PR TITLE
Generate more generic certificates that can have other uses.

### PR DESCRIPTION
**Pull request by huslage**
Added `Digital Signature, Key Encipherment, Key Agreement` Key Usage values.

Signed-off-by: Aaron Huslage <aaron@docker.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
@huslage This looks like it is probably fine but could you elaborate a little bit on use case?

**Comment by huslage** [comment]
The SSL generating code is currently used as a library by @ehazlett in a
tool called cert-tool. I would like for that tool to be able to act as a
mini-PKI so that setting up SSL on registries is as easy as signing a cert
with the CA generated here.

On Tuesday, May 12, 2015, Nathan LeClaire <notifications@github.com> wrote:

> @huslage <https://github.com/huslage> This looks like it is probably fine
> but could you elaborate a little bit on use case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/pull/1119#issuecomment-101443319>.
>


-- 
Aaron Huslage
Solution Architect - Docker, Inc.
+1-919-600-1712

**Comment by nathanleclaire** [comment]
I'll test this to make sure it doesn't break anything obvious in our existing workflow, but mostly looks pretty good.

**Comment by huslage** [comment]
Anything?

**Comment by ehazlett** [comment]
Sorry this one missed my radar.  LGTM

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
