### PR TITLE
Add note about pre-create check and exit code

### PR DESCRIPTION
**Pull request by nathanleclaire**
Requires: https://github.com/docker/machine/pull/2807

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
cc @docker/machine-maintainers PTAL

Blarg, docs are failing.  @SvenDowideit @londoncalling ?

**Comment by londoncalling** [comment]
@SvenDowideit (per @moxiegirl) it looks like you need to kick off another Docs build here, and neither of us have Jenkins permissions right now. Sven can you please re-kick this build? Thanks!

**Comment by dgageot** [comment]
Merged with https://github.com/docker/machine/pull/2826

**Comment by nathanleclaire** [comment]
:+1:

**Pull request closed without merging**
