### PR TITLE
CLI progress/activity indicator

### PR DESCRIPTION
**Pull request by janeczku**
This implements a progress/activity indicator for commands that take longer than a couple of seconds.

Please feel free to comment or push against this PR's branch if you think the code needs improvement in some way or another.

[asciicast](https://asciinema.org/a/agfb5vwtr0szwsw5p8rkcwo2t)

Related to #230
cc: @ahmetalpbalkan @ehazlett @nathanleclaire

Signed-off-by: Jan Broer <janeczku@yahoo.de>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Pretty interesting patch.  I will check it out soon.

**Comment by ahmetalpbalkan** [comment]
I think we should keep the intermediate steps instead of removing them and using only one line. "Docker pull" also has an animation but at the end you see what's happened on each line (i.e. what layers are downloaded). In this case providing more info about the steps can be better IMO.

**Comment by nathanleclaire** [comment]
+1 @ahmetalpbalkan ... the more info, the merrier.

**Comment by janeczku** [comment]
@ahmetalpbalkan Yeah, we can keep those lines and prefix them with a "+" or similar.

**Comment by ehazlett** [comment]
:heart_eyes: 

+1 @ahmetalpbalkan

**Comment by zchee** [comment]
+1
Awesome user experience!

**Comment by janeczku** [comment]
@zchee  :stuck_out_tongue:

**Comment by ahmetalpbalkan** [comment]
@janeczku any plans to move this forward? looks really cool.

**Comment by janeczku** [comment]
@ahmetalpbalkan, the patch is functional as is. Whether it gets moved forward is not really my call: @nathanleclaire @ehazlett

**Comment by nathanleclaire** [comment]
Sorry to be the difficult one here, I appreciate the work, but I think it is best for us if we keep our logging / terminal handling as simple as possible.  However, the good news is that a lot of the work I've been doing with `libmachine` should make creating your own Go wrapper to do whatever fancy tricks you want with the output a lot easier.

**Comment by ahmetalpbalkan** [comment]
:+1: :clap:

**Comment by janeczku** [comment]
@nathanleclaire, i appreciate your explanation and where you are taking `libmachine` with the new API capabilities :+1: 
I do  however disagree with the characterization of this PR as "fancy trick". I don't think this is a fair characterization of what this patch actually implements: Satisfying a basic principle of UI design.
Currently there *is* a lack of feedback during long running commands in `docker-machine`: Often the CLI will just sit there for 10 seconds or even half a minute and longer after the user issued a command -  leaving the user to wonder whether the app has hung-up. 

[UI Design principle No. 1 according to Jakob Nielsen](http://www.designprinciplesftw.com/collections/10-usability-heuristics-for-user-interface-design)

> **Visibility of system status**
The system should always keep users informed about what is going on, through appropriate feedback within reasonable time.

That being said, I am sure there are different and maybe better ways to tackle this UX issue than what constitutes this particular PR. I just wanted to stress that there is need for something like this.

**Comment by nathanleclaire** [comment]
> That being said, I am sure there are different and maybe better ways to tackle this UX issue than what constitutes this particular PR. I just wanted to stress that there is need for something like this.

I agree, and I think it would be better addressed by a simpler method such as printing a `.` periodically while waiting for SSH and a `o` while waiting for the Docker daemon (similar to how b2d-cli worked), and/or printing messages to indicate "This may take a few minutes" where relevant.  Because the Machine CLI and log need to work flexibly in a variety of different situations and OSes, I'm wary of introducing too much complexity.

**Pull request closed without merging**
