### PR TITLE
Fixing inaccurate Usage message for the `--openstack-net-id` option

### PR DESCRIPTION
**Pull request by hairyhenderson**
Signed-off-by: Dave Henderson <Dave.Henderson@ca.ibm.com>

### CODE REVIEW

**Comment by ehazlett** [comment]
LGTM 

/cc @ggiamarchi

**Comment by ggiamarchi** [comment]
LGTM

**Comment by hairyhenderson** [comment]
Anything more before this can be merged?

**Comment by ehazlett** [comment]
@hairyhenderson thanks!

**Pull request merged**
