### PR TITLE
Added a Disk Size parameter for Google Compute Engine.

### PR DESCRIPTION
**Pull request by saturnism**
Signed-off-by Ray Tsang <saturnism@gmail.com>

### CODE REVIEW

**Comment by ehazlett** [comment]
Thanks!  Can you sign the commit and format (gofmt -s -w)?

**Comment by ehazlett** [comment]
This doesn't seem to be working for me.  Using the following:

```
machine create -d google --google-disk-size 14 test-gce
```

I get:

```
Disk /dev/disk/by-uuid/7409bd05-49d0-4262-b4ff-292f7df325d2: 10.7 GB, 10735321088 bytes
```

**Comment by ehazlett** [comment]
Closing this as it has been stagnant.  Please re-open if you can get the above addressed and rebased.  Thanks!

**Comment by saturnism** [comment]
Hiya! My bad - please re-open.  I noticed master is now using ubuntu image.  This should actually work now.  Apologies for the delay.

**Comment by saturnism** [comment]
I've also push the latest code rebased to the upstream master.

**Comment by ehazlett** [comment]
You will need to open a new PR.  Thanks!

**Pull request closed without merging**
