### PR TITLE
Update flag help explanation and VirtualBox version line

### PR DESCRIPTION
**Pull request by nathanleclaire**
Mostly the changes here update the `create` section to be in accordance with the new plugin model but there's some wrap pedantism bundled in as well.  Hopefully it's not problematic, I think it was either automatically done by my editor or by me fiddling (I compulsively `V`+`gw` in vim to wrap when editing markdown).

cc @moxiegirl @docker/machine-maintainers WDYT

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
@londoncalling you'll want to review this. It hits the Machine project.  @nathanleclaire  Vicky is going to be y'alls dedicated writer. So, I'd like her to start reviewing...hope this is an OK one to start on.

**Comment by nathanleclaire** [comment]
@moxiegirl OK cool.  Welcome @londoncalling (nice nick btw :)).  This PR should be pretty reasonable to get started with.

**Comment by londoncalling** [comment]
I'm on it :+1:  :-)

**Comment by dgageot** [comment]
LGTM

**Comment by londoncalling** [comment]
LGTM

**Comment by nathanleclaire** [comment]
:+1:

**Pull request merged**
