### PR TITLE
docs: update usage info for env shell options

### PR DESCRIPTION
**Pull request by ehazlett**
Updates docs for new env shell selection usage.

### CODE REVIEW

**Comment by ehazlett** [comment]
@nathanleclaire PTAL

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
Hm, sorry, that was a little impulsive: I think I'd rather it say, "To see how to connect Docker to this machine, run:"

**Comment by nathanleclaire** [comment]
Just because "the configuration settings for this machine" could be a variety of different things.

**Comment by ehazlett** [comment]
@nathanleclaire updated and rebased.  PTAL

**Comment by nathanleclaire** [comment]
Nice. LGTM

**Pull request merged**
