### PR TITLE
Add Aliyun ECS Docker Machine Driver Plugin

### PR DESCRIPTION
**Pull request by menglingwei**

### CODE REVIEW

**Comment by menglingwei** [comment]
support aliyun cloud driver ecs.console.aliyun.com #2973

**Comment by dgageot** [comment]
Hi @menglingwei can you squash your changes into a single commit? Thanks!

**Comment by menglingwei** [comment]
@dgageot ok。Thanks

**Comment by dgageot** [comment]
@menglingwei Sorry but you didn't really squash your commits

If your repository points to `docker/machine` as `upstream` and to your fork as `origin`, here's one way to clean up everything:

```
git fetch upstream
git checkout -b add-aliyun upstream/master
git cherry-pick cc38926919d757e977276a4fa7d90b9ba4ff6b2c
git commit --amend -s --no-edit
git push origin add-aliyun
```

Add create a clean PR from that branch.

**Comment by menglingwei** [comment]
@dgageot  thanks, i created a clean PR   https://github.com/docker/machine/pull/3154 .

**Comment by dgageot** [comment]
Thanks @menglingwei

**Comment by dgageot** [comment]
Merged with https://github.com/docker/machine/pull/3154

**Pull request closed without merging**
