### PR TITLE
Fix for #2244 - make fails with https remote url

### PR DESCRIPTION
**Pull request by jeanlaurent**

### CODE REVIEW

**Comment by dmp42** [comment]
New version doesn't `cut` like it should.
You might want to bring back the initial sed.

**Comment by dmp42** [comment]
Still not working :)

**Comment by jeanlaurent** [comment]
Well if was working for ssh remote and broken for https remote. 
The 1st fix broke things, the other way around ssh ko  & http ok

Should be fixed for both now.

**Comment by dgageot** [comment]
@dmp42 PTAL

**Comment by dmp42** [comment]
LGTM. Maybe we want to still `2> /dev/null` if not in a git repo? (though admittedly we shouldn't allow publication at all in that case).

**Comment by nathanleclaire** [comment]
Why not just set these variables to default to `docker` and `machine`?  It's trivially easy to override them from the command line if you want to change them, so why get clever?  e.g.:

```console
$ cat Makefile
FOO := bar

default:
        echo ${FOO}
$ make
echo bar
bar
$ make FOO=quux
echo quux
quux
$
```

**Comment by dgageot** [comment]
+1

**Comment by nathanleclaire** [comment]
I've submitted https://github.com/docker/machine/pull/2278 instead

**Comment by dmp42** [comment]
@nathanleclaire I believe we disagree on this, so we should discuss this more.
Let's sit together when you can.

**Comment by dgageot** [comment]
@nathanleclaire, @dmp42 let's move on with that one. Let's look at the facts:

+ Both https://github.com/docker/machine/pull/2245 and https://github.com/docker/machine/pull/2278 do the job of fixing #2244
+ https://github.com/docker/machine/pull/2245 keeps the current property of working on a clone or a renamed repo. So it's more user friendly.
+ We have bigger fish to fry

I'm going to LGTM that one and close https://github.com/docker/machine/pull/2278

**Comment by dgageot** [comment]
LGTM

**Pull request merged**
