### PR TITLE
Fix some docs issues

### PR DESCRIPTION
**Pull request by nathanleclaire**
Closes https://github.com/docker/machine/issues/1468

cc @ehazlett @moxiegirl please review.

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
LGTM

@nathanleclaire @bfirsh @ehazlett I'd like to split out the Docker Machine docs the file is already pretty big and getting more so. It makes PRs hard to manage when all the content is in a single file.

 Let me know if that's ok with you guys.  It will probably taking me about an hour, maybe two.

**Comment by ehazlett** [comment]
LGTM

**Comment by ehazlett** [comment]
@moxiegirl this sounds great to me!

**Comment by ehazlett** [comment]
@moxiegirl thanks!!

**Comment by nathanleclaire** [comment]
> @nathanleclaire @bfirsh @ehazlett I'd like to split out the Docker Machine docs the file is already pretty big and getting more so. It makes PRs hard to manage when all the content is in a single file.

SGTM!

**Pull request merged**
