### PR TITLE
Bail on failed SSH command with information about what failed

### PR DESCRIPTION
**Pull request by nathanleclaire**
@ehazlett @bfirsh @prologic WDYT?

Closes https://github.com/docker/machine/issues/1266 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by prologic** [comment]
We can't just test for the exit code directly?

**Comment by nathanleclaire** [comment]
@prologic There's no cross platform way to do so that I am aware of (see http://stackoverflow.com/questions/10385551/get-exit-code-go, for instance).

**Comment by prologic** [comment]
Hmm I find this quite surpsingly really See [Popen.returncode](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.returncode) -- Unless the Python standard library has been lying to me this whole time!

**Comment by prologic** [comment]
Go really has no platform independent way of returning the exit status of a subprocess?

**Comment by nathanleclaire** [comment]
> Go really has no platform independent way of returning the exit status of a subprocess?

AFAICT not really.  There are some "hack-arounds", and it's fairly easy to tell whether a process failed or succeeded, but I think the actual numeric codes are fairly platform-specific.

**Comment by prologic** [comment]
Weird but okay :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by bfirsh** [comment]
Nice!

Might be worth explaining a little clearer what's going on to make it less scary: "Machine ran a command on a host using SSH and it failed:"

Does the upstream error also explain how you might recover from this? (e.g. remove the host and try creating it again)

**Comment by nathanleclaire** [comment]
cc @ehazlett --- I'm not sure about this exact output format but I _really_ want to get this in for the next release as our failing SSH commands right now and not spitting out much that's useful.

**Comment by ehazlett** [comment]
I think we can tweak the output later.  I agree it would be great to have this soon.

LGTM

**Comment by nathanleclaire** [comment]
Pending Travis, LGTM.  Should work with native and external SSH both.

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
