### PR TITLE
support for fish shell in env command

### PR DESCRIPTION
**Pull request by databus23**
This is basically ported from boot2docker-cli

### CODE REVIEW

**Comment by ehazlett** [comment]
LGTM

**Comment by ehazlett** [comment]
@databus23 i'm having trouble getting this to work in general (i.e. `(docker-machine env dev)` is giving me an `fish: Illegal command name`.  Tried with fish v2.1.2.  any ideas?

**Comment by databus23** [comment]
How are you sourcing the output of `docker-machine env dev`?

I do `docker-machine env dev | source`.

**Comment by databus23** [comment]
Ah I overlooked the `()` in your post.

That does not work, command substitution in fish works different then in bash. You have to do ` ... | source` to set the environment in fish.

**Comment by ehazlett** [comment]
Whew thanks!  I'll update the docs.

**Pull request merged**
