### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by dgageot** [comment]
Thank you @Godin, you need to sign the commit though

**Comment by Godin** [comment]
@dgageot you mean with GPG and not just with "Signed-off-by" line as it was already done?

**Comment by dgageot** [comment]
It's good like that! I thought I saw Gordon complaining

**Comment by dgageot** [comment]
LGTM

**Comment by Godin** [comment]
@dgageot yep he did, but I corrected ;)

**Comment by jeanlaurent** [comment]
LGTM

**Pull request merged**
