### PR TITLE
Fix driver CPU inconsistency

### PR DESCRIPTION
**Pull request by nathanleclaire**
Carrying change to try and avoid DCO freakout from https://github.com/docker/machine/pull/3494

Thanks @philips

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by philips** [comment]
LGTM.

Any idea what I did wrong with the DCO? I have contributed to lots of github.com/docker projects in the past... the turtle just got really mad at me :)

**Comment by nathanleclaire** [comment]
Probably not your fault, the bot has bugs sometimes.  Probably there was just some situation it did not expect that broke its code :)

**Comment by philips** [comment]
Fair enough. If someone wants to look into it I first pushed w/o the signed-off-by then realized my mistake and seconds later force pushed with a fix. Maybe a time race?

**Comment by nathanleclaire** [comment]
Yup, sounds like that caused a race that sent the whole state sideways.

**Pull request merged**
