### PR TITLE
Fix none driver socket issue

### LINKED ISSUE #643: Cannot use unix socket URL with none driver
I use ssh & socat to port forward a remote /var/run/docker.sock as a local unix socket.
I add this local unix socket using the none driver.

docker-machine ls output:
```
NAME    ACTIVE   DRIVER         STATE     URL                                             SWARM
dev              vmwarefusion   Running   tcp://192.168.2.130:2376
vultr   *        none                     unix:///Users/bsuh/.remote-sockets/vultr.sock
```

docker-machine env output:
```
docker-machine env vultr
set -x DOCKER_TLS_VERIFY yes
set -x DOCKER_CERT_PATH /Users/bsuh/.docker/machine/machines/vultr
set -x DOCKER_HOST unix:///Users/bsuh/.remote-sockets/vultr.sock
```

It tries to use TLS on a Unix socket URL.

### PR DESCRIPTION
**Pull request by nathanleclaire**
Fixes #643.

PLEASE DO NOT MERGE YET.  I want to add tests first.

cc @ehazlett 

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by bsuh** [comment]
Should it unset environment variables and then set them? If your previous machine had TLS on and you change to a machine using unix sockets, it seems like TLS would remain on.

**Comment by ehazlett** [comment]
I'm not a fan of this.  This will mean we will need to throw errors for `start`, `stop`, `ssh`, `upgrade`, and `kill`.  Seems counter-intuitive.  I can see the benefit of seeing the local instance if there is one, but why not just `$(docker-machine env -u)`?

**Comment by bsuh** [comment]
The none driver already throws errors for those.

**Comment by ehazlett** [comment]
@bsuh true, but I'm not sure where that is used outside of testing.  I guess it fits in this case but I'm not sure we should have a driver that negates the majority of the functionality.

**Comment by bsuh** [comment]
To be honest, I'm just getting my feet wet with devops with side projects, so perhaps I'm not the target audience for machine. I'm not using Docker to build distributed systems, but I use it for isolation. I don't need to create a lot of Docker hosts automatically or bring them up and down, but I'd still like to use machine for keeping a list of hosts & connecting to those hosts that I create manually on unsupported hosting services. If the none driver already exists and supports TCP sockets, I don't see why it couldn't support Unix sockets.

**Pull request closed without merging**
