### PR TITLE
Verifying the --swarm-discovery flag

### LINKED ISSUE #1604: Proposal: Commands with "token://" should error out if "//" is omitted
The "--swarm-discovery token://" option should terminate with an error message if the user does not specify "//".

I have watched two people complete the Swarm "Getting Started" guide, and both specified "token:flkajdkasdl" instead of "token://flkajdkasdl".

For both cases, the individuals were confused by the documentation, and thought the '//' meant that the token value was a comment. They didn't realize that // is required.

To avoid confusion, the command should terminate with an error when 'token://' does not include the double-slashes.

### PR DESCRIPTION
**Pull request by hairyhenderson**
Fixes #1604 

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by ehazlett** [comment]
@hairyhenderson the tests are failing

**Comment by hairyhenderson** [comment]
@ehazlett - d'oh - fumbled the `git commit` there... Should pass now... ;)

**Comment by nathanleclaire** [comment]
LGTM

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
