### PR TITLE
Add docker-machine provision command

### PR DESCRIPTION
**Pull request by nathanleclaire**
Revised to new `libmachine` changes etc.

cc @docker/machine-maintainers 

~~TODO:~~

- [x] Docs
- [x] Tests

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
@dmp42 Why change the milestone to 0.6.0 from 0.5.1?

**Comment by dgageot** [comment]
@nathanleclaire Can you please rebase? ;-)

**Comment by nathanleclaire** [comment]
Docs and tests added and rebased -- There's definitely a decent chance CI will go red on this one so if it's not green I'll fix everything up tomorrow.

**Comment by nathanleclaire** [comment]
cc @londoncalling for docs review

**Comment by londoncalling** [comment]
@nathanleclaire  LGTM on Docs (machine/docs/reference/provision.md)

**Comment by nathanleclaire** [comment]
@docker/machine-maintainers CI green -- lemme know if it LGTY

**Comment by nathanleclaire** [comment]
;_; docs are failing @SvenDowideit please fix it with your magic

**Comment by dgageot** [comment]
LGTM

**Comment by jeanlaurent** [comment]
LGTM

I would merge but doc build is failing ( @SvenDowideit )

**Comment by londoncalling** [comment]
cc Sven and Mary re: docs build ..

**Comment by moxiegirl** [comment]
@londoncalling there is an issue with the docs-build system that causes intermittent problems. Let's merge this for now.

**Comment by londoncalling** [comment]
👍

**Comment by nathanleclaire** [comment]
Pinged @SvenDowideit on this, hopefully he'll reply soon.

**Comment by SvenDowideit** [comment]
awesome, thank you - @thaJeztah we have one :)

**Comment by SvenDowideit** [comment]
test this please

**Comment by nathanleclaire** [comment]
Yay it's all green from @SvenDowideit magic.  @dgageot @jeanlaurent PTAL

**Comment by thaJeztah** [comment]
oh! cool!

**Pull request merged**
